Simulink.defineIntEnumType( 'ActvnAvl3', ...
   {'Idle','Actvn','Deactvn'}, ...
   [0 1 2], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirDirModReq', ...
   {'Normal','Focus','Avoid','Customize'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirFragSts', ...
   {'OFF','ON','Error'}, ...
   [1 2 3], ...
   'DefaultValue', 'OFF', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForInteriorViewCamera', ...
   {'Undefd','WithoutCamera','WithInterViewCamera','WithInterViewCameraOtherM'}, ...
   [0 1 2 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPowerSeats', ...
   {'Undefd','NoMemory','DrvrMemoryPassMechanical','DrvrMemoryPassWoMemory','DrvrAndPassMemory','DrvrWoMemoryPassMechanical','DrvrAndPassWoMemory','DrvrAndPassPwrSeatWithSlutn','PassMemoryDrvrWoMemory'}, ...
   [0 1 2 3 4 80 81 82 83], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtClngActv', ...
   {'Off','OnLvlLo','OnLvlMed','OnLvlHi'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtTFrntQf', ...
   {'SnsrDataUndefd','FanNotRunning','SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SnsrDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DrvrPfmncWarnReq', ...
   {'Unavailable','Unknown','NoWarning','Distractive','Warninglevel1','Warninglevel2_Navigation','Warninglevel2'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'Unavailable', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ElcTrLFtngMdle', ...
   {'Undefd','NtEqpdWthElcTrFtngMdle','EqpdWthElcTrFtngMdle'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Flg1', ...
   {'Rst','Set'}, ...
   [0 1], ...
   'DefaultValue', 'Rst', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HeadRadar', ...
   {'UnDefd','WithoutRadar','WithOMC','WithTOF','WithOMCAndTOF'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'UnDefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtTSpSpcl', ...
   {'Norm','Lo','Hi'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacTIfQf', ...
   {'SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1], ...
   'DefaultValue', 'SnsrDataNotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NoYes1', ...
   {'No','Yes'}, ...
   [0 1], ...
   'DefaultValue', 'No', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of NoYes1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PassSeatSts1', ...
   {'Empty','Fmale','OccptLrg','Ukwn'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Empty', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qf1', ...
   {'DevOfDataUndefd','DataTmpUndefdAndEvlnInProgs','DevOfDataNotWithinRngAllwd','DataCalcdWithDevDefd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'DevOfDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qly2', ...
   {'Flt','NoInfo','Vld'}, ...
   [0 1 2], ...
   'DefaultValue', 'Flt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'StrtRemSts1', ...
   {'Idle','Strtg','Actv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'StsFd', ...
   {'None','On','Off','Error','Functionallimit','Energylimit','Resvd1','Resvd2'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SunSnsrQf', ...
   {'SnsrDataUndefd','Resd','SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SnsrDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of SunSnsrQf.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnStsRsp', ...
   {'Stop','Running','Calibration'}, ...
   [0 1 2], ...
   'DefaultValue', 'Stop', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WndFllwngHmnMvmntFnctn', ...
   {'Undefd','WithtFunctn','FcsOnDrvr','FcsOnDrvrAndPss','FcsOnDrvrAndSec','FcsOnDrvrAndPssAndSec','FrntNonFcsBse','FrntNnFcsAvdnc','SecNonFcsBse','SecNonFcsAvdnc'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

