Simulink.defineIntEnumType( 'ActrReq', ...
   {'Off','On','AutOn'}, ...
   [0 1 2], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirMtrlSnsrReq', ...
   {'SNA','Off','On','Calibrate'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SNA', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirPmQf', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'BookChargeSetResponse', ...
   {'Default','Success','Cancelled','Fail'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForAirMtrlSnsrGly', ...
   {'Undefd','WithoutInOutPM25','WithInPM25','WithInOutPM25','WithInPM25US'}, ...
   [0 1 2 3 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaOffReq', ...
   {'NoReq','SecRowOffReq','TrdRowOffReq','ClimaOff'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmpmtAirPmLvl', ...
   {'Level1','Level2','Level3','Level4','Level5','Level6','Reserved','Invalid'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Level1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of CmpmtAirPmLvl.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DoorSts2', ...
   {'Ukwn','Opend','Clsd'}, ...
   [0 1 2], ...
   'DefaultValue', 'Ukwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FanErr', ...
   {'Noerr','Speedunstable','Poorcontact','Brokenline'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Noerr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of FanErr.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtTSpSpcl', ...
   {'Norm','Lo','Hi'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacFanLvl', ...
   {'Off','LvlMan1','LvlMan2','LvlMan3','LvlMan4','LvlMan5','LvlMan6','LvlMan7','LvlMan8','LvlMan9','LvlAutMinusMinus','LvlAutMinus','LvlAutNorm','LvlAutPlus','LvlAutPlusPlus','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'IntPmHiPopUp', ...
   {'NoReq','ClimaOn','ClimaOnAndWinClsd','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PmSnsrErrSts', ...
   {'NoError','ShortToGroundOrOpenCircuit','ShortToBatt','Resvd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoError', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PmSnsrSts', ...
   {'Initial','Collecting','Complete','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Initial', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ReqSts1', ...
   {'NotReqd','Reqd'}, ...
   [0 1], ...
   'DefaultValue', 'NotReqd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VehMktGlb', ...
   {'SNA','World','Europe','NorthAmerica','SouthAmerica','MiddleEastAfrica','SouthEastAsia','Pacific','Russia','Korea','China','Taiwan','Japan','India','Israel','Turkey','Spare'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16], ...
   'DefaultValue', 'SNA', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WinAndRoofAndCurtPosnTyp', ...
   {'PosnUkwn','ClsFull','PercOpen4','PercOpen8','PercOpen12','PercOpen16','PercOpen20','PercOpen24','PercOpen28','PercOpen32','PercOpen36','PercOpen40','PercOpen44','PercOpen48','PercOpen52','PercOpen56','PercOpen60','PercOpen64','PercOpen68','PercOpen72','PercOpen76','PercOpen80','PercOpen84','PercOpen88','PercOpen92','PercOpen96','OpenFull','Resd1','Resd2','Resd3','Resd4','Movg'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31], ...
   'DefaultValue', 'PosnUkwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

