Simulink.defineIntEnumType( 'AACAirClngSts', ...
   {'AACOff','AACOn','Sleep','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'AACOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirFragSts', ...
   {'OFF','ON','Error'}, ...
   [1 2 3], ...
   'DefaultValue', 'OFF', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirIonSts', ...
   {'AIUOff','AIUOn','Sleep','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'AIUOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'BookChargeSetResponse', ...
   {'Default','Success','Cancelled','Fail'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CabinOxgenSupply', ...
   {'Undefd','NCbnOxygn','InCbnOxygnDlvry_Mchnicl','NslInhltnNdDffn','DffsOxygn','InCbnOxygnDlvry_MchniclWthSnsr','NslInhltnNdDffnWthSnsr','DffsOxygnWthSnsrr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirClng', ...
   {'Undefd','NoAirClng','AirClng'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrpsnTypGly', ...
   {'Undefd','CombEng','HV','PHEV','BEV','MHEVForGEEA2','EREV'}, ...
   [0 1 2 3 4 128 129], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForRoofHatch', ...
   {'Undefd','NoRoofHatchf','OpenaPanoRoof','Hatch','ElecPanoRoof','PanoRoofFixed','PanoRoofPolestarStarLightFixed','DoubleSunCurtains','SunrfGlassClrAdj','SunrfGlassClrAdjWithZoning','SunrfGlassClrAdjWithPowSunrfVisor','MetalroofNoSunroofOrPanoCanopy','DoubleSunshadeNoSunroof','SftRf'}, ...
   [0 1 2 3 4 5 6 128 129 130 131 132 133 134], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CdsRunngMod', ...
   {'Standby','ActiveMode'}, ...
   [0 1], ...
   'DefaultValue', 'Standby', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ChagSts', ...
   {'Init','Changing','Changesucceeded','Changefailed'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Init', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'Co2Lvl', ...
   {'Lvl0Slight','Lvl1Low','Lvl2Middle','Lvl3High'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Lvl0Slight', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of Co2Lvl.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DoorSts2', ...
   {'Ukwn','Opend','Clsd'}, ...
   [0 1 2], ...
   'DefaultValue', 'Ukwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DrvrPfmncWarnReq', ...
   {'Unavailable','Unknown','NoWarning','Distractive','Warninglevel1','Warninglevel2_Navigation','Warninglevel2'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'Unavailable', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Err1', ...
   {'NoErr','Err'}, ...
   [0 1], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiFragraLvlReq', ...
   {'LvlOff','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'LvlOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'HmiFragraModReq', ...
   {'Single','Mix','Scene','Reserve'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Single', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvActvnSts', ...
   {'Open','Clsd','KeepSt','OpenAndReqActvDcha'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Open', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacTIfQf', ...
   {'SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1], ...
   'DefaultValue', 'SnsrDataNotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'InitSts', ...
   {'Noinitialization','Initializing','InitializationOK','Initializationfailed'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Noinitialization', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'NoReqOnOff', ...
   {'Norequest','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norequest', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NoYes1', ...
   {'No','Yes'}, ...
   [0 1], ...
   'DefaultValue', 'No', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of NoYes1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOffNoReq', ...
   {'NoReq','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenConcSnsrElecErr', ...
   {'NoErr','ShortToGrondOrOpenCircuit','ShortToBatt','Rsvd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyAvlSts', ...
   {'Off','Diffuse','NasalCannula','Error','None','PwrLo','BattleLo','TmrOvr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyPopUpReq', ...
   {'NoReq','DoorNotCls','WinNotCls','DoorAndWinNotCls','OpenFaild','ActrFlt','LvPwrLo','HvPwrLo','RemStsCarryOn','AutOxygenSplyActv','HvSocLow','Rsvd1','Rsvd2','Rsvd3','Rsvd4','Rsvd5'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyReq', ...
   {'NoReq','Off','Diffuse','NasalCannula'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyVoiceFb', ...
   {'Idle','OpenSucccess','ClsSucess','OpenFaild_LvPwrFlt','OpenFaild_HvPwrFlt','OpenFaild_OGMFlt','ClsFaild','Rsvd'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygengenrErrInfo', ...
   {'Normal','HumidifierErr','SolnVlvErr','DryerErr','FilErr','RadrErr','AirCmprErr','Rsvd'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PmSnsrErrSts', ...
   {'NoError','ShortToGroundOrOpenCircuit','ShortToBatt','Resvd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoError', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PmSnsrSts', ...
   {'Initial','Collecting','Complete','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Initial', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qf1', ...
   {'DevOfDataUndefd','DataTmpUndefdAndEvlnInProgs','DevOfDataNotWithinRngAllwd','DataCalcdWithDevDefd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'DevOfDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'RatUse', ...
   {'NoRequest','Low','Mid','High'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoRequest', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ReqFragLvlTelm', ...
   {'ReqFragLvl_OFF','ReqFragLvl_Level1','ReqFragLvl_Level2','ReqFragLvl_Level3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'ReqFragLvl_OFF', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'ReqSts1', ...
   {'NotReqd','Reqd'}, ...
   [0 1], ...
   'DefaultValue', 'NotReqd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TelmAirFragChReq', ...
   {'NoReq','Ch1','Ch2','Ch3','Ch4','Ch5'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TempErr', ...
   {'Normal','OverTemp','UnderTemp','Invalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UnknowLvl', ...
   {'Unknow','Lvl1','Lvl2','Lvl3','Lvl4','Rsvd1','Rsvd2','Rsvd3'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Unknow', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Warn2', ...
   {'NoWarn','Warn'}, ...
   [0 1], ...
   'DefaultValue', 'NoWarn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WinAndRoofAndCurtPosnTyp', ...
   {'PosnUkwn','ClsFull','PercOpen4','PercOpen8','PercOpen12','PercOpen16','PercOpen20','PercOpen24','PercOpen28','PercOpen32','PercOpen36','PercOpen40','PercOpen44','PercOpen48','PercOpen52','PercOpen56','PercOpen60','PercOpen64','PercOpen68','PercOpen72','PercOpen76','PercOpen80','PercOpen84','PercOpen88','PercOpen92','PercOpen96','OpenFull','Resd1','Resd2','Resd3','Resd4','Movg'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31], ...
   'DefaultValue', 'PosnUkwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

