Simulink.defineIntEnumType( 'BatBtrMStsEnum', ...
   {'BtrABCSts_C','BtrABCSts_B','BtrABCSts_A'}, ...
   [0 1 2], ...
   'DefaultValue', 'BtrABCSts_C', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'BatLoadBtrMStsEnum', ...
   {'BtrLoadModeSts_C','BtrLoadModeSts_B','BtrLoadModeSts_A'}, ...
   [0 1 2], ...
   'DefaultValue', 'BtrLoadModeSts_C', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'DTCState', ...
   {'DTC_OK','DTC_NOT_OK','DTC_NOT_RUN'}, ...
   [0 1 3], ...
   'DefaultValue', 'DTC_OK', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

