Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'DTCState', ...
   {'DTC_OK','DTC_NOT_OK','DTC_NOT_RUN'}, ...
   [0 1 3], ...
   'DefaultValue', 'DTC_OK', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'HvacFanDiagFlag', ...
   {'ErrorADConvertor','ErrortemperatureSensor','Errorbridgedriverovercurrent','Errorbridgedriverovertemperature'}, ...
   [1 2 4 8], ...
   'DefaultValue', 'ErrorADConvertor', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'HvacFanDir', ...
   {'Unused','CW','CCW','Invalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Unused', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSeln', ...
   {'BlowerHalf','BlowerThreeQuarters','Invalid','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'BlowerHalf', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NetworkChlType', ...
   {'NetworkHandle_CAN','NetworkHandle_LIN1','NetworkHandle_LIN2','NetworkHandle_LIN3','NetworkHandle_LIN4'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NetworkHandle_CAN', ...
   'StorageType', 'uint16', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SysServCarID', ...
   {'SysServ_CarConfig_HX11_2','SysServ_CarConfig_HX11_1','SysServ_CarConfig_HC11_2','SysServ_CarConfig_HC11_1','SysServ_CarConfig_LAMBDA','SysServ_CarConfig_L946'}, ...
   [0 1 2 3 4 7], ...
   'DefaultValue', 'SysServ_CarConfig_HX11_2', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

