Simulink.defineIntEnumType( 'ActCfrGroup', ...
   {'Notused','FirstActuatorGroup','SecondActuatorGroup','reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Notused', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ActCfrMod', ...
   {'Normal','Service','Stop','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ActCfrPrgDir', ...
   {'CW_CCW','CCW_CW'}, ...
   [0 1], ...
   'DefaultValue', 'CW_CCW', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ActCfrPrgSafty', ...
   {'LowEndstop','HighEndstop'}, ...
   [0 1], ...
   'DefaultValue', 'LowEndstop', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ActRfrErr', ...
   {'NoError','OverOrUnderVoltage','ReceptionError','OverTemperature','PermanentElectricalDefect'}, ...
   [0 1 2 4 8], ...
   'DefaultValue', 'NoError', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ActRfrMod', ...
   {'normal','service','stop','degrade'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ActvInActv', ...
   {'Active','Inactive'}, ...
   [0 1], ...
   'DefaultValue', 'Active', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'BatBtrMStsEnum', ...
   {'BtrABCSts_C','BtrABCSts_B','BtrABCSts_A'}, ...
   [0 1 2], ...
   'DefaultValue', 'BtrABCSts_C', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'BatLoadBtrMStsEnum', ...
   {'BtrLoadModeSts_C','BtrLoadModeSts_B','BtrLoadModeSts_A'}, ...
   [0 1 2], ...
   'DefaultValue', 'BtrLoadModeSts_C', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ComChlType', ...
   {'ComChl_Can','ComChl_Lin1','ComChl_Lin2','ComChl_Lin3','ComChl_Lin4'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'ComChl_Can', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'DioChannelType', ...
   {'DioChannel_AQS_INPUT','DioChannel_VGA_IN_CTR','DioChannel_VLCL_INPUT','DioChannel_FrontDefrostSwitchLevl','DioChannel_ClimateONOFFSwitchLevl','DioChannel_AutoClimateSwitchLevl','DioChannel_BTS5180_DSEL','DioChannel_INCAR_MTR_EN','DioChannel_VN7020_Fault','DioChannel_Max','DioChannel_V_OUT_EN','DioChannel_LIN4_SLP','DioChannel_VGA_EN','DioChannel_RETXV_LS_EN','DioChannel_RETXV_LS_AD_EN','DioChannel_RPTC_LS_AD_EN','DioChannel_LIN3_TX','DioChannel_LIN3_RX','DioChannel_VBAT_AD_EN','DioChannel_LIN3_SLP','DioChannel_FPTC_AD_EN','DioChannel_SLEEP_VDD_EN','DioChannel_VLCL_PWM_INPUT','DioChannel_TLE94106_EN','DioChannel_LIN4_RX','DioChannel_LIN4_TX','DioChannel_VN7020_INPUT','DioChannel_VN7020_SEn','DioChannel_VN7020_SEL0','DioChannel_RPTC_LS_EN','DioChannel_AQS_POWER_EN','DioChannel_VLCL_AD_EN','DioChannel_AQS_LEVEL','DioChannel_TLE94110_EN','DioChannel_BTS5180_DIG_EN','DioChannel_VN7020_SEL1','DioChannel_FDI_POWER_EN','DioChannel_COI_POWER_EN','DioChannel_ACI_POWER_EN','DioChannel_TCSSolenoidValve_HS_EN','DioChannel_TCSRefrigeratorStopVlv_HS_EN','DioChannel_TCSNegativeIonModuleSupply_HS_EN','DioChannel_HeatingSupply_HS_EN','DioChannel_TCSInternalCirculationFanSupply_EN','DioChannel_TCSInternalCirculationFanFaultDetection'}, ...
   [0 1 2 3 4 5 27 28 29 30 35 37 40 42 43 45 54 55 59 60 70 75 91 97 102 103 109 110 113 120 131 135 136 137 140 142 143 144 145 146 147 148 149 150 151], ...
   'DefaultValue', 'DioChannel_AQS_INPUT', ...
   'StorageType', 'uint16', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HFAChlType', ...
   {'HFAChl1_MOTOR0','HFAChl1_MOTOR1','HFAChl1_MOTOR2','HFAChl1_MOTOR3','HFAChl1_MOTOR4','HFAChl1_MOTOR5','HFAChl1_MOTOR6','HFAChl1_MOTOR7','HFAChl1_MOTOR8','HFAChl1_MOTOR9','HFAChl1_MOTOR10','HFAChl1_MOTOR11','HFAChl1_MOTOR12','HFAChl1_MOTOR13','HFAChl1_MOTOR14','HFAChl1_MOTOR15','HFAChl1_MOTOR16','HFAChl1_MOTOR17','HFAChl1_MOTOR18','HFAChl1_MOTOR19','HFAChl1_MOTORMAX'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20], ...
   'DefaultValue', 'HFAChl1_MOTOR0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'LinFrameType', ...
   {'LinFrame_CcmCcm_Lin3Fr03','LinFrame_CcmCcm_Lin4Fr09','LinFrame_lin3DiagResponse','LinFrame_lin4DiagResponse'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'LinFrame_CcmCcm_Lin3Fr03', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'MtrRoutStaEnum', ...
   {'MOTOR_ROUTINE_COMPLETE','MOTOR_ROUTINE_ABORTED','MOTOR_ROUTINE_ACTIVE'}, ...
   [0 1 2], ...
   'DefaultValue', 'MOTOR_ROUTINE_COMPLETE', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'NetworkChlType', ...
   {'NetworkHandle_CAN','NetworkHandle_LIN1','NetworkHandle_LIN2','NetworkHandle_LIN3','NetworkHandle_LIN4'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NetworkHandle_CAN', ...
   'StorageType', 'uint16', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'NvMBlockId', ...
   {'DidF1AB','DidE103','DidF190','DidD005','DidD09A','CarCfgData','PowerModeCnt','DcMtrCalData','HfaMtrCalData','VgaMtrCalData','CarCfgBulkData','MemMgrForClimaNvArray','RecordSignal','RefData','Max'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'DidF1AB', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff2', ...
   {'On','Off'}, ...
   [0 1], ...
   'DefaultValue', 'On', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PowerChlType', ...
   {'DCMtr','HFA','VGA'}, ...
   [0 1 2], ...
   'DefaultValue', 'DCMtr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ReqSts1', ...
   {'NotReqd','Reqd'}, ...
   [0 1], ...
   'DefaultValue', 'NotReqd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SbcWakeupSta', ...
   {'EcuM_RESET_Other','EcuM_RESET_PowerOn','EcuM_RESET_WaekUp','EcuM_RESET_SoftWare','EcuM_RESET_LowOrHighPower','EcuM_RESET_SWPassiveTrg','EcuM_RESET_SWCANService','EcuM_RESET_SWEcuDogSlp','EcuM_RESET_SWModleConfig','EcuM_RESET_SWFblFinish'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'EcuM_RESET_Other', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SetSpdMode', ...
   {'Speedmode0','Speedmode1','Speedmode2','Speedmode3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Speedmode0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SysServCarID', ...
   {'SysServ_CarConfig_HX11_2','SysServ_CarConfig_HX11_1','SysServ_CarConfig_HC11_2','SysServ_CarConfig_HC11_1','SysServ_CarConfig_LAMBDA','SysServ_CarConfig_L946'}, ...
   [0 1 2 3 4 7], ...
   'DefaultValue', 'SysServ_CarConfig_HX11_2', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01BlckInd', ...
   {'Disabled','Enabled','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Disabled', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01BlckSts', ...
   {'NoBlock','Block','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoBlock', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01DrvDir', ...
   {'Downward','Upward','Initialization','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Downward', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01ElecErr', ...
   {'Normal','ElecErr','PrmntElecErr','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01OvrTempErr', ...
   {'Normal','OvrTempErr','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01ResetSts', ...
   {'NoReset','Reset','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReset', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01SpclFct', ...
   {'None','SpecialFunction1active','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01SpdSts', ...
   {'Stop','Speedlevel1','Speedlevel2','Speedlevel3','Speedlevel4','Autospeed','Reserved0','Reserved1','Reserved2','Reserved3','Reserved4','Reserved5','Reserved6','Reserved7','Reserved8','Signalinvalid'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Stop', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01UrgcExist', ...
   {'False','True','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'False', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01VoltErr', ...
   {'Normal','UnderVolt','OvrVolt','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnMotBlockCmd', ...
   {'Blockdelectiondisable','Blockdelectionenable','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Blockdelectiondisable', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnMotDir', ...
   {'CW','CCW','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'CW', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnMotMode', ...
   {'Normal','Stop','Reserved_orMaintainence','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnMotPsonAvl', ...
   {'Targetpositionvalid','Startpositionvalid','Bothpositionsinvalid','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Targetpositionvalid', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnMotSaveData', ...
   {'Notsavedata','Savedata','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Notsavedata', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnMotSpdSet', ...
   {'Reserved0','Speedlevel1','Speedlevel2','Speedlevel3','Speedlevel4','Autospeed','Reserved1','Reserved2','Reserved3','Reserved4','Reserved5','Reserved6','Reserved7','Reserved8','Reserved9','Signalinvalid'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Reserved0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnMotUrgcPson', ...
   {'Bottom','Top','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Bottom', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnMotUrgcUnlck', ...
   {'Off','On','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'YesNo2', ...
   {'No','Yes'}, ...
   [0 1], ...
   'DefaultValue', 'No', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

