Simulink.defineIntEnumType( 'BatBtrMStsEnum', ...
   {'BtrABCSts_C','BtrABCSts_B','BtrABCSts_A'}, ...
   [0 1 2], ...
   'DefaultValue', 'BtrABCSts_C', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'BatLoadBtrMStsEnum', ...
   {'BtrLoadModeSts_C','BtrLoadModeSts_B','BtrLoadModeSts_A'}, ...
   [0 1 2], ...
   'DefaultValue', 'BtrLoadModeSts_C', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DTCState', ...
   {'DTC_OK','DTC_NOT_OK','DTC_NOT_RUN'}, ...
   [0 1 3], ...
   'DefaultValue', 'DTC_OK', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'DioChannelType', ...
   {'DioChannel_AQS_INPUT','DioChannel_VGA_IN_CTR','DioChannel_VLCL_INPUT','DioChannel_FrontDefrostSwitchLevl','DioChannel_ClimateONOFFSwitchLevl','DioChannel_AutoClimateSwitchLevl','DioChannel_BTS5180_DSEL','DioChannel_INCAR_MTR_EN','DioChannel_VN7020_Fault','DioChannel_Max','DioChannel_V_OUT_EN','DioChannel_LIN4_SLP','DioChannel_VGA_EN','DioChannel_RETXV_LS_EN','DioChannel_RETXV_LS_AD_EN','DioChannel_RPTC_LS_AD_EN','DioChannel_LIN3_TX','DioChannel_LIN3_RX','DioChannel_VBAT_AD_EN','DioChannel_LIN3_SLP','DioChannel_FPTC_AD_EN','DioChannel_SLEEP_VDD_EN','DioChannel_VLCL_PWM_INPUT','DioChannel_TLE94106_EN','DioChannel_LIN4_RX','DioChannel_LIN4_TX','DioChannel_VN7020_INPUT','DioChannel_VN7020_SEn','DioChannel_VN7020_SEL0','DioChannel_RPTC_LS_EN','DioChannel_AQS_POWER_EN','DioChannel_VLCL_AD_EN','DioChannel_AQS_LEVEL','DioChannel_TLE94110_EN','DioChannel_BTS5180_DIG_EN','DioChannel_VN7020_SEL1','DioChannel_FDI_POWER_EN','DioChannel_COI_POWER_EN','DioChannel_ACI_POWER_EN','DioChannel_TCSSolenoidValve_HS_EN','DioChannel_TCSRefrigeratorStopVlv_HS_EN','DioChannel_TCSNegativeIonModuleSupply_HS_EN','DioChannel_HeatingSupply_HS_EN','DioChannel_TCSInternalCirculationFanSupply_EN','DioChannel_TCSInternalCirculationFanFaultDetection'}, ...
   [0 1 2 3 4 5 27 28 29 30 35 37 40 42 43 45 54 55 59 60 70 75 91 97 102 103 109 110 113 120 131 135 136 137 140 142 143 144 145 146 147 148 149 150 151], ...
   'DefaultValue', 'DioChannel_AQS_INPUT', ...
   'StorageType', 'uint16', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'EvaprVlvSts', ...
   {'VlvReqdToClsd','VlvReqdToOpen','ElecErrByCircOpen','ElecErrShoToGnd','ElecErrShoToPwrSply','Resd'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'VlvReqdToClsd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'IcuChannelType', ...
   {'IcuChannel_AQS_INPUT','IcuChannel_CAN_RX','IcuChannel_VLCL_INPUT','IcuChannel_HALL_INPUT','IcuChannel_MAX','IcuChannel_HALL_INPUT2'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'IcuChannel_AQS_INPUT', ...
   'StorageType', 'uint16', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'NoYes1', ...
   {'No','Yes'}, ...
   [0 1], ...
   'DefaultValue', 'No', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of NoYes1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NvMBlockId', ...
   {'DidF1AB','DidE103','DidF190','DidD005','DidD09A','CarCfgData','PowerModeCnt','DcMtrCalData','HfaMtrCalData','VgaMtrCalData','CarCfgBulkData','MemMgrForClimaNvArray','RecordSignal','RefData','Max'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'DidF1AB', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PwmChannelType', ...
   {'PwmChannel_FPTC_PWM','PwmChannel_FAN_PWM','PwmChannel_VLCL_PWM','PwmChannel_S_PWM','PwmChannel_S_MOS','PwmChannel_TCSWarmColoredLight_PWM','PwmChannel_TCSColdColoredLight_PWM','PwmChannel_TCSInternalCirculationFan_PWM','PwmChannel_TCSHeatDissipationFan_PWM','PwmChannel_TCSRefrigerationSheetPostive_PWM','PwmChannel_TCSRefrigerationSheetNegtive_PWM','PwmChannel_MAX'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11], ...
   'DefaultValue', 'PwmChannel_FPTC_PWM', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SysServCarID', ...
   {'SysServ_CarConfig_HX11_2','SysServ_CarConfig_HX11_1','SysServ_CarConfig_HC11_2','SysServ_CarConfig_HC11_1','SysServ_CarConfig_LAMBDA','SysServ_CarConfig_L946'}, ...
   [0 1 2 3 4 7], ...
   'DefaultValue', 'SysServ_CarConfig_HX11_2', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

