Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForAirClng', ...
   {'Undefd','NoAirClng','AirClng'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirFrag', ...
   {'Undefd','WithoutAFU','WithAFU'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirMtrlSnsrGly', ...
   {'Undefd','WithoutInOutPM25','WithInPM25','WithInOutPM25','WithInPM25US'}, ...
   [0 1 2 3 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirQlyGly', ...
   {'Undefd','NoAQS','AQS','WithoutCO2WithoutAQS','WithCO2WithoutAQS','WithoutCO2WithAQS','WithCO2WithAQS','WithoutCO2WithAQS3GAS','WithCO2WithAQS3GAS'}, ...
   [0 1 2 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAmntOfSeatTyp3', ...
   {'CarCfgForAmntOfSeatTyp3_Undefd','CarCfgForAmntOfSeatTyp3_NotValid','CarCfgForAmntOfSeatTyp3_5seat','CarCfgForAmntOfSeatTyp3_7seat','CarCfgForAmntOfSeatTyp3_4seat','CarCfgForAmntOfSeatTyp3_3seat','CarCfgForAmntOfSeatTyp3_4seat_2_519G','CarCfgForAmntOfSeatTyp3_1seat','CarCfgForAmntOfSeatTyp3_2seat','CarCfgForAmntOfSeatTyp3_6seat','CarCfgForAmntOfSeatTyp3_9seat','CarCfgForAmntOfSeatTyp3_8seat'}, ...
   [0 1 2 3 4 5 6 7 8 9 128 129], ...
   'DefaultValue', 'CarCfgForAmntOfSeatTyp3_Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForAuxWtrPmp', ...
   {'Undefd','WoWtrPmp','WithWtrPmp'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForBypVlvInHvac2', ...
   {'Undefd','NoBypVlv','BypVlv','BypVlvExt'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForClsVlvInHvac', ...
   {'Undefd','WoClsVlv','WithClsVlv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForCmptmtClng', ...
   {'Undefd','NoCmptmtClng','CmptmtClng'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForElecVentAdjmt', ...
   {'Undefd','WithoutAdjmt','WithAdjmtFrnt','WithAdjmtFrntRear','WithAdjmtFrntSecThird'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForExtVentnClimaCtrl', ...
   {'Undefd','WoExtVentnClimaCtrl','WithExtVentnClimaCtrl'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForFlcTyp', ...
   {'Undefd','WithoutFLC','FLCADAS','NoValue','NoValue1','FLCTrifocal','FLCBinocularCam'}, ...
   [0 1 2 3 4 5 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForFoldCSD', ...
   {'Undefd','WithoutCSD','WithFoldedCSD','WithSlidingCSD','WithFlipCSD','WithFlipScalableCSD'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForFuTyp', ...
   {'Undefd','Petrol','Diesel','NoFuel','PETROL_METHANOL'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForGlassTyp', ...
   {'Undefd','WindGlassStd','WindGlassNoStd'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHeatPmpTyp', ...
   {'Undefd','WithoutHeatPump','WithNonIntegratedHeatPump','WithIntegratedHeatPump'}, ...
   [0 1 2 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHeatrDurgDrvg', ...
   {'Undefined','NoAdditionalHeater','AdditionalHeater'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefined', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacFilTypGly', ...
   {'Undefd','Pollenfilter','Multifilter','Multifilter2','Multifilter3'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacFlrSnsrForT', ...
   {'Undefined','WoHvacFlrSnsrForT','WithHvacFlrSnsrForT'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefined', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacHeatrSnsrT', ...
   {'Undefined','NoHvacHeatrSnsrT','HvacHeatrSnsrT'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefined', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForInteriorViewCamera', ...
   {'Undefd','WithoutCamera','WithInterViewCamera','WithInterViewCameraOtherM'}, ...
   [0 1 2 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForLoVoltElecCfg', ...
   {'Undefd','WithoutStartStop','StartStopInSPA','StartStopInCMA','EnhancedRegenSPA','Lynk48V','SPA48V','CMA48V','GAD48V','PHEVSPA','PHEVCMAHEP7','PHEVSPA7DCT','BEV','PHEVSPAPS14','PHEVDRIVEME20'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForNavSysandIntnmap', ...
   {'Undefd','WithoutNavigationWithoutMap','WithoutNavigationWithMap','WithNavigationWithoutMap','WithNavigationWithMap'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForNrOfDoor2', ...
   {'Undefd','Door5','Door4','Door2','Door3'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPipeInFuTank', ...
   {'Undefd','WoPipeInFuTank','WithPipeInFuTank'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPowerSeats', ...
   {'Undefd','NoMemory','DrvrMemoryPassMechanical','DrvrMemoryPassWoMemory','DrvrAndPassMemory','DrvrWoMemoryPassMechanical','DrvrAndPassWoMemory','DrvrAndPassPwrSeatWithSlutn','PassMemoryDrvrWoMemory'}, ...
   [0 1 2 3 4 80 81 82 83], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPreClng', ...
   {'Undefd','WoPreClng','PreClng1China','PreClng1Global','PreClng2China','PreClng2Globa','PreClng3China','PreClng3Global','PreClng4China','PreClng4Global'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrkgCDSNotAvl', ...
   {'PrkgCDSAvl','PrkgCDSNotAvl'}, ...
   [0 1], ...
   'DefaultValue', 'PrkgCDSAvl', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrkgClima', ...
   {'Undefd','NoPrkgClima','PrkgClimaAftRun','PrkgClimaHeatg','PrkgClimaFull','CmbSchdDirPrkgClima'}, ...
   [0 1 2 3 4 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrpsnTypGly', ...
   {'Undefd','CombEng','HV','PHEV','BEV','MHEVForGEEA2','EREV'}, ...
   [0 1 2 3 4 128 129], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForRemEngStrtPreCdn', ...
   {'Undefd','ERSByAppByKeyRunningLight','WithoutRemStrt','WithRemStrt','ERSByAppRunningLight','ERSByKey','ERSByKeyRunningLight','ERSByAppByKey'}, ...
   [0 7 1 2 3 4 5 6], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForRoofHatch', ...
   {'Undefd','NoRoofHatchf','OpenaPanoRoof','Hatch','ElecPanoRoof','PanoRoofFixed','PanoRoofPolestarStarLightFixed','DoubleSunCurtains','SunrfGlassClrAdj','SunrfGlassClrAdjWithZoning','SunrfGlassClrAdjWithPowSunrfVisor','MetalroofNoSunroofOrPanoCanopy','DoubleSunshadeNoSunroof','SftRf'}, ...
   [0 1 2 3 4 5 6 128 129 130 131 132 133 134], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgCal1', ...
   {'NoVal','Cal1','Cal2','Cal3','Cal4','Cal5','Cal6','Cal7','Cal8','Cal9','Cal10'}, ...
   [0 1 2 3 4 5 6 7 8 9 10], ...
   'DefaultValue', 'NoVal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgForRowFirst', ...
   {'Undefd','NoSeatHeatg','SeatHeatg','DriverOnly','SeatHeatFrontPass4z','SeatHeatFrontDrvr4z','SeatHeatFrontDrvrPass4z','SeatHeatDrvrOnly4z','SeatHeatPassOnly4z','SeatHeatPassOnly'}, ...
   [0 1 2 128 129 130 131 132 133 135], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgForRowSec', ...
   {'Undefd','NoSeatHeatg','SeatHeatg','SeatHeatgOnlyRight'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatVentnForRowFirst1', ...
   {'Undefd','NoSeatVentn','SeatVentn','DrvrSeatVentn','PassSeatVentn','SeatVentnCushion','DrvrSeatVentnCushion','PassSeatVentnCushion','SeatVentnBackrest','DrvrSeatVentnBackrest','PassSeatVentnBackrest','SeatVentnCushionSMF2','SeatVentnBackrestSMF2','DrvrSeatVentnBackrestSMF2','PassSeatVentnBackrestSMF2','DrvrSeatVentnCushionSMF2','PassSeatVentnCushionSMF2','SeatVentnSMF2','DrvrSeatVentnSMF2','PassSeatVentnSMF2'}, ...
   [0 1 2 3 128 129 130 131 132 133 134 137 138 139 140 141 142 143 144 145], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatVentnForRowSecGly', ...
   {'Undefd','WithoutSecSeats','SecSeats','SecSeatsVentnCushion','SecSeatsRiVentnCushion','SecSeatsVentnBackrest'}, ...
   [0 1 2 128 129 131], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSecRowVentnCenter', ...
   {'Undefd','WoRoSecVentCen','WithRoSecVentCenInd','WoRoSecVentCenCmn','WithRoSecVentCenIndLong','WoRoSecVentCenCmnLong'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSecRowVentnSide', ...
   {'Undefd','WoSecRowVentn','WithSecRowVentn','WithFanSide'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSmallFlowCyc', ...
   {'Undefd','WoSmallFlowCyc','WithSmallFlowCyc'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSmkSnsr', ...
   {'UnDefd','NoSmkSnsr','SmkSnsr'}, ...
   [0 1 2], ...
   'DefaultValue', 'UnDefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSnsrForCmptmtT', ...
   {'Undefd','WoSnsr','WithMtrlSnsr','WithCarSnsr','WithIntgrtCarSns','WithIndepCarSns'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSnsrHumPrsnt', ...
   {'Undefd','WithoutSnsr','WithSnsr'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSteerWhlPosn', ...
   {'Undefd','LeSideDrv','RiSideDrv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSunSnsr', ...
   {'Undefd','WithoutSunSnsr','WithSunSnsrLIN3D','WithSunSnsrHardwired2D','WithSunSnsrLIN2D','WithSunSnsrHardwired2DWithFuntnSafety'}, ...
   [0 1 2 3 128 129], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForTelmNodTyp', ...
   {'Undefd','WoVCMandTCAM','WithVCM','WithTCAM'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForThermMngt', ...
   {'UnDefd','ThermMngtGen1','ThermMngtGen2'}, ...
   [0 1 2], ...
   'DefaultValue', 'UnDefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForVehTyp3', ...
   {'Undefd','L541','V542','V543','V526','V426','V541','V316','V320','V323','V431','V432','L431','V433','P514','V331','V317','CX11','CS11','CH11','CC11','CS12','DCY11','Reserved1','FX11','LAMBDA','HX11','HC11','HB11','ALPHA','GK11H','L946','P181','P177','E366','P389','EX11','KX11','DC1E','KW11','ES11','BC1E','EF1E','DX1E','CF1E','CM1E','DX11','G733','V216','BX1E','FS11','G636','CX21','L743','P417','E155','CS1E','EO11','V51DK','E335','CM2E','CX1E','E171','E371','HY11','HS11','EX1E','HRE1','XE08','G426','MC11','E245','E261','E23H','P145','V446K','SIGMA','P171','P179','P22H','FS21','P376','L955','SS21','E145','P162','KX21','P166','E281','KO11'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 128 129 130 131 132 133 134 135 138 139 140 141 142 143 144 145 146 147 148 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 224 225 226 227 228 229 230 231 233 234 235 236 239 241 242 243 244 245 246 247 248 249 250], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForWindHeatd', ...
   {'Undefd','NoWindHeatd','HeatdWind'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DcChlType', ...
   {'TLE91_HWCH0_REC','TLE91_HWCH1_TEMP_FL','TLE91_HWCH2_MODE','TLE91_HWCH3_TEMP_FR','TLE91_HWCH4_TEMP_DEFROST','TLE91_HWCH5_TEMP_S','TLE91_HWCH6_MODE_S','TLE91_HWCH_MAX_NUM'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'TLE91_HWCH0_REC', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'Err1', ...
   {'NoErr','Err'}, ...
   [0 1], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HFAChlType', ...
   {'HFAChl1_MOTOR0','HFAChl1_MOTOR1','HFAChl1_MOTOR2','HFAChl1_MOTOR3','HFAChl1_MOTOR4','HFAChl1_MOTOR5','HFAChl1_MOTOR6','HFAChl1_MOTOR7','HFAChl1_MOTOR8','HFAChl1_MOTOR9','HFAChl1_MOTOR10','HFAChl1_MOTOR11','HFAChl1_MOTOR12','HFAChl1_MOTOR13','HFAChl1_MOTOR14','HFAChl1_MOTOR15','HFAChl1_MOTOR16','HFAChl1_MOTOR17','HFAChl1_MOTOR18','HFAChl1_MOTOR19','HFAChl1_MOTORMAX'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20], ...
   'DefaultValue', 'HFAChl1_MOTOR0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'HeadRadar', ...
   {'UnDefd','WithoutRadar','WithOMC','WithTOF','WithOMCAndTOF'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'UnDefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacActrSts', ...
   {'Ok','Flt','CalRunng'}, ...
   [0 1 2], ...
   'DefaultValue', 'Ok', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LifeDetection', ...
   {'Undefd','WithoutDetection','SecondRowOnly','BothRowOnly','AlarmWithoutSound','AlarmWithSound','LifeDetectionWithUWB','WithCameraMiliterRadarAndCo2'}, ...
   [0 1 2 3 4 5 6 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'MtrRoutStaEnum', ...
   {'MOTOR_ROUTINE_COMPLETE','MOTOR_ROUTINE_ABORTED','MOTOR_ROUTINE_ACTIVE'}, ...
   [0 1 2], ...
   'DefaultValue', 'MOTOR_ROUTINE_COMPLETE', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'PwrMdAllMtrSlp', ...
   {'PwrMdAllMtr_AllowSleep','PwrMdAllMtr_NotAllowSleep'}, ...
   [0 1], ...
   'DefaultValue', 'PwrMdAllMtr_AllowSleep', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'StartDevice', ...
   {'Undefd','StrtWithTwoDir','StrtWithOneDir','StrtBtn','NoPhyDev'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SysServCarID', ...
   {'SysServ_CarConfig_HX11_2','SysServ_CarConfig_HX11_1','SysServ_CarConfig_HC11_2','SysServ_CarConfig_HC11_1','SysServ_CarConfig_LAMBDA','SysServ_CarConfig_L946'}, ...
   [0 1 2 3 4 7], ...
   'DefaultValue', 'SysServ_CarConfig_HX11_2', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VGAChlType', ...
   {'VGACH1_MOTOR0','VGAChl1_MOTOR1','VGAChl1_MOTOR2','VGAChl1_MOTOR3','VGAChl1_MOTOR4','VGAChl1_MOTOR5','VGAChl1_MOTOR6','VGAChl1_MOTOR7','VGAChl1_MOTOR8','VGAChl1_MOTOR9','VGAChl1_MOTOR10','VGAChl1_MOTOR11','VGAChl1_MOTOR12','VGAChl1_MOTOR13','VGAChl1_MOTOR14','VGAChl1_MOTOR15','VGAChl1_MOTOR16','VGAChl1_MOTOR17','VGAChl1_MOTOR18','VGAChl1_MOTOR19','VGAChl1_MOTORMAX'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20], ...
   'DefaultValue', 'VGACH1_MOTOR0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'VentnStsRsp', ...
   {'Stop','Running','Calibration'}, ...
   [0 1 2], ...
   'DefaultValue', 'Stop', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

