Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HFAChlType', ...
   {'HFAChl1_MOTOR0','HFAChl1_MOTOR1','HFAChl1_MOTOR2','HFAChl1_MOTOR3','HFAChl1_MOTOR4','HFAChl1_MOTOR5','HFAChl1_MOTOR6','HFAChl1_MOTOR7','HFAChl1_MOTOR8','HFAChl1_MOTOR9','HFAChl1_MOTOR10','HFAChl1_MOTOR11','HFAChl1_MOTOR12','HFAChl1_MOTOR13','HFAChl1_MOTOR14','HFAChl1_MOTOR15','HFAChl1_MOTOR16','HFAChl1_MOTOR17','HFAChl1_MOTOR18','HFAChl1_MOTOR19','HFAChl1_MOTORMAX'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20], ...
   'DefaultValue', 'HFAChl1_MOTOR0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'NvMBlockId', ...
   {'DidF1AB','DidE103','DidF190','DidD005','DidD09A','CarCfgData','PowerModeCnt','DcMtrCalData','HfaMtrCalData','VgaMtrCalData','CarCfgBulkData','MemMgrForClimaNvArray','RecordSignal','RefData','Max'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'DidF1AB', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PowerChlType', ...
   {'DCMtr','HFA','VGA'}, ...
   [0 1 2], ...
   'DefaultValue', 'DCMtr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PwrMdAllMtrSlp', ...
   {'PwrMdAllMtr_AllowSleep','PwrMdAllMtr_NotAllowSleep'}, ...
   [0 1], ...
   'DefaultValue', 'PwrMdAllMtr_AllowSleep', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SbcWakeupSta', ...
   {'EcuM_RESET_Other','EcuM_RESET_PowerOn','EcuM_RESET_WaekUp','EcuM_RESET_SoftWare','EcuM_RESET_LowOrHighPower','EcuM_RESET_SWPassiveTrg','EcuM_RESET_SWCANService','EcuM_RESET_SWEcuDogSlp','EcuM_RESET_SWModleConfig','EcuM_RESET_SWFblFinish'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'EcuM_RESET_Other', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SysServCarID', ...
   {'SysServ_CarConfig_HX11_2','SysServ_CarConfig_HX11_1','SysServ_CarConfig_HC11_2','SysServ_CarConfig_HC11_1','SysServ_CarConfig_LAMBDA','SysServ_CarConfig_L946'}, ...
   [0 1 2 3 4 7], ...
   'DefaultValue', 'SysServ_CarConfig_HX11_2', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VGAChlType', ...
   {'VGACH1_MOTOR0','VGAChl1_MOTOR1','VGAChl1_MOTOR2','VGAChl1_MOTOR3','VGAChl1_MOTOR4','VGAChl1_MOTOR5','VGAChl1_MOTOR6','VGAChl1_MOTOR7','VGAChl1_MOTOR8','VGAChl1_MOTOR9','VGAChl1_MOTOR10','VGAChl1_MOTOR11','VGAChl1_MOTOR12','VGAChl1_MOTOR13','VGAChl1_MOTOR14','VGAChl1_MOTOR15','VGAChl1_MOTOR16','VGAChl1_MOTOR17','VGAChl1_MOTOR18','VGAChl1_MOTOR19','VGAChl1_MOTORMAX'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20], ...
   'DefaultValue', 'VGACH1_MOTOR0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

