Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DioChannelType', ...
   {'DioChannel_AQS_INPUT','DioChannel_VGA_IN_CTR','DioChannel_VLCL_INPUT','DioChannel_FrontDefrostSwitchLevl','DioChannel_ClimateONOFFSwitchLevl','DioChannel_AutoClimateSwitchLevl','DioChannel_BTS5180_DSEL','DioChannel_INCAR_MTR_EN','DioChannel_VN7020_Fault','DioChannel_Max','DioChannel_V_OUT_EN','DioChannel_LIN4_SLP','DioChannel_VGA_EN','DioChannel_RETXV_LS_EN','DioChannel_RETXV_LS_AD_EN','DioChannel_RPTC_LS_AD_EN','DioChannel_LIN3_TX','DioChannel_LIN3_RX','DioChannel_VBAT_AD_EN','DioChannel_LIN3_SLP','DioChannel_FPTC_AD_EN','DioChannel_SLEEP_VDD_EN','DioChannel_VLCL_PWM_INPUT','DioChannel_TLE94106_EN','DioChannel_LIN4_RX','DioChannel_LIN4_TX','DioChannel_VN7020_INPUT','DioChannel_VN7020_SEn','DioChannel_VN7020_SEL0','DioChannel_RPTC_LS_EN','DioChannel_AQS_POWER_EN','DioChannel_VLCL_AD_EN','DioChannel_AQS_LEVEL','DioChannel_TLE94110_EN','DioChannel_BTS5180_DIG_EN','DioChannel_VN7020_SEL1','DioChannel_FDI_POWER_EN','DioChannel_COI_POWER_EN','DioChannel_ACI_POWER_EN','DioChannel_TCSSolenoidValve_HS_EN','DioChannel_TCSRefrigeratorStopVlv_HS_EN','DioChannel_TCSNegativeIonModuleSupply_HS_EN','DioChannel_HeatingSupply_HS_EN','DioChannel_TCSInternalCirculationFanSupply_EN','DioChannel_TCSInternalCirculationFanFaultDetection'}, ...
   [0 1 2 3 4 5 27 28 29 30 35 37 40 42 43 45 54 55 59 60 70 75 91 97 102 103 109 110 113 120 131 135 136 137 140 142 143 144 145 146 147 148 149 150 151], ...
   'DefaultValue', 'DioChannel_AQS_INPUT', ...
   'StorageType', 'uint16', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HFAChlType', ...
   {'HFAChl1_MOTOR0','HFAChl1_MOTOR1','HFAChl1_MOTOR2','HFAChl1_MOTOR3','HFAChl1_MOTOR4','HFAChl1_MOTOR5','HFAChl1_MOTOR6','HFAChl1_MOTOR7','HFAChl1_MOTOR8','HFAChl1_MOTOR9','HFAChl1_MOTOR10','HFAChl1_MOTOR11','HFAChl1_MOTOR12','HFAChl1_MOTOR13','HFAChl1_MOTOR14','HFAChl1_MOTOR15','HFAChl1_MOTOR16','HFAChl1_MOTOR17','HFAChl1_MOTOR18','HFAChl1_MOTOR19','HFAChl1_MOTORMAX'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20], ...
   'DefaultValue', 'HFAChl1_MOTOR0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'IcuChannelType', ...
   {'IcuChannel_AQS_INPUT','IcuChannel_CAN_RX','IcuChannel_VLCL_INPUT','IcuChannel_HALL_INPUT','IcuChannel_MAX','IcuChannel_HALL_INPUT2'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'IcuChannel_AQS_INPUT', ...
   'StorageType', 'uint16', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SbcWakeupSta', ...
   {'EcuM_RESET_Other','EcuM_RESET_PowerOn','EcuM_RESET_WaekUp','EcuM_RESET_SoftWare','EcuM_RESET_LowOrHighPower','EcuM_RESET_SWPassiveTrg','EcuM_RESET_SWCANService','EcuM_RESET_SWEcuDogSlp','EcuM_RESET_SWModleConfig','EcuM_RESET_SWFblFinish'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'EcuM_RESET_Other', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SysServCarID', ...
   {'SysServ_CarConfig_HX11_2','SysServ_CarConfig_HX11_1','SysServ_CarConfig_HC11_2','SysServ_CarConfig_HC11_1','SysServ_CarConfig_LAMBDA','SysServ_CarConfig_L946'}, ...
   [0 1 2 3 4 7], ...
   'DefaultValue', 'SysServ_CarConfig_HX11_2', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VGAChlType', ...
   {'VGACH1_MOTOR0','VGAChl1_MOTOR1','VGAChl1_MOTOR2','VGAChl1_MOTOR3','VGAChl1_MOTOR4','VGAChl1_MOTOR5','VGAChl1_MOTOR6','VGAChl1_MOTOR7','VGAChl1_MOTOR8','VGAChl1_MOTOR9','VGAChl1_MOTOR10','VGAChl1_MOTOR11','VGAChl1_MOTOR12','VGAChl1_MOTOR13','VGAChl1_MOTOR14','VGAChl1_MOTOR15','VGAChl1_MOTOR16','VGAChl1_MOTOR17','VGAChl1_MOTOR18','VGAChl1_MOTOR19','VGAChl1_MOTORMAX'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20], ...
   'DefaultValue', 'VGACH1_MOTOR0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

