Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CabinOxgenSupply', ...
   {'Undefd','NCbnOxygn','InCbnOxygnDlvry_Mchnicl','NslInhltnNdDffn','DffsOxygn','InCbnOxygnDlvry_MchniclWthSnsr','NslInhltnNdDffnWthSnsr','DffsOxygnWthSnsrr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirClng', ...
   {'Undefd','NoAirClng','AirClng'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirClnrAdv', ...
   {'Undefd','NoAirClnrAdv','AirClnrAdv','AirClnrAdvWaterION','WithAAC','WithAACandlonizer'}, ...
   [0 1 2 128 129 130], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirFrag', ...
   {'Undefd','WithoutAFU','WithAFU'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirMtrlSnsrGly', ...
   {'Undefd','WithoutInOutPM25','WithInPM25','WithInOutPM25','WithInPM25US'}, ...
   [0 1 2 3 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirQlyGly', ...
   {'Undefd','NoAQS','AQS','WithoutCO2WithoutAQS','WithCO2WithoutAQS','WithoutCO2WithAQS','WithCO2WithAQS','WithoutCO2WithAQS3GAS','WithCO2WithAQS3GAS'}, ...
   [0 1 2 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAmntOfSeatTyp3', ...
   {'CarCfgForAmntOfSeatTyp3_Undefd','CarCfgForAmntOfSeatTyp3_NotValid','CarCfgForAmntOfSeatTyp3_5seat','CarCfgForAmntOfSeatTyp3_7seat','CarCfgForAmntOfSeatTyp3_4seat','CarCfgForAmntOfSeatTyp3_3seat','CarCfgForAmntOfSeatTyp3_4seat_2_519G','CarCfgForAmntOfSeatTyp3_1seat','CarCfgForAmntOfSeatTyp3_2seat','CarCfgForAmntOfSeatTyp3_6seat','CarCfgForAmntOfSeatTyp3_9seat','CarCfgForAmntOfSeatTyp3_8seat'}, ...
   [0 1 2 3 4 5 6 7 8 9 128 129], ...
   'DefaultValue', 'CarCfgForAmntOfSeatTyp3_Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForAutDemst', ...
   {'UnDefd','WoAutDemst','WithAutDemst'}, ...
   [0 1 2], ...
   'DefaultValue', 'UnDefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAuxWtrPmp', ...
   {'Undefd','WoWtrPmp','WithWtrPmp'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForBypVlvInHvac2', ...
   {'Undefd','NoBypVlv','BypVlv','BypVlvExt'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForClsVlvInHvac', ...
   {'Undefd','WoClsVlv','WithClsVlv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForCmprAcTyp3', ...
   {'Undefd','CmprAcMeclA','CmprAcMeclB','CmprAcElec','CmprIVDc','CmprAcElecChill','CmprAcMeclA2','CmprAcMeclB2','CmprAcMeclC','CmprAcMeclD'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForCmptmtClng', ...
   {'Undefd','NoCmptmtClng','CmptmtClng'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForElecVentAdjmt', ...
   {'Undefd','WithoutAdjmt','WithAdjmtFrnt','WithAdjmtFrntRear','WithAdjmtFrntSecThird'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForExtVentnClimaCtrl', ...
   {'Undefd','WoExtVentnClimaCtrl','WithExtVentnClimaCtrl'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForFlcTyp', ...
   {'Undefd','WithoutFLC','FLCADAS','NoValue','NoValue1','FLCTrifocal','FLCBinocularCam'}, ...
   [0 1 2 3 4 5 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForFoldCSD', ...
   {'Undefd','WithoutCSD','WithFoldedCSD','WithSlidingCSD','WithFlipCSD','WithFlipScalableCSD'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForFuTyp', ...
   {'Undefd','Petrol','Diesel','NoFuel','PETROL_METHANOL'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForGlassTyp', ...
   {'Undefd','WindGlassStd','WindGlassNoStd'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHeatPmpTyp', ...
   {'Undefd','WithoutHeatPump','WithNonIntegratedHeatPump','WithIntegratedHeatPump'}, ...
   [0 1 2 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHeatrDurgDrvg', ...
   {'Undefined','NoAdditionalHeater','AdditionalHeater'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefined', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHeatrTypGly', ...
   {'Undefd','NoHeatr','FuHeatr','HvHeatr','PrkgHeatrElec','Hv12V','Hvah','HvahAndHvch'}, ...
   [0 1 2 3 4 128 129 130], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacFilTypGly', ...
   {'Undefd','Pollenfilter','Multifilter','Multifilter2','Multifilter3'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacFlrSnsrForT', ...
   {'Undefined','WoHvacFlrSnsrForT','WithHvacFlrSnsrForT'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefined', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacHeatrSnsrT', ...
   {'Undefined','NoHvacHeatrSnsrT','HvacHeatrSnsrT'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefined', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacRe', ...
   {'Undefd','NoHvacRe','HvacReWoPtc','HvacReWithPtc','HvacReWithHVAH','HvacReWthHVAHANDHVCHDblTZn','HvacReWthHVAHLinVBMR_RHFA','HvacReWthHVAHLinVBMR','HvacReWthHVAHLinRHFA','HvacReWthHVAHANDHVCHDblTMF'}, ...
   [0 1 2 3 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacTyp2', ...
   {'Undefd','HvacElectronic2','HvacElectronic4','HvacSimple1','HvacSimple2','HvacSimple3','HvacMan','HvacManWithRecircPtl','HvacSimple4','HvacElectronic1','ADU1Z','ADU2Z','ADU3Z','ADU4Z','HVAC4ZonesFullControl','HVAC5ZonesFullControl','HVAC4DOUBLE','HVAC333DOUBLE','HVAC331DOUBLE','Front3Zones_RearHvac','Front2Zones_RearHvac'}, ...
   [0 1 2 3 4 5 6 128 129 130 131 132 133 134 135 136 137 139 141 142 147], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForInteriorViewCamera', ...
   {'Undefd','WithoutCamera','WithInterViewCamera','WithInterViewCameraOtherM'}, ...
   [0 1 2 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForLoVoltElecCfg', ...
   {'Undefd','WithoutStartStop','StartStopInSPA','StartStopInCMA','EnhancedRegenSPA','Lynk48V','SPA48V','CMA48V','GAD48V','PHEVSPA','PHEVCMAHEP7','PHEVSPA7DCT','BEV','PHEVSPAPS14','PHEVDRIVEME20'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForNavSysandIntnmap', ...
   {'Undefd','WithoutNavigationWithoutMap','WithoutNavigationWithMap','WithNavigationWithoutMap','WithNavigationWithMap'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForNrOfDoor2', ...
   {'Undefd','Door5','Door4','Door2','Door3'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPipeInFuTank', ...
   {'Undefd','WoPipeInFuTank','WithPipeInFuTank'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPowerSeats', ...
   {'Undefd','NoMemory','DrvrMemoryPassMechanical','DrvrMemoryPassWoMemory','DrvrAndPassMemory','DrvrWoMemoryPassMechanical','DrvrAndPassWoMemory','DrvrAndPassPwrSeatWithSlutn','PassMemoryDrvrWoMemory'}, ...
   [0 1 2 3 4 80 81 82 83], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPreClng', ...
   {'Undefd','WoPreClng','PreClng1China','PreClng1Global','PreClng2China','PreClng2Globa','PreClng3China','PreClng3Global','PreClng4China','PreClng4Global'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrkgCDSNotAvl', ...
   {'PrkgCDSAvl','PrkgCDSNotAvl'}, ...
   [0 1], ...
   'DefaultValue', 'PrkgCDSAvl', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrkgClima', ...
   {'Undefd','NoPrkgClima','PrkgClimaAftRun','PrkgClimaHeatg','PrkgClimaFull','CmbSchdDirPrkgClima'}, ...
   [0 1 2 3 4 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrpsnTypGly', ...
   {'Undefd','CombEng','HV','PHEV','BEV','MHEVForGEEA2','EREV'}, ...
   [0 1 2 3 4 128 129], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForRemEngStrtPreCdn', ...
   {'Undefd','ERSByAppByKeyRunningLight','WithoutRemStrt','WithRemStrt','ERSByAppRunningLight','ERSByKey','ERSByKeyRunningLight','ERSByAppByKey'}, ...
   [0 7 1 2 3 4 5 6], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForRoofHatch', ...
   {'Undefd','NoRoofHatchf','OpenaPanoRoof','Hatch','ElecPanoRoof','PanoRoofFixed','PanoRoofPolestarStarLightFixed','DoubleSunCurtains','SunrfGlassClrAdj','SunrfGlassClrAdjWithZoning','SunrfGlassClrAdjWithPowSunrfVisor','MetalroofNoSunroofOrPanoCanopy','DoubleSunshadeNoSunroof','SftRf'}, ...
   [0 1 2 3 4 5 6 128 129 130 131 132 133 134], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgCal1', ...
   {'NoVal','Cal1','Cal2','Cal3','Cal4','Cal5','Cal6','Cal7','Cal8','Cal9','Cal10'}, ...
   [0 1 2 3 4 5 6 7 8 9 10], ...
   'DefaultValue', 'NoVal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgForRowFirst', ...
   {'Undefd','NoSeatHeatg','SeatHeatg','DriverOnly','SeatHeatFrontPass4z','SeatHeatFrontDrvr4z','SeatHeatFrontDrvrPass4z','SeatHeatDrvrOnly4z','SeatHeatPassOnly4z','SeatHeatPassOnly'}, ...
   [0 1 2 128 129 130 131 132 133 135], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgForRowSec', ...
   {'Undefd','NoSeatHeatg','SeatHeatg','SeatHeatgOnlyRight'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgForRowSecGly', ...
   {'WithoutHeatgRearSeats','HeatgRearSeats'}, ...
   [1 2], ...
   'DefaultValue', 'WithoutHeatgRearSeats', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatVentnForRowFirst1', ...
   {'Undefd','NoSeatVentn','SeatVentn','DrvrSeatVentn','PassSeatVentn','SeatVentnCushion','DrvrSeatVentnCushion','PassSeatVentnCushion','SeatVentnBackrest','DrvrSeatVentnBackrest','PassSeatVentnBackrest','SeatVentnCushionSMF2','SeatVentnBackrestSMF2','DrvrSeatVentnBackrestSMF2','PassSeatVentnBackrestSMF2','DrvrSeatVentnCushionSMF2','PassSeatVentnCushionSMF2','SeatVentnSMF2','DrvrSeatVentnSMF2','PassSeatVentnSMF2'}, ...
   [0 1 2 3 128 129 130 131 132 133 134 137 138 139 140 141 142 143 144 145], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatVentnForRowSecGly', ...
   {'Undefd','WithoutSecSeats','SecSeats','SecSeatsVentnCushion','SecSeatsRiVentnCushion','SecSeatsVentnBackrest'}, ...
   [0 1 2 128 129 131], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSecRowVentnCenter', ...
   {'Undefd','WoRoSecVentCen','WithRoSecVentCenInd','WoRoSecVentCenCmn','WithRoSecVentCenIndLong','WoRoSecVentCenCmnLong'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSecRowVentnSide', ...
   {'Undefd','WoSecRowVentn','WithSecRowVentn','WithFanSide'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSmallFlowCyc', ...
   {'Undefd','WoSmallFlowCyc','WithSmallFlowCyc'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSmkSnsr', ...
   {'UnDefd','NoSmkSnsr','SmkSnsr'}, ...
   [0 1 2], ...
   'DefaultValue', 'UnDefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSnsrForCmptmtT', ...
   {'Undefd','WoSnsr','WithMtrlSnsr','WithCarSnsr','WithIntgrtCarSns','WithIndepCarSns'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSnsrHumPrsnt', ...
   {'Undefd','WithoutSnsr','WithSnsr'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSteerWhlHeatg', ...
   {'Undefd','NoSteerWhlHeatg','SteerWhlHeatg'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSteerWhlPosn', ...
   {'Undefd','LeSideDrv','RiSideDrv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForStrtStop', ...
   {'FullUnavailable','CoolingAndOtherAvailable','HeatingAndOtherAvailable','FullAvailable'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'FullUnavailable', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSunSnsr', ...
   {'Undefd','WithoutSunSnsr','WithSunSnsrLIN3D','WithSunSnsrHardwired2D','WithSunSnsrLIN2D','WithSunSnsrHardwired2DWithFuntnSafety'}, ...
   [0 1 2 3 128 129], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForTelmNodTyp', ...
   {'Undefd','WoVCMandTCAM','WithVCM','WithTCAM'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForThermMngt', ...
   {'UnDefd','ThermMngtGen1','ThermMngtGen2'}, ...
   [0 1 2], ...
   'DefaultValue', 'UnDefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForVehTyp3', ...
   {'Undefd','L541','V542','V543','V526','V426','V541','V316','V320','V323','V431','V432','L431','V433','P514','V331','V317','CX11','CS11','CH11','CC11','CS12','DCY11','Reserved1','FX11','LAMBDA','HX11','HC11','HB11','ALPHA','GK11H','L946','P181','P177','E366','P389','EX11','KX11','DC1E','KW11','ES11','BC1E','EF1E','DX1E','CF1E','CM1E','DX11','G733','V216','BX1E','FS11','G636','CX21','L743','P417','E155','CS1E','EO11','V51DK','E335','CM2E','CX1E','E171','E371','HY11','HS11','EX1E','HRE1','XE08','G426','MC11','E245','E261','E23H','P145','V446K','SIGMA','P171','P179','P22H','FS21','P376','L955','SS21','E145','P162','KX21','P166','E281','KO11'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 128 129 130 131 132 133 134 135 138 139 140 141 142 143 144 145 146 147 148 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 224 225 226 227 228 229 230 231 233 234 235 236 239 241 242 243 244 245 246 247 248 249 250], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForWindHeatd', ...
   {'Undefd','NoWindHeatd','HeatdWind'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCenCfgForVrntOfVehSysElec1', ...
   {'VehLrg1','VehSmall1'}, ...
   [0 1], ...
   'DefaultValue', 'VehLrg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrInd1', ...
   {'Cmn','Ind'}, ...
   [0 1], ...
   'DefaultValue', 'Cmn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrInd2', ...
   {'Cmn','Ind'}, ...
   [0 1], ...
   'DefaultValue', 'Cmn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrnt1', ...
   {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'FlapInd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrnt2', ...
   {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn','VentFlrCmnAdjmt','FlrVentCmnAdjmt','WithoutFlap'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'FlapInd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrntCen', ...
   {'NoFlap','FlapInd'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlap', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrRecircAndOsaCmnPrsnt1', ...
   {'Ind','Cmn','Nest'}, ...
   [0 1 2], ...
   'DefaultValue', 'Ind', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of ClimaCfgForActrRecircAndOsaCmnPrsnt1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForAmntOfSeat1', ...
   {'Seat5','Seat7','Seat4','Seat3','Seat1','Seat2','Seat6'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'Seat5', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForAmntOfSeatRow1', ...
   {'NrOfRow1','NrOfRow2','NrOfRow3'}, ...
   [0 1 2], ...
   'DefaultValue', 'NrOfRow1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForBRAND', ...
   {'Undefd','VCC','GEELY','LYNK','PROTON','LOTUS','LEVC','YUANCHENG','SMART','POLESTAR','ZEEKR','GEOMETRY','RENAULT','ALPINE'}, ...
   [0 1 2 3 4 5 6 7 8 9 16 17 19 24], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForCarTyp1', ...
   {'CarTyp0','CarTyp1','CarTyp2'}, ...
   [0 1 2], ...
   'DefaultValue', 'CarTyp0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForCmptmtSnsr1', ...
   {'WoCmptmtSnsr','AirTWithFan','IntrMtrlT'}, ...
   [0 1 2], ...
   'DefaultValue', 'WoCmptmtSnsr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForCoolgPreCdn1', ...
   {'NotAvl','PreVent','PreAirCdn'}, ...
   [0 1 2], ...
   'DefaultValue', 'NotAvl', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForEcuCooltVlvOutp1', ...
   {'Limd','Full'}, ...
   [0 1], ...
   'DefaultValue', 'Limd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForFuHeatrFuLine1', ...
   {'FuLineInTank','FuLineInSwirlPool'}, ...
   [0 1], ...
   'DefaultValue', 'FuLineInTank', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForFuHeatrTyp1', ...
   {'WoFuHeatr','FuHeatrTyp1','FuHeatrTyp2'}, ...
   [0 1 2], ...
   'DefaultValue', 'WoFuHeatr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForGlassTyp1', ...
   {'WindGlassStd','WindGlassNoStd'}, ...
   [0 1], ...
   'DefaultValue', 'WindGlassStd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of ClimaCfgForGlassTyp1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHeatrTyp1', ...
   {'NoHeatr','FuHeatr','HvHeatr','PrkgHeatrElec','Hv12V','Hvah','HvahAndHvch'}, ...
   [1 2 3 4 128 129 130], ...
   'DefaultValue', 'NoHeatr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvHeatrTyp1', ...
   {'WoHvHeatr','HvHeatrTyp1','HvHeatrTyp2'}, ...
   [0 1 2], ...
   'DefaultValue', 'WoHvHeatr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacFrontBlowerType', ...
   {'LinFrntBlw','PWMFrntBlwWithSpdFeb','PWMFrntBlwWoSpdFeb','FETOrLPMFrntBlw','LinFrntBlwWoFb'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'LinFrntBlw', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacLowSideRETXVESts', ...
   {'No','TXV','EXV','ETXV'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'No', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacReBlowerType', ...
   {'LinReBlw','PWMReBlwWithSpdFeb','PWMReBlwWoSpdFeb','FETOrLPMReBlw','LinReBlwWoFb'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'LinReBlw', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacReTyp1', ...
   {'NoBlw','Blw','BlwWithActrMod','BlwWithActrTem','BlwWithActrModAndTem'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoBlw', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacSnsrRCmptmtESts', ...
   {'Undefd','WoSnsr','WithMtrlSnsr','WithCarSnsr'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacSnsrReHexESts', ...
   {'No','WithReHexSnsr'}, ...
   [0 1], ...
   'DefaultValue', 'No', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfAirDistbnSetg1', ...
   {'NrOfAirDistbnSetg1','NrOfAirDistbnSetg2','NrOfAirDistbnSetg3','NrOfAirDistbnSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfAirDistbnSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfDoor1', ...
   {'Door5','Door4','Door3','Door2'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Door5', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfFanLvlSetg1', ...
   {'NrOfFanLvlSetg1','NrOfFanLvlSetg2','NrOfFanLvlSetg3','NrOfFanLvlSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfFanLvlSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfTSetg1', ...
   {'NrOfTSetg1','NrOfTSetg2','NrOfTSetg3','NrOfTSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfTSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForRowSecVentCentrVrnt1', ...
   {'NotPrsnt','Ind','Cmn'}, ...
   [0 1 2], ...
   'DefaultValue', 'NotPrsnt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CooltVlvOutpTyp', ...
   {'Undefd','ILimd','IFull'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ElcTrLFtngMdle', ...
   {'Undefd','NtEqpdWthElcTrFtngMdle','EqpdWthElcTrFtngMdle'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FLOATINGDRVING', ...
   {'Undefd','WthtFltngDrving','WthFltngDrvngbyWhls','WthFltngDrvngbyWhlsandPrpllr'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FrontHeaterExchanger', ...
   {'Undefd','WithoutPTC','WithPTC1000w','WithHAVH1zone','WithHAVH2zone','WithHAVH3zone','OnezoneWotC','TwozoneWotC','ThreezoneWotC'}, ...
   [0 1 2 3 4 5 6 7 8], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HeadRadar', ...
   {'UnDefd','WithoutRadar','WithOMC','WithTOF','WithOMCAndTOF'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'UnDefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LifeDetection', ...
   {'Undefd','WithoutDetection','SecondRowOnly','BothRowOnly','AlarmWithoutSound','AlarmWithSound','LifeDetectionWithUWB','WithCameraMiliterRadarAndCo2'}, ...
   [0 1 2 3 4 5 6 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'RFKEY', ...
   {'Undefd','NORFKEY','LLT','ELUT','HLUT','LLUT','LRLU','SLUT','EHLUT','ELLUT','HLLUT','LRLUT','LRHLU','LRELU','LRLLU'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'StartDevice', ...
   {'Undefd','StrtWithTwoDir','StrtWithOneDir','StrtBtn','NoPhyDev'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TEMPEREDSTORAGEBOX', ...
   {'Undefd','NTEMPSTORBOX','TMPSTRBXRFORHT','TMPSTRBXRF','TMPSTRBXRFORHTELEC','WthGlySmrtRfrgrtr','IntgrtdGlysmrtfrdgRFORHAT','IntgrtdGlysmrtfrdgRFORHATLC','ConstantTempBox','IntrgtdDCAndELECDOOR','IntrgtdLCAndELECDOOR','SmartFridgeMechanical','IntrgtdLCAndELECOpen','CHSMDOOR'}, ...
   [0 1 2 3 4 6 9 10 11 12 13 14 15 16], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WadingAssistSystem', ...
   {'Undefd','WithoutAssistSystem','WithWadingAssistSystem','WitWadingAssistSystemVisualDetection','WthWadingAssistSystemSonar'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WndFllwngHmnMvmntFnctn', ...
   {'Undefd','WithtFunctn','FcsOnDrvr','FcsOnDrvrAndPss','FcsOnDrvrAndSec','FcsOnDrvrAndPssAndSec','FrntNonFcsBse','FrntNnFcsAvdnc','SecNonFcsBse','SecNonFcsAvdnc'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

