Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForStrtStop', ...
   {'FullUnavailable','CoolingAndOtherAvailable','HeatingAndOtherAvailable','FullAvailable'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'FullUnavailable', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'EngRunngReq', ...
   {'Dft','StopInhb','RunReq','Resd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Dft', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'EngSt1', ...
   {'Ini','Awake','Rdy','PreStrtg','StrtgInProgs','RunngRunng','RunngStb','RunngStrtgInProgs','RunngRemStrtd','AftRun'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Ini', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Flg1', ...
   {'Rst','Set'}, ...
   [0 1], ...
   'DefaultValue', 'Rst', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WipgSpdInfo', ...
   {'Off','IntlLo','IntlHi','WipgSpd4045','WipgSpd4650','WipgSpd5155','WipgSpd5660','WiprErr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

