Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'ClimaCfgForHeatrTyp1', ...
   {'NoHeatr','FuHeatr','HvHeatr','PrkgHeatrElec','Hv12V','Hvah','HvahAndHvch'}, ...
   [1 2 3 4 128 129 130], ...
   'DefaultValue', 'NoHeatr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LvlOfPrioTyp', ...
   {'Off','LvlOfPrio1','LvlOfPrio2','LvlOfPrio3','LvlOfPrio4','LvlOfPrio5','LvlOfPrio6','LvlOfPrio7'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qf1', ...
   {'DevOfDataUndefd','DataTmpUndefdAndEvlnInProgs','DevOfDataNotWithinRngAllwd','DataCalcdWithDevDefd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'DevOfDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

