Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForAirMtrlSnsrGly', ...
   {'Undefd','WithoutInOutPM25','WithInPM25','WithInOutPM25','WithInPM25US'}, ...
   [0 1 2 3 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHeatrTyp1', ...
   {'NoHeatr','FuHeatr','HvHeatr','PrkgHeatrElec','Hv12V','Hvah','HvahAndHvch'}, ...
   [1 2 3 4 128 129 130], ...
   'DefaultValue', 'NoHeatr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfTSetg1', ...
   {'NrOfTSetg1','NrOfTSetg2','NrOfTSetg3','NrOfTSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfTSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaStStrtUp', ...
   {'Comfort','Cooldown','Heatup'}, ...
   [0 1 2], ...
   'DefaultValue', 'Comfort', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DataQf', ...
   {'NotOk','Ok'}, ...
   [0 1], ...
   'DefaultValue', 'NotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DrvrPfmncWarnReq', ...
   {'Unavailable','Unknown','NoWarning','Distractive','Warninglevel1','Warninglevel2_Navigation','Warninglevel2'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'Unavailable', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtTSpSpcl', ...
   {'Norm','Lo','Hi'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacFanLvl', ...
   {'Off','LvlMan1','LvlMan2','LvlMan3','LvlMan4','LvlMan5','LvlMan6','LvlMan7','LvlMan8','LvlMan9','LvlAutMinusMinus','LvlAutMinus','LvlAutNorm','LvlAutPlus','LvlAutPlusPlus','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacTIfQf', ...
   {'SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1], ...
   'DefaultValue', 'SnsrDataNotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaActv', ...
   {'Off','PreCdngActv','PostCdngActv','BlwAftRunActv'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

