Simulink.defineIntEnumType( 'ActrReq', ...
   {'Off','On','AutOn'}, ...
   [0 1 2], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'BookChargeSetResponse', ...
   {'Default','Success','Cancelled','Fail'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForHvacRe', ...
   {'Undefd','NoHvacRe','HvacReWoPtc','HvacReWithPtc','HvacReWithHVAH','HvacReWthHVAHANDHVCHDblTZn','HvacReWthHVAHLinVBMR_RHFA','HvacReWthHVAHLinVBMR','HvacReWthHVAHLinRHFA','HvacReWthHVAHANDHVCHDblTMF'}, ...
   [0 1 2 3 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacTyp2', ...
   {'Undefd','HvacElectronic2','HvacElectronic4','HvacSimple1','HvacSimple2','HvacSimple3','HvacMan','HvacManWithRecircPtl','HvacSimple4','HvacElectronic1','ADU1Z','ADU2Z','ADU3Z','ADU4Z','HVAC4ZonesFullControl','HVAC5ZonesFullControl','HVAC4DOUBLE','HVAC333DOUBLE','HVAC331DOUBLE','Front3Zones_RearHvac','Front2Zones_RearHvac'}, ...
   [0 1 2 3 4 5 6 128 129 130 131 132 133 134 135 136 137 139 141 142 147], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForBRAND', ...
   {'Undefd','VCC','GEELY','LYNK','PROTON','LOTUS','LEVC','YUANCHENG','SMART','POLESTAR','ZEEKR','GEOMETRY','RENAULT','ALPINE'}, ...
   [0 1 2 3 4 5 6 7 8 9 16 17 19 24], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfAirDistbnSetg1', ...
   {'NrOfAirDistbnSetg1','NrOfAirDistbnSetg2','NrOfAirDistbnSetg3','NrOfAirDistbnSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfAirDistbnSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfFanLvlSetg1', ...
   {'NrOfFanLvlSetg1','NrOfFanLvlSetg2','NrOfFanLvlSetg3','NrOfFanLvlSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfFanLvlSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfTSetg1', ...
   {'NrOfTSetg1','NrOfTSetg2','NrOfTSetg3','NrOfTSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfTSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaStStrtUp', ...
   {'Comfort','Cooldown','Heatup'}, ...
   [0 1 2], ...
   'DefaultValue', 'Comfort', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtTFrntQf', ...
   {'SnsrDataUndefd','FanNotRunning','SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SnsrDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CoolgReqForDisp', ...
   {'NoReq','LoReq','HiReq'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Flg1', ...
   {'Rst','Set'}, ...
   [0 1], ...
   'DefaultValue', 'Rst', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiClimaReqQf', ...
   {'Undefd','Off','HmiClimaRlv','Resv1'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtCoolgReq', ...
   {'Off','Auto'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtTSpSpcl', ...
   {'Norm','Lo','Hi'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacFanLvl', ...
   {'Off','LvlMan1','LvlMan2','LvlMan3','LvlMan4','LvlMan5','LvlMan6','LvlMan7','LvlMan8','LvlMan9','LvlAutMinusMinus','LvlAutMinus','LvlAutNorm','LvlAutPlus','LvlAutPlusPlus','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacReCtrl', ...
   {'Off','OffWithNoOccpt','On'}, ...
   [0 1 2], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacRecircCmd', ...
   {'Aut','AutWithAirQly','RecircFull','OscircFull'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Aut', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacTIfQf', ...
   {'SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1], ...
   'DefaultValue', 'SnsrDataNotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'MemReqSts', ...
   {'Pnd','Ok','NotOk'}, ...
   [0 1 2], ...
   'DefaultValue', 'Pnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('NVRAM memory status remapped by MemMgr and sent to SWCs '), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ObsvrStsForCmptmt', ...
   {'InActv','Inin','Actv'}, ...
   [0 1 2], ...
   'DefaultValue', 'InActv', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PatSeld', ...
   {'NoSeld','RefrshPatSeld','ParentchildPatSeld','Restpatseld','RomanticPatseld','StrangerPatseld','TheaterPatseld','PetPatseld','BiochalPatseld','CarWashPatseld','EcoPatseld','KingPatseld','CustomizationPatseld','MeetingPatseld','CombatCockPatseld'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'NoSeld', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaActv', ...
   {'Off','PreCdngActv','PostCdngActv','BlwAftRunActv'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaMod', ...
   {'NoPrkg','PreTmrPrkg','PreDirPrkg','PostPrkg','PreClng'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoPrkg', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SnsrSts', ...
   {'Ok','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'Ok', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

