Simulink.defineIntEnumType( 'AmbTStForClsDwn', ...
   {'Undefd','Cold','Inter','Wrm'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForHvacRe', ...
   {'Undefd','NoHvacRe','HvacReWoPtc','HvacReWithPtc','HvacReWithHVAH','HvacReWthHVAHANDHVCHDblTZn','HvacReWthHVAHLinVBMR_RHFA','HvacReWthHVAHLinVBMR','HvacReWthHVAHLinRHFA','HvacReWthHVAHANDHVCHDblTMF'}, ...
   [0 1 2 3 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrInd1', ...
   {'Cmn','Ind'}, ...
   [0 1], ...
   'DefaultValue', 'Cmn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrnt1', ...
   {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'FlapInd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrntCen', ...
   {'NoFlap','FlapInd'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlap', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'MemReqSts', ...
   {'Pnd','Ok','NotOk'}, ...
   [0 1 2], ...
   'DefaultValue', 'Pnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('NVRAM memory status remapped by MemMgr and sent to SWCs '), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

