Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'ClimaCfgForRowSecVentCentrVrnt1', ...
   {'NotPrsnt','Ind','Cmn'}, ...
   [0 1 2], ...
   'DefaultValue', 'NotPrsnt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacTIfQf', ...
   {'SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1], ...
   'DefaultValue', 'SnsrDataNotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

