Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'ClimaCfgForActrRecircAndOsaCmnPrsnt1', ...
   {'Ind','Cmn','Nest'}, ...
   [0 1 2], ...
   'DefaultValue', 'Ind', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of ClimaCfgForActrRecircAndOsaCmnPrsnt1.'), ... 
   'AddClassNameToEnumNames', true);

