Simulink.defineIntEnumType( 'ActrReq', ...
   {'Off','On','AutOn'}, ...
   [0 1 2], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AmntSnsr', ...
   {'Amnt','InitValue','Error'}, ...
   [0 14 15], ...
   'DefaultValue', 'Amnt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForHeatPmpTyp', ...
   {'Undefd','WithoutHeatPump','WithNonIntegratedHeatPump','WithIntegratedHeatPump'}, ...
   [0 1 2 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacRe', ...
   {'Undefd','NoHvacRe','HvacReWoPtc','HvacReWithPtc','HvacReWithHVAH','HvacReWthHVAHANDHVCHDblTZn','HvacReWthHVAHLinVBMR_RHFA','HvacReWthHVAHLinVBMR','HvacReWthHVAHLinRHFA','HvacReWthHVAHANDHVCHDblTMF'}, ...
   [0 1 2 3 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacReBlowerType', ...
   {'LinReBlw','PWMReBlwWithSpdFeb','PWMReBlwWoSpdFeb','FETOrLPMReBlw','LinReBlwWoFb'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'LinReBlw', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfTSetg1', ...
   {'NrOfTSetg1','NrOfTSetg2','NrOfTSetg3','NrOfTSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfTSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtCoolgSts', ...
   {'OffNoReq','OffByEvaprTLo','OffByPLo','OffByAmbTOutOfRng','OffBySysFailr','OffByLoadCut','OnWithBattCoolg','On','OnWithRefrigerator','OnWithRefrigeratorAndBattCoolg'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'OffNoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CoolgReqForDisp', ...
   {'NoReq','LoReq','HiReq'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtCoolgReq', ...
   {'Off','Auto'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtTSpSpcl', ...
   {'Norm','Lo','Hi'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacTIfQf', ...
   {'SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1], ...
   'DefaultValue', 'SnsrDataNotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnBdChrgrSts1', ...
   {'Disconnected','ConnectedWithoutPower','PowerAvailableButNotActivated','ConnectedWithPower','DischargeConnectwithoutpowerincar','DischargeConnectwithoutpoweroutcar','DischargeConnectwithpowerincar','DischargeConnectwithpoweroutcar','Init','Fault','NotCompleteConnected','Reserved0','Reserved1','Reserved2'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13], ...
   'DefaultValue', 'Disconnected', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOffCrit1', ...
   {'NotVld1','Off','On','NotVld2'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NotVld1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of OnOffCrit1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaActv', ...
   {'Off','PreCdngActv','PostCdngActv','BlwAftRunActv'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'RelHumKeepSts', ...
   {'Off','DehumByAC','DehumByRec','Humdfy'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ThmgtLevel', ...
   {'NoRequest','Boost1','Boost2','Spare'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoRequest', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WipgSpdInfo', ...
   {'Off','IntlLo','IntlHi','WipgSpd4045','WipgSpd4650','WipgSpd5155','WipgSpd5660','WiprErr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

