Simulink.defineIntEnumType( 'ActrReq', ...
   {'Off','On','AutOn'}, ...
   [0 1 2], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AmbTStForClsDwn', ...
   {'Undefd','Cold','Inter','Wrm'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForExtVentnClimaCtrl', ...
   {'Undefd','WoExtVentnClimaCtrl','WithExtVentnClimaCtrl'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCenCfgForVrntOfVehSysElec1', ...
   {'VehLrg1','VehSmall1'}, ...
   [0 1], ...
   'DefaultValue', 'VehLrg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrInd1', ...
   {'Cmn','Ind'}, ...
   [0 1], ...
   'DefaultValue', 'Cmn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrInd2', ...
   {'Cmn','Ind'}, ...
   [0 1], ...
   'DefaultValue', 'Cmn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrnt1', ...
   {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'FlapInd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrnt2', ...
   {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn','VentFlrCmnAdjmt','FlrVentCmnAdjmt','WithoutFlap'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'FlapInd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrntCen', ...
   {'NoFlap','FlapInd'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlap', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrRecircAndOsaCmnPrsnt1', ...
   {'Ind','Cmn','Nest'}, ...
   [0 1 2], ...
   'DefaultValue', 'Ind', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of ClimaCfgForActrRecircAndOsaCmnPrsnt1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForCarTyp1', ...
   {'CarTyp0','CarTyp1','CarTyp2'}, ...
   [0 1 2], ...
   'DefaultValue', 'CarTyp0', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacFrontBlowerType', ...
   {'LinFrntBlw','PWMFrntBlwWithSpdFeb','PWMFrntBlwWoSpdFeb','FETOrLPMFrntBlw','LinFrntBlwWoFb'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'LinFrntBlw', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaManModCmftSts', ...
   {'None','AvoidColdWind','AvoidHotWind','Resd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtClngActv', ...
   {'Off','OnLvlLo','OnLvlMed','OnLvlHi'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CoolgReqForDisp', ...
   {'NoReq','LoReq','HiReq'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacFanLvl', ...
   {'Off','LvlMan1','LvlMan2','LvlMan3','LvlMan4','LvlMan5','LvlMan6','LvlMan7','LvlMan8','LvlMan9','LvlAutMinusMinus','LvlAutMinus','LvlAutNorm','LvlAutPlus','LvlAutPlusPlus','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacActrSpd', ...
   {'SpdAut','Spd1','Spd2','Spd3','Spd4'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'SpdAut', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacActrSts', ...
   {'Ok','Flt','CalRunng'}, ...
   [0 1 2], ...
   'DefaultValue', 'Ok', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanFrntLimForPwrAllwd', ...
   {'NoLim','FanLo','FanOff'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoLim', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'IntCo2Sts', ...
   {'NoReq','CDSMontr','EgyReq','ClimaOn','SocLowBlwrOn','SocLowBlowrOff'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'MemReqSts', ...
   {'Pnd','Ok','NotOk'}, ...
   [0 1 2], ...
   'DefaultValue', 'Pnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('NVRAM memory status remapped by MemMgr and sent to SWCs '), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOffNoReq', ...
   {'NoReq','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaActv', ...
   {'Off','PreCdngActv','PostCdngActv','BlwAftRunActv'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Warn2', ...
   {'NoWarn','Warn'}, ...
   [0 1], ...
   'DefaultValue', 'NoWarn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

