Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForExtVentnClimaCtrl', ...
   {'Undefd','WoExtVentnClimaCtrl','WithExtVentnClimaCtrl'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacRe', ...
   {'Undefd','NoHvacRe','HvacReWoPtc','HvacReWithPtc','HvacReWithHVAH','HvacReWthHVAHANDHVCHDblTZn','HvacReWthHVAHLinVBMR_RHFA','HvacReWthHVAHLinVBMR','HvacReWthHVAHLinRHFA','HvacReWthHVAHANDHVCHDblTMF'}, ...
   [0 1 2 3 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrInd1', ...
   {'Cmn','Ind'}, ...
   [0 1], ...
   'DefaultValue', 'Cmn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrInd2', ...
   {'Cmn','Ind'}, ...
   [0 1], ...
   'DefaultValue', 'Cmn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrnt1', ...
   {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'FlapInd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrnt2', ...
   {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn','VentFlrCmnAdjmt','FlrVentCmnAdjmt','WithoutFlap'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'FlapInd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForActrModVrntCen', ...
   {'NoFlap','FlapInd'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlap', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForAmntOfSeatRow1', ...
   {'NrOfRow1','NrOfRow2','NrOfRow3'}, ...
   [0 1 2], ...
   'DefaultValue', 'NrOfRow1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfTSetg1', ...
   {'NrOfTSetg1','NrOfTSetg2','NrOfTSetg3','NrOfTSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfTSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForRowSecVentCentrVrnt1', ...
   {'NotPrsnt','Ind','Cmn'}, ...
   [0 1 2], ...
   'DefaultValue', 'NotPrsnt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ExtVentToastFrmClimaSts', ...
   {'NoToast','StartTrue','StartFalse','LowPower','Exit'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoToast', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FrontHeaterExchanger', ...
   {'Undefd','WithoutPTC','WithPTC1000w','WithHAVH1zone','WithHAVH2zone','WithHAVH3zone','OnezoneWotC','TwozoneWotC','ThreezoneWotC'}, ...
   [0 1 2 3 4 5 6 7 8], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Level4', ...
   {'None','Lvl1','Lvl2','Lvl3','Lvl4','Lvl5','Lvl6','Lvl7','Lvl8','Lvl9'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VCCMaxReqReqdForActrFrnt', ...
   {'NoMaxReqReqd','MaxReqReqdForDefrst','MaxReqReqdForRowFirstAtFlr','MaxReqReqdForRowFirstAtVent','MaxReqReqdForRowSecAtFlr','MaxReqReqdForRowSecAtVent','MaxReqReqdForDefrstAndVent2Zone','MaxReqReqdForDefrstAndFlr2Zone','MaxReqReqdForRowFirstAtVentSideLe','MaxReqReqdForRowFirstAtVentSideRi','MaxReqReqdForRowFirstAtVentLe','MaxReqReqdForRowFirstAtVentRi','MaxReqReqdForRowFirstAtFlrLe','MaxReqReqdForRowFirstAtFlrRi','MaxReqReqdForRowSecAtVentLe','MaxReqReqdForRowSecAtVentRi','MaxReqReqdForRowSecAtFlrLe','MaxReqReqdForRowSecAtFlrRi'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17], ...
   'DefaultValue', 'NoMaxReqReqd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Used for loggingwhich actuator that requests max'), ... 
   'AddClassNameToEnumNames', true);

