Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForHvacRe', ...
   {'Undefd','NoHvacRe','HvacReWoPtc','HvacReWithPtc','HvacReWithHVAH','HvacReWthHVAHANDHVCHDblTZn','HvacReWthHVAHLinVBMR_RHFA','HvacReWthHVAHLinVBMR','HvacReWthHVAHLinRHFA','HvacReWthHVAHANDHVCHDblTMF'}, ...
   [0 1 2 3 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForAmntOfSeatRow1', ...
   {'NrOfRow1','NrOfRow2','NrOfRow3'}, ...
   [0 1 2], ...
   'DefaultValue', 'NrOfRow1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForCmptmtSnsr1', ...
   {'WoCmptmtSnsr','AirTWithFan','IntrMtrlT'}, ...
   [0 1 2], ...
   'DefaultValue', 'WoCmptmtSnsr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHvacSnsrRCmptmtESts', ...
   {'Undefd','WoSnsr','WithMtrlSnsr','WithCarSnsr'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtTFrntQf', ...
   {'SnsrDataUndefd','FanNotRunning','SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SnsrDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DrvrPfmncWarnReq', ...
   {'Unavailable','Unknown','NoWarning','Distractive','Warninglevel1','Warninglevel2_Navigation','Warninglevel2'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'Unavailable', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DshbTForClimaQf', ...
   {'SnsrDataUndefd','SnsrDataPnd','SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SnsrDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of DshbTForClimaQf.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Flg1', ...
   {'Rst','Set'}, ...
   [0 1], ...
   'DefaultValue', 'Rst', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'MemReqSts', ...
   {'Pnd','Ok','NotOk'}, ...
   [0 1 2], ...
   'DefaultValue', 'Pnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('NVRAM memory status remapped by MemMgr and sent to SWCs '), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ObsvrStsForCmptmt', ...
   {'InActv','Inin','Actv'}, ...
   [0 1 2], ...
   'DefaultValue', 'InActv', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaActv', ...
   {'Off','PreCdngActv','PostCdngActv','BlwAftRunActv'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qly2', ...
   {'Flt','NoInfo','Vld'}, ...
   [0 1 2], ...
   'DefaultValue', 'Flt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SnsrSts', ...
   {'Ok','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'Ok', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VCCNvRamRxSts', ...
   {'NvRamNotRx','ShortStopNvRamRx','NvRamGuessed','NvRamRx'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NvRamNotRx', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('NvRam recieval status'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WinAndRoofAndCurtPosnTyp', ...
   {'PosnUkwn','ClsFull','PercOpen4','PercOpen8','PercOpen12','PercOpen16','PercOpen20','PercOpen24','PercOpen28','PercOpen32','PercOpen36','PercOpen40','PercOpen44','PercOpen48','PercOpen52','PercOpen56','PercOpen60','PercOpen64','PercOpen68','PercOpen72','PercOpen76','PercOpen80','PercOpen84','PercOpen88','PercOpen92','PercOpen96','OpenFull','Resd1','Resd2','Resd3','Resd4','Movg'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31], ...
   'DefaultValue', 'PosnUkwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

