Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CabinOHSts', ...
   {'NoReq','COHMon','EgyReq','ClimaOn'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirMtrlSnsrGly', ...
   {'Undefd','WithoutInOutPM25','WithInPM25','WithInOutPM25','WithInPM25US'}, ...
   [0 1 2 3 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacRe', ...
   {'Undefd','NoHvacRe','HvacReWoPtc','HvacReWithPtc','HvacReWithHVAH','HvacReWthHVAHANDHVCHDblTZn','HvacReWthHVAHLinVBMR_RHFA','HvacReWthHVAHLinVBMR','HvacReWthHVAHLinRHFA','HvacReWthHVAHANDHVCHDblTMF'}, ...
   [0 1 2 3 128 129 130 131 132 133], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacTyp2', ...
   {'Undefd','HvacElectronic2','HvacElectronic4','HvacSimple1','HvacSimple2','HvacSimple3','HvacMan','HvacManWithRecircPtl','HvacSimple4','HvacElectronic1','ADU1Z','ADU2Z','ADU3Z','ADU4Z','HVAC4ZonesFullControl','HVAC5ZonesFullControl','HVAC4DOUBLE','HVAC333DOUBLE','HVAC331DOUBLE','Front3Zones_RearHvac','Front2Zones_RearHvac'}, ...
   [0 1 2 3 4 5 6 128 129 130 131 132 133 134 135 136 137 139 141 142 147], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrpsnTypGly', ...
   {'Undefd','CombEng','HV','PHEV','BEV','MHEVForGEEA2','EREV'}, ...
   [0 1 2 3 4 128 129], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForRoofHatch', ...
   {'Undefd','NoRoofHatchf','OpenaPanoRoof','Hatch','ElecPanoRoof','PanoRoofFixed','PanoRoofPolestarStarLightFixed','DoubleSunCurtains','SunrfGlassClrAdj','SunrfGlassClrAdjWithZoning','SunrfGlassClrAdjWithPowSunrfVisor','MetalroofNoSunroofOrPanoCanopy','DoubleSunshadeNoSunroof','SftRf'}, ...
   [0 1 2 3 4 5 6 128 129 130 131 132 133 134], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgForRowSecGly', ...
   {'WithoutHeatgRearSeats','HeatgRearSeats'}, ...
   [1 2], ...
   'DefaultValue', 'WithoutHeatgRearSeats', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatVentnForRowFirst1', ...
   {'Undefd','NoSeatVentn','SeatVentn','DrvrSeatVentn','PassSeatVentn','SeatVentnCushion','DrvrSeatVentnCushion','PassSeatVentnCushion','SeatVentnBackrest','DrvrSeatVentnBackrest','PassSeatVentnBackrest','SeatVentnCushionSMF2','SeatVentnBackrestSMF2','DrvrSeatVentnBackrestSMF2','PassSeatVentnBackrestSMF2','DrvrSeatVentnCushionSMF2','PassSeatVentnCushionSMF2','SeatVentnSMF2','DrvrSeatVentnSMF2','PassSeatVentnSMF2'}, ...
   [0 1 2 3 128 129 130 131 132 133 134 137 138 139 140 141 142 143 144 145], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForSeatVentnForRowSecGly', ...
   {'Undefd','WithoutSecSeats','SecSeats','SecSeatsVentnCushion','SecSeatsRiVentnCushion','SecSeatsVentnBackrest'}, ...
   [0 1 2 128 129 131], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForVehTyp3', ...
   {'Undefd','L541','V542','V543','V526','V426','V541','V316','V320','V323','V431','V432','L431','V433','P514','V331','V317','CX11','CS11','CH11','CC11','CS12','DCY11','Reserved1','FX11','LAMBDA','HX11','HC11','HB11','ALPHA','GK11H','L946','P181','P177','E366','P389','EX11','KX11','DC1E','KW11','ES11','BC1E','EF1E','DX1E','CF1E','CM1E','DX11','G733','V216','BX1E','FS11','G636','CX21','L743','P417','E155','CS1E','EO11','V51DK','E335','CM2E','CX1E','E171','E371','HY11','HS11','EX1E','HRE1','XE08','G426','MC11','E245','E261','E23H','P145','V446K','SIGMA','P171','P179','P22H','FS21','P376','L955','SS21','E145','P162','KX21','P166','E281','KO11'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 128 129 130 131 132 133 134 135 138 139 140 141 142 143 144 145 146 147 148 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 224 225 226 227 228 229 230 231 233 234 235 236 239 241 242 243 244 245 246 247 248 249 250], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ChrgrSts1', ...
   {'Idle','PreStrt','Chrgn','Alrm','Srv','Diagc','Boot','Rstrt','DisChrgn','BookChrgn','Shutdown','Heating','Cooling'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForBRAND', ...
   {'Undefd','VCC','GEELY','LYNK','PROTON','LOTUS','LEVC','YUANCHENG','SMART','POLESTAR','ZEEKR','GEOMETRY','RENAULT','ALPINE'}, ...
   [0 1 2 3 4 5 6 7 8 9 16 17 19 24], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForNrOfTSetg1', ...
   {'NrOfTSetg1','NrOfTSetg2','NrOfTSetg3','NrOfTSetg4'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NrOfTSetg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaOvrheatProWarnSts', ...
   {'NoWarn','Err','PwrLo','Tout'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoWarn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaSts', ...
   {'Start','Finish'}, ...
   [0 1], ...
   'DefaultValue', 'Start', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaWarn', ...
   {'NoWarn','FuLo','BattLo','FuAndBattLo','TLo','THi','Error','HVError','ActvnLimd'}, ...
   [0 1 2 3 4 5 6 7 8], ...
   'DefaultValue', 'NoWarn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtClngActv', ...
   {'Off','OnLvlLo','OnLvlMed','OnLvlHi'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'EgyPrio', ...
   {'NoPrio','CtrlrClima','U12ForClima'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoPrio', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'EnableDisableCoding', ...
   {'Disabled','Enabled'}, ...
   [0 1], ...
   'DefaultValue', 'Disabled', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of Flg1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'EngSt1', ...
   {'Ini','Awake','Rdy','PreStrtg','StrtgInProgs','RunngRunng','RunngStb','RunngStrtgInProgs','RunngRemStrtd','AftRun'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Ini', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Err1', ...
   {'NoErr','Err'}, ...
   [0 1], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ErsCmd', ...
   {'ErsCmdNotSet','ErsCmdOn','ErsCmdOff'}, ...
   [0 1 2], ...
   'DefaultValue', 'ErsCmdNotSet', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ExtVentTemprSts', ...
   {'None','LO','HI','Normal'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ExtVentToastFrmClimaSts', ...
   {'NoToast','StartTrue','StartFalse','LowPower','Exit'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoToast', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FanVolReq', ...
   {'idle','lv1','lv2','lv3','lv4','lv5','lv6','lv7','lv8','lv9'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GearLvrIndcn2', ...
   {'ParkIndcn','RvsIndcn','NeutIndcn','DrvIndcn','ManModeIndcn','Resd1','Resd2','Undefd'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'ParkIndcn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HVReqFb', ...
   {'Default','HvOnOk','HvSocLow','HvFalut'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HeatrTyp', ...
   {'NoHeatr','FuHeatr','HvHeatr','HeatrElec','FuHeatrAndHeatrElec'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoHeatr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtCoolgReq', ...
   {'Off','Auto'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtTSpSpcl', ...
   {'Norm','Lo','Hi'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacFanLvl', ...
   {'Off','LvlMan1','LvlMan2','LvlMan3','LvlMan4','LvlMan5','LvlMan6','LvlMan7','LvlMan8','LvlMan9','LvlAutMinusMinus','LvlAutMinus','LvlAutNorm','LvlAutPlus','LvlAutPlusPlus','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacRecircCmd', ...
   {'Aut','AutWithAirQly','RecircFull','OscircFull'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Aut', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvActvnSts', ...
   {'Open','Clsd','KeepSt','OpenAndReqActvDcha'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Open', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvCooltHeatrSts', ...
   {'Off','LockedUntilNextStart','LockedUntilService','LockedPermanent','Operation','Reserved1','Reserved2','Reserved3'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'IntCo2Sts', ...
   {'NoReq','CDSMontr','EgyReq','ClimaOn','SocLowBlwrOn','SocLowBlowrOff'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Level4', ...
   {'None','Lvl1','Lvl2','Lvl3','Lvl4','Lvl5','Lvl6','Lvl7','Lvl8','Lvl9'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LifeDetection', ...
   {'Undefd','WithoutDetection','SecondRowOnly','BothRowOnly','AlarmWithoutSound','AlarmWithSound','LifeDetectionWithUWB','WithCameraMiliterRadarAndCo2'}, ...
   [0 1 2 3 4 5 6 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LockSt3', ...
   {'LockUndefd','LockUnlckd','LockTrUnlckd','LockLockd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'LockUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LockTrigSrc2', ...
   {'NoTrigSrc','KeyRem','Keyls','IntrSwt','SpdAut','TmrAut','Slam','Telm','Crash','Apprch','OutsOth','InsOth'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11], ...
   'DefaultValue', 'NoTrigSrc', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'MemReqSts', ...
   {'Pnd','Ok','NotOk'}, ...
   [0 1 2], ...
   'DefaultValue', 'Pnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('NVRAM memory status remapped by MemMgr and sent to SWCs '), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NoReqOnOff', ...
   {'Norequest','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norequest', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NormalLowHigh', ...
   {'Normal','Low','High'}, ...
   [0 1 2], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOffNoReq', ...
   {'NoReq','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyAvlSts', ...
   {'Off','Diffuse','NasalCannula','Error','None','PwrLo','BattleLo','TmrOvr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyReq', ...
   {'NoReq','Off','Diffuse','NasalCannula'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PreCdngReqFromExtSrc', ...
   {'NoReq','Off','OnHmi','OnTelm'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PreClngNotif', ...
   {'NoReq','NoWarn','Done','Err','Intrpt','Spare1','Spare2','Spare3'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PreClngSts', ...
   {'Off','UniqueActv','WithPreCdngActv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaMod', ...
   {'NoPrkg','PreTmrPrkg','PreDirPrkg','PostPrkg','PreClng'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoPrkg', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaReqSts', ...
   {'NoPrkg','PrePrkgTmrReq','PrePrkgDirReq','PostPrkgReq','PrkgEgyOk','PrePrkgRunng','PostPrkgRunng','PrkgSusp','PreClngDirReq','PreClngRunng'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'NoPrkg', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgModMgr', ...
   {'Undefd','Off','EgyReq','PrkgActv','EgyReqFromTmr','NewTmrInin','PrkgFromWallActv','PrkgFromBattActv'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'RemVentSts', ...
   {'NoReq','EgyReq','ClimaOn'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'RemVentWarningSts', ...
   {'NoErr','Err','PwrNotAllwd','EgyNotAllwd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SchedCmptHeatCoolFB', ...
   {'NoReq','ON','OFF','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SeatClimaLvl', ...
   {'Off','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SeatHeatDurgClimaEnad', ...
   {'SeatHeatOff','SeatDrvOn','SeatPassOn','SeatDrvrAndPass','SeatLeftRearOn','SeatRightRearOn'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'SeatHeatOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'StrtRemSts1', ...
   {'Idle','Strtg','Actv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TSpReq', ...
   {'idle','lo','normal','hi'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TelmSeatClimaLvl', ...
   {'off','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TelmSeatClimaLvlExsrc', ...
   {'NoReq','off','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UnLckCoolActvLvl', ...
   {'NoReq','CoolForFrnt','CoolForFrntAndRear'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UnLckHeatActvLvl', ...
   {'NoReq','HeatForFrnt','HeatForFrntAndRear'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WarnLvl', ...
   {'WarnLvlMsg_Off','WarnLvlMsg_Lv1','WarnLvlMsg_Lv2','WarnLvlMsg_Lv3','WarnLvlMsg_Lv4_1','WarnLvlMsg_Lv4_2','WarnLvlMsg_Lv4_3','WarnLvlMsg_Reserved'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'WarnLvlMsg_Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'WinAndRoofAndCurtPosnTyp', ...
   {'PosnUkwn','ClsFull','PercOpen4','PercOpen8','PercOpen12','PercOpen16','PercOpen20','PercOpen24','PercOpen28','PercOpen32','PercOpen36','PercOpen40','PercOpen44','PercOpen48','PercOpen52','PercOpen56','PercOpen60','PercOpen64','PercOpen68','PercOpen72','PercOpen76','PercOpen80','PercOpen84','PercOpen88','PercOpen92','PercOpen96','OpenFull','Resd1','Resd2','Resd3','Resd4','Movg'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31], ...
   'DefaultValue', 'PosnUkwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

