Simulink.defineIntEnumType( 'BatteryReq', ...
   {'Default','Discharging','Finished','Resd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CabinOHSts', ...
   {'NoReq','COHMon','EgyReq','ClimaOn'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CabinOxgenSupply', ...
   {'Undefd','NCbnOxygn','InCbnOxygnDlvry_Mchnicl','NslInhltnNdDffn','DffsOxygn','InCbnOxygnDlvry_MchniclWthSnsr','NslInhltnNdDffnWthSnsr','DffsOxygnWthSnsrr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForAirMtrlSnsrGly', ...
   {'Undefd','WithoutInOutPM25','WithInPM25','WithInOutPM25','WithInPM25US'}, ...
   [0 1 2 3 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForExtVentnClimaCtrl', ...
   {'Undefd','WoExtVentnClimaCtrl','WithExtVentnClimaCtrl'}, ...
   [0 1 2], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForHvacTyp2', ...
   {'Undefd','HvacElectronic2','HvacElectronic4','HvacSimple1','HvacSimple2','HvacSimple3','HvacMan','HvacManWithRecircPtl','HvacSimple4','HvacElectronic1','ADU1Z','ADU2Z','ADU3Z','ADU4Z','HVAC4ZonesFullControl','HVAC5ZonesFullControl','HVAC4DOUBLE','HVAC333DOUBLE','HVAC331DOUBLE','Front3Zones_RearHvac','Front2Zones_RearHvac'}, ...
   [0 1 2 3 4 5 6 128 129 130 131 132 133 134 135 136 137 139 141 142 147], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForPrpsnTypGly', ...
   {'Undefd','CombEng','HV','PHEV','BEV','MHEVForGEEA2','EREV'}, ...
   [0 1 2 3 4 128 129], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForRemEngStrtPreCdn', ...
   {'Undefd','ERSByAppByKeyRunningLight','WithoutRemStrt','WithRemStrt','ERSByAppRunningLight','ERSByKey','ERSByKeyRunningLight','ERSByAppByKey'}, ...
   [0 7 1 2 3 4 5 6], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarCfgForVehTyp3', ...
   {'Undefd','L541','V542','V543','V526','V426','V541','V316','V320','V323','V431','V432','L431','V433','P514','V331','V317','CX11','CS11','CH11','CC11','CS12','DCY11','Reserved1','FX11','LAMBDA','HX11','HC11','HB11','ALPHA','GK11H','L946','P181','P177','E366','P389','EX11','KX11','DC1E','KW11','ES11','BC1E','EF1E','DX1E','CF1E','CM1E','DX11','G733','V216','BX1E','FS11','G636','CX21','L743','P417','E155','CS1E','EO11','V51DK','E335','CM2E','CX1E','E171','E371','HY11','HS11','EX1E','HRE1','XE08','G426','MC11','E245','E261','E23H','P145','V446K','SIGMA','P171','P179','P22H','FS21','P376','L955','SS21','E145','P162','KX21','P166','E281','KO11'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 128 129 130 131 132 133 134 135 138 139 140 141 142 143 144 145 146 147 148 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 224 225 226 227 228 229 230 231 233 234 235 236 239 241 242 243 244 245 246 247 248 249 250], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCenCfgForVrntOfVehSysElec1', ...
   {'VehLrg1','VehSmall1'}, ...
   [0 1], ...
   'DefaultValue', 'VehLrg1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForBRAND', ...
   {'Undefd','VCC','GEELY','LYNK','PROTON','LOTUS','LEVC','YUANCHENG','SMART','POLESTAR','ZEEKR','GEOMETRY','RENAULT','ALPINE'}, ...
   [0 1 2 3 4 5 6 7 8 9 16 17 19 24], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForCoolgPreCdn1', ...
   {'NotAvl','PreVent','PreAirCdn'}, ...
   [0 1 2], ...
   'DefaultValue', 'NotAvl', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForEcuCooltVlvOutp1', ...
   {'Limd','Full'}, ...
   [0 1], ...
   'DefaultValue', 'Limd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForHeatrTyp1', ...
   {'NoHeatr','FuHeatr','HvHeatr','PrkgHeatrElec','Hv12V','Hvah','HvahAndHvch'}, ...
   [1 2 3 4 128 129 130], ...
   'DefaultValue', 'NoHeatr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaOvrheatProWarnSts', ...
   {'NoWarn','Err','PwrLo','Tout'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoWarn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaWarn', ...
   {'NoWarn','FuLo','BattLo','FuAndBattLo','TLo','THi','Error','HVError','ActvnLimd'}, ...
   [0 1 2 3 4 5 6 7 8], ...
   'DefaultValue', 'NoWarn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtClngActv', ...
   {'Off','OnLvlLo','OnLvlMed','OnLvlHi'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtTFrntQf', ...
   {'SnsrDataUndefd','FanNotRunning','SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SnsrDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DCChrgnHndlStsE2E', ...
   {'OnBdChrgrHndlSts_Disconnected','OnBdChrgrHndlSts_ConnectedWithoutPower','OnBdChrgrHndlSts_PowerAvailableButNotActivated','OnBdChrgrHndlSts_ConnectedWithPower','OnBdChrgrHndlSts_Init','OnBdChrgrHndlSts_Fault'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'OnBdChrgrHndlSts_Disconnected', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'EngSt1', ...
   {'Ini','Awake','Rdy','PreStrtg','StrtgInProgs','RunngRunng','RunngStb','RunngStrtgInProgs','RunngRemStrtd','AftRun'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Ini', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ErsCmd', ...
   {'ErsCmdNotSet','ErsCmdOn','ErsCmdOff'}, ...
   [0 1 2], ...
   'DefaultValue', 'ErsCmdNotSet', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FanVolReq', ...
   {'idle','lv1','lv2','lv3','lv4','lv5','lv6','lv7','lv8','lv9'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Flg1', ...
   {'Rst','Set'}, ...
   [0 1], ...
   'DefaultValue', 'Rst', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GearLvrIndcn2', ...
   {'ParkIndcn','RvsIndcn','NeutIndcn','DrvIndcn','ManModeIndcn','Resd1','Resd2','Undefd'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'ParkIndcn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HeatrPreCdngTyp', ...
   {'NoReq','Aut','Fu','Elec'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HeatrTyp', ...
   {'NoHeatr','FuHeatr','HvHeatr','HeatrElec','FuHeatrAndHeatrElec'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoHeatr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtTSpSpcl', ...
   {'Norm','Lo','Hi'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacFanLvl', ...
   {'Off','LvlMan1','LvlMan2','LvlMan3','LvlMan4','LvlMan5','LvlMan6','LvlMan7','LvlMan8','LvlMan9','LvlAutMinusMinus','LvlAutMinus','LvlAutNorm','LvlAutPlus','LvlAutPlusPlus','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvBattMntnReq', ...
   {'Default','DchaReq','SlpReq','ChrgReq'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacFanSts', ...
   {'Off','On','Warning','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'IntCo2Sts', ...
   {'NoReq','CDSMontr','EgyReq','ClimaOn','SocLowBlwrOn','SocLowBlowrOff'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LifeDetection', ...
   {'Undefd','WithoutDetection','SecondRowOnly','BothRowOnly','AlarmWithoutSound','AlarmWithSound','LifeDetectionWithUWB','WithCameraMiliterRadarAndCo2'}, ...
   [0 1 2 3 4 5 6 128], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LockSt3', ...
   {'LockUndefd','LockUnlckd','LockTrUnlckd','LockLockd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'LockUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LockTrigSrc2', ...
   {'NoTrigSrc','KeyRem','Keyls','IntrSwt','SpdAut','TmrAut','Slam','Telm','Crash','Apprch','OutsOth','InsOth'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11], ...
   'DefaultValue', 'NoTrigSrc', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NoReqOnOff', ...
   {'Norequest','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norequest', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NormalLowHigh', ...
   {'Normal','Low','High'}, ...
   [0 1 2], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnBdChrgrSts1', ...
   {'Disconnected','ConnectedWithoutPower','PowerAvailableButNotActivated','ConnectedWithPower','DischargeConnectwithoutpowerincar','DischargeConnectwithoutpoweroutcar','DischargeConnectwithpowerincar','DischargeConnectwithpoweroutcar','Init','Fault','NotCompleteConnected','Reserved0','Reserved1','Reserved2'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13], ...
   'DefaultValue', 'Disconnected', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOffNoReq', ...
   {'NoReq','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PreCdngReqFromExtSrc', ...
   {'NoReq','Off','OnHmi','OnTelm'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaReqSts', ...
   {'NoPrkg','PrePrkgTmrReq','PrePrkgDirReq','PostPrkgReq','PrkgEgyOk','PrePrkgRunng','PostPrkgRunng','PrkgSusp','PreClngDirReq','PreClngRunng'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'NoPrkg', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qf1', ...
   {'DevOfDataUndefd','DataTmpUndefdAndEvlnInProgs','DevOfDataNotWithinRngAllwd','DataCalcdWithDevDefd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'DevOfDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'RFKEY', ...
   {'Undefd','NORFKEY','LLT','ELUT','HLUT','LLUT','LRLU','SLUT','EHLUT','ELLUT','HLLUT','LRLUT','LRHLU','LRELU','LRLLU'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'RemVentSts', ...
   {'NoReq','EgyReq','ClimaOn'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SeatHeatDurgClimaEnad', ...
   {'SeatHeatOff','SeatDrvOn','SeatPassOn','SeatDrvrAndPass','SeatLeftRearOn','SeatRightRearOn'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'SeatHeatOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SnsrSts', ...
   {'Ok','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'Ok', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'StartDevice', ...
   {'Undefd','StrtWithTwoDir','StrtWithOneDir','StrtBtn','NoPhyDev'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'StrtRemSts1', ...
   {'Idle','Strtg','Actv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TSpReq', ...
   {'idle','lo','normal','hi'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TelmSeatClimaLvl', ...
   {'off','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TelmSeatClimaLvlExsrc', ...
   {'NoReq','off','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UnLckCoolActvLvl', ...
   {'NoReq','CoolForFrnt','CoolForFrntAndRear'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UnLckHeatActvLvl', ...
   {'NoReq','HeatForFrnt','HeatForFrntAndRear'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WarnLvl', ...
   {'WarnLvlMsg_Off','WarnLvlMsg_Lv1','WarnLvlMsg_Lv2','WarnLvlMsg_Lv3','WarnLvlMsg_Lv4_1','WarnLvlMsg_Lv4_2','WarnLvlMsg_Lv4_3','WarnLvlMsg_Reserved'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'WarnLvlMsg_Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'WinAndRoofAndCurtPosnTyp', ...
   {'PosnUkwn','ClsFull','PercOpen4','PercOpen8','PercOpen12','PercOpen16','PercOpen20','PercOpen24','PercOpen28','PercOpen32','PercOpen36','PercOpen40','PercOpen44','PercOpen48','PercOpen52','PercOpen56','PercOpen60','PercOpen64','PercOpen68','PercOpen72','PercOpen76','PercOpen80','PercOpen84','PercOpen88','PercOpen92','PercOpen96','OpenFull','Resd1','Resd2','Resd3','Resd4','Movg'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31], ...
   'DefaultValue', 'PosnUkwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

