Simulink.defineIntEnumType( 'AACAirClngErrSts', ...
   {'NoErr','Err','ShortCircuit','OpenCircuit','Resd1','Resd2','Resd3','Resd4'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AACAirClngSts', ...
   {'AACOff','AACOn','Sleep','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'AACOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ActrDefrstSts', ...
   {'Off','On','Limited','NotAvailable','TmrOff','AutoCdn'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of ActrDefrstSts.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ActrReq', ...
   {'Off','On','AutOn'}, ...
   [0 1 2], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirCdnrSetg', ...
   {'Normal','ECO','Reserved1'}, ...
   [0 1 2], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirDirModReq', ...
   {'Normal','Focus','Avoid','Customize'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirPtcModeReq', ...
   {'Normal','AC_PreheatingLimitFrequency','DC_Preheating','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AmntSnsr', ...
   {'Amnt','InitValue','Error'}, ...
   [0 14 15], ...
   'DefaultValue', 'Amnt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'BatteryReq', ...
   {'Default','Discharging','Finished','Resd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'BltLockSt1', ...
   {'Unlock','Lock'}, ...
   [0 1], ...
   'DefaultValue', 'Unlock', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'BookChargeSetResponse', ...
   {'Default','Success','Cancelled','Fail'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarModSts1', ...
   {'CarModNorm','CarModTrnsp','CarModFcy','CarModCrash','CarModDyno'}, ...
   [0 1 2 3 5], ...
   'DefaultValue', 'CarModNorm', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ChSet', ...
   {'Idle','Channel1','Channel2','Channel3','Channel4','Channel5','Channel6','Channel7'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CloseOpen', ...
   {'Close','Open'}, ...
   [0 1], ...
   'DefaultValue', 'Close', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CmpmtAirPmLvl', ...
   {'Level1','Level2','Level3','Level4','Level5','Level6','Reserved','Invalid'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Level1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of CmpmtAirPmLvl.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtCoolgSts', ...
   {'OffNoReq','OffByEvaprTLo','OffByPLo','OffByAmbTOutOfRng','OffBySysFailr','OffByLoadCut','OnWithBattCoolg','On','OnWithRefrigerator','OnWithRefrigeratorAndBattCoolg'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'OffNoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CoolgReqForDisp', ...
   {'NoReq','LoReq','HiReq'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CptEquid', ...
   {'Equid','NotEquid'}, ...
   [0 1], ...
   'DefaultValue', 'Equid', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DataQf', ...
   {'NotOk','Ok'}, ...
   [0 1], ...
   'DefaultValue', 'NotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DcDcActvd', ...
   {'NoConversionToLVSide','ConversionToLVSide'}, ...
   [0 1], ...
   'DefaultValue', 'NoConversionToLVSide', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DeiceReq', ...
   {'NoReq','DeiceChecking','Deicing','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DevErrSts2', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DirMod', ...
   {'NotVld1','GNSS','MapMatch','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NotVld1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DoorSts2', ...
   {'Ukwn','Opend','Clsd'}, ...
   [0 1 2], ...
   'DefaultValue', 'Ukwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DrvModReqType1', ...
   {'Undefd','DrvMod1','DrvMod2','DrvMod3','DrvMod4','DrvMod5','DrvMod6','DrvMod7','DrvMod8','DrvMod9','DrvMod10','DrvMod11','DrvMod12','DrvMod13','DrvMod14','Err'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Undefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'EngSt1', ...
   {'Ini','Awake','Rdy','PreStrtg','StrtgInProgs','RunngRunng','RunngStb','RunngStrtgInProgs','RunngRemStrtd','AftRun'}, ...
   [0 1 2 3 4 5 6 7 8 9], ...
   'DefaultValue', 'Ini', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Err1', ...
   {'NoErr','Err'}, ...
   [0 1], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ErsCmd', ...
   {'ErsCmdNotSet','ErsCmdOn','ErsCmdOff'}, ...
   [0 1 2], ...
   'DefaultValue', 'ErsCmdNotSet', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FanErr', ...
   {'Noerr','Speedunstable','Poorcontact','Brokenline'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Noerr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of FanErr.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Flg1', ...
   {'Rst','Set'}, ...
   [0 1], ...
   'DefaultValue', 'Rst', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'FltEgyCns1', ...
   {'NoFlt','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'NoFlt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtCoolgReq', ...
   {'Off','Auto'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiFragraLvlReq', ...
   {'LvlOff','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'LvlOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'HmiHvacFanLvl', ...
   {'Off','LvlMan1','LvlMan2','LvlMan3','LvlMan4','LvlMan5','LvlMan6','LvlMan7','LvlMan8','LvlMan9','LvlAutMinusMinus','LvlAutMinus','LvlAutNorm','LvlAutPlus','LvlAutPlusPlus','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiPM25PopUpResp', ...
   {'Idle','Confirm','Cancel','Timeout'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvPwrEgyPrio', ...
   {'Standby','Dischrgning','Chrgning','ClimaWithAc','ClimaWithoutAc','RemoteClimatisaiton'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'Standby', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'IdPen', ...
   {'ProfUkwn','Prof1','Prof2','Prof3','Prof4','Prof5','Prof6','Prof7','Prof8','Prof9','Prof10','Prof11','Prof12','Prof13','Resd14','ProfAll'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'ProfUkwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LiOperMod', ...
   {'Night','Day','Twli','Tnl'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Night', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LockSt3', ...
   {'LockUndefd','LockUnlckd','LockTrUnlckd','LockLockd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'LockUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LockTrigSrc2', ...
   {'NoTrigSrc','KeyRem','Keyls','IntrSwt','SpdAut','TmrAut','Slam','Telm','Crash','Apprch','OutsOth','InsOth'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11], ...
   'DefaultValue', 'NoTrigSrc', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NoReqOnOff', ...
   {'Norequest','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'Norequest', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'NoYes1', ...
   {'No','Yes'}, ...
   [0 1], ...
   'DefaultValue', 'No', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of NoYes1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OccptPresSt1', ...
   {'Undefd1','OccptNotPrsnt','OccptPrsnt','Undefd2'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Undefd1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OkNotOk', ...
   {'NotOk','Ok'}, ...
   [0 1], ...
   'DefaultValue', 'NotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnBdChrgrHndlSts1', ...
   {'Disconnected','ConnectedWithoutPower','PowerAvailableButNotActivated','ConnectedWithPower','DischargeConnectwithoutpowerincar','DischargeConnectwithoutpoweroutcar','DischargeConnectwithpowerincar','DischargeConnectwithpoweroutcar','Init','Fault','NotCompleteConnnected','Reserved0','Reserved1','Reserved2'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13], ...
   'DefaultValue', 'Disconnected', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnBdChrgrSts1', ...
   {'Disconnected','ConnectedWithoutPower','PowerAvailableButNotActivated','ConnectedWithPower','DischargeConnectwithoutpowerincar','DischargeConnectwithoutpoweroutcar','DischargeConnectwithpowerincar','DischargeConnectwithpoweroutcar','Init','Fault','NotCompleteConnected','Reserved0','Reserved1','Reserved2'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13], ...
   'DefaultValue', 'Disconnected', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOffCrit1', ...
   {'NotVld1','Off','On','NotVld2'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NotVld1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of OnOffCrit1.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOffNoReq', ...
   {'NoReq','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OpenClsGlbCmd', ...
   {'Idle','GlobalOpenWindow','GlobalCloseWindowAndSunroof','GlobalCloseWindow','GlobalStop','Resd1','Resd2','Resd3'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenConcSnsrElecErr', ...
   {'NoErr','ShortToGrondOrOpenCircuit','ShortToBatt','Rsvd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyAvlSts', ...
   {'Off','Diffuse','NasalCannula','Error','None','PwrLo','BattleLo','TmrOvr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygengenrErrInfo', ...
   {'Normal','HumidifierErr','SolnVlvErr','DryerErr','FilErr','RadrErr','AirCmprErr','Rsvd'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PatSeld', ...
   {'NoSeld','RefrshPatSeld','ParentchildPatSeld','Restpatseld','RomanticPatseld','StrangerPatseld','TheaterPatseld','PetPatseld','BiochalPatseld','CarWashPatseld','EcoPatseld','KingPatseld','CustomizationPatseld','MeetingPatseld','CombatCockPatseld'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14], ...
   'DefaultValue', 'NoSeld', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PmSnsrErrSts', ...
   {'NoError','ShortToGroundOrOpenCircuit','ShortToBatt','Resvd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoError', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PmSnsrSts', ...
   {'Initial','Collecting','Complete','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Initial', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PosnSts', ...
   {'Idle','ClsFullAndLock','ClsFull','PercOpen10','PercOpen20','PercOpen30','PercOpen40','PercOpen50','PercOpen60','PercOpen70','PercOpen80','PercOpen90','OpenFull','OpenFullAndLock','Resd1','Resd2'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qf1', ...
   {'DevOfDataUndefd','DataTmpUndefdAndEvlnInProgs','DevOfDataNotWithinRngAllwd','DataCalcdWithDevDefd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'DevOfDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qly2', ...
   {'Flt','NoInfo','Vld'}, ...
   [0 1 2], ...
   'DefaultValue', 'Flt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ReqSts1', ...
   {'NotReqd','Reqd'}, ...
   [0 1], ...
   'DefaultValue', 'NotReqd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'RuranACModeSet', ...
   {'Classic','ClodDew','MorningBreeze','WarnSun','Fireplace','Reserved','Reserved1','Reserved2'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Classic', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SeatClimaLvl', ...
   {'Off','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SeatHeatDurgClimaEnad', ...
   {'SeatHeatOff','SeatDrvOn','SeatPassOn','SeatDrvrAndPass','SeatLeftRearOn','SeatRightRearOn'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'SeatHeatOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SnsrSts', ...
   {'Ok','Flt'}, ...
   [0 1], ...
   'DefaultValue', 'Ok', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Status1', ...
   {'Inactive','ActiveForManualMode','ActiveForAutoMode','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Inactive', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'StrtRemSts1', ...
   {'Idle','Strtg','Actv'}, ...
   [0 1 2], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SunSnsrQf', ...
   {'SnsrDataUndefd','Resd','SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SnsrDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'Description', sprintf('Type definition of SunSnsrQf.'), ... 
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TelmThermoTankReq', ...
   {'Req_NoReq','Req_off','Req_Coolg','Req_Heatlg'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Req_NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'TempErr', ...
   {'Normal','OverTemp','UnderTemp','Invalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Normal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ThmgtLevel', ...
   {'NoRequest','Boost1','Boost2','Spare'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoRequest', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'UsgModSts1', ...
   {'UsgModAbdnd','UsgModInActv','UsgModCnvinc','UsgModActv','UsgModDrvg'}, ...
   [0 1 2 11 13], ...
   'DefaultValue', 'UsgModAbdnd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VentnActr01BlckInd', ...
   {'Disabled','Enabled','Reserved','Signalinvalid'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Disabled', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VlvCalibSts', ...
   {'NotInitialized','Initializing','Initialized','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NotInitialized', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VlvSpdLvlReq', ...
   {'Invalid','Level1','Level2','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Invalid', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WarnLvl', ...
   {'WarnLvlMsg_Off','WarnLvlMsg_Lv1','WarnLvlMsg_Lv2','WarnLvlMsg_Lv3','WarnLvlMsg_Lv4_1','WarnLvlMsg_Lv4_2','WarnLvlMsg_Lv4_3','WarnLvlMsg_Reserved'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'WarnLvlMsg_Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'WasRespLevel', ...
   {'Default','Level1','Level2','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Default', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WhlMotSysCluReq', ...
   {'NoReq','ReqOpen','ReqClsd','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'WinAndRoofAndCurtPosnTyp', ...
   {'PosnUkwn','ClsFull','PercOpen4','PercOpen8','PercOpen12','PercOpen16','PercOpen20','PercOpen24','PercOpen28','PercOpen32','PercOpen36','PercOpen40','PercOpen44','PercOpen48','PercOpen52','PercOpen56','PercOpen60','PercOpen64','PercOpen68','PercOpen72','PercOpen76','PercOpen80','PercOpen84','PercOpen88','PercOpen92','PercOpen96','OpenFull','Resd1','Resd2','Resd3','Resd4','Movg'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31], ...
   'DefaultValue', 'PosnUkwn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WipgSpdInfo', ...
   {'Off','IntlLo','IntlHi','WipgSpd4045','WipgSpd4650','WipgSpd5155','WipgSpd5660','WiprErr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WtrDepLev', ...
   {'NoReq','Level1','Level2','Level3','Level4','Level5','Level6','Level7','Level8','Level9','Level10','Level11','Level12','Level13','Level14','Level15'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

