Simulink.defineIntEnumType( 'AACAirClngSts', ...
   {'AACOff','AACOn','Sleep','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'AACOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'AirMtrlSnsrReq', ...
   {'SNA','Off','On','Calibrate'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SNA', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'ClimaManModCmftSts', ...
   {'None','AvoidColdWind','AvoidHotWind','Resd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaOffReq', ...
   {'NoReq','SecRowOffReq','TrdRowOffReq','ClimaOff'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaStStrtUp', ...
   {'Comfort','Cooldown','Heatup'}, ...
   [0 1 2], ...
   'DefaultValue', 'Comfort', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaSts', ...
   {'Start','Finish'}, ...
   [0 1], ...
   'DefaultValue', 'Start', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaWarn', ...
   {'NoWarn','FuLo','BattLo','FuAndBattLo','TLo','THi','Error','HVError','ActvnLimd'}, ...
   [0 1 2 3 4 5 6 7 8], ...
   'DefaultValue', 'NoWarn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptSts', ...
   {'NoRequest','CoolingRequest','HeatingRequest','CoolingAndHeatingRequest','PostHeating'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoRequest', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CoolgStsForDisp', ...
   {'NoCoolgActv','CoolgLvlStrtd1','CoolgLvlStrtd2','Resd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoCoolgActv', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'DataQf', ...
   {'NotOk','Ok'}, ...
   [0 1], ...
   'DefaultValue', 'NotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'EngRunngReq', ...
   {'Dft','StopInhb','RunReq','Resd'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Dft', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Err1', ...
   {'NoErr','Err'}, ...
   [0 1], ...
   'DefaultValue', 'NoErr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ExtVentToastFrmClimaSts', ...
   {'NoToast','StartTrue','StartFalse','LowPower','Exit'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'NoToast', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Flg1', ...
   {'Rst','Set'}, ...
   [0 1], ...
   'DefaultValue', 'Rst', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'GenQf1', ...
   {'UndefindDataAccur','TmpUndefdData','DataAccurNotWithinSpcn','AccurData'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'UndefindDataAccur', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiCmptmtAirDistbnFrnt', ...
   {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Flr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HmiHvacFanLvl', ...
   {'Off','LvlMan1','LvlMan2','LvlMan3','LvlMan4','LvlMan5','LvlMan6','LvlMan7','LvlMan8','LvlMan9','LvlAutMinusMinus','LvlAutMinus','LvlAutNorm','LvlAutPlus','LvlAutPlusPlus','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'HvacTIfQf', ...
   {'SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1], ...
   'DefaultValue', 'SnsrDataNotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'IntPmHiPopUp', ...
   {'NoReq','ClimaOn','ClimaOnAndWinClsd','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'LvlOfClimaCmft', ...
   {'Off','Lvl1','Lvl2','Lvl3','Lvl4','Lvl5','Lvl6','Lvl7'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ModeCmptHp', ...
   {'vent','cool','hot','cool_hot','cool_defog','hot_defog','cool_hot_defog','reserved'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'vent', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OkNotOk', ...
   {'NotOk','Ok'}, ...
   [0 1], ...
   'DefaultValue', 'NotOk', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOff1', ...
   {'Off','On'}, ...
   [0 1], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OnOffNoReq', ...
   {'NoReq','On','Off'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyAvlSts', ...
   {'Off','Diffuse','NasalCannula','Error','None','PwrLo','BattleLo','TmrOvr'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyPopUpReq', ...
   {'NoReq','DoorNotCls','WinNotCls','DoorAndWinNotCls','OpenFaild','ActrFlt','LvPwrLo','HvPwrLo','RemStsCarryOn','AutOxygenSplyActv','HvSocLow','Rsvd1','Rsvd2','Rsvd3','Rsvd4','Rsvd5'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyReq', ...
   {'NoReq','Off','Diffuse','NasalCannula'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'OxygenSplyVoiceFb', ...
   {'Idle','OpenSucccess','ClsSucess','OpenFaild_LvPwrFlt','OpenFaild_HvPwrFlt','OpenFaild_OGMFlt','ClsFaild','Rsvd'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Idle', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PmSnsrSts', ...
   {'Initial','Collecting','Complete','Error'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Initial', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PopUpReq', ...
   {'NoReq','AvoidColdWind','AvoidHotWind','ReAvoidColdWind','ReAvoidHotWind','Resd1','Resd2','Resd3'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PreClngNotif', ...
   {'NoReq','NoWarn','Done','Err','Intrpt','Spare1','Spare2','Spare3'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ReqSts1', ...
   {'NotReqd','Reqd'}, ...
   [0 1], ...
   'DefaultValue', 'NotReqd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'TelmThermoTankReq', ...
   {'Req_NoReq','Req_off','Req_Coolg','Req_Heatlg'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Req_NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'UnknowLvl', ...
   {'Unknow','Lvl1','Lvl2','Lvl3','Lvl4','Rsvd1','Rsvd2','Rsvd3'}, ...
   [0 1 2 3 4 5 6 7], ...
   'DefaultValue', 'Unknow', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'VehMktGlb', ...
   {'SNA','World','Europe','NorthAmerica','SouthAmerica','MiddleEastAfrica','SouthEastAsia','Pacific','Russia','Korea','China','Taiwan','Japan','India','Israel','Turkey','Spare'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16], ...
   'DefaultValue', 'SNA', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Warn2', ...
   {'NoWarn','Warn'}, ...
   [0 1], ...
   'DefaultValue', 'NoWarn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'WhlMotSysCluReq', ...
   {'NoReq','ReqOpen','ReqClsd','Reserved'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

