Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CarCfgForSeatHeatgCal1', ...
   {'NoVal','Cal1','Cal2','Cal3','Cal4','Cal5','Cal6','Cal7','Cal8','Cal9','Cal10'}, ...
   [0 1 2 3 4 5 6 7 8 9 10], ...
   'DefaultValue', 'NoVal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'ClimaCfgForAmntOfSeat1', ...
   {'Seat5','Seat7','Seat4','Seat3','Seat1','Seat2','Seat6'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'Seat5', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'SeatClimaLvl', ...
   {'Off','Lvl1','Lvl2','Lvl3'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

