Simulink.defineIntEnumType( 'CCMLifeCycleModeGroup', ...
   {'Normal','StartUp'}, ...
   [0 1], ...
   'DefaultValue', 'StartUp', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'ClimaCfgForCmptmtSnsr1', ...
   {'WoCmptmtSnsr','AirTWithFan','IntrMtrlT'}, ...
   [0 1 2], ...
   'DefaultValue', 'WoCmptmtSnsr', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'CmptmtTFrntQf', ...
   {'SnsrDataUndefd','FanNotRunning','SnsrDataNotOk','SnsrDataOk'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SnsrDataUndefd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Flg1', ...
   {'Rst','Set'}, ...
   [0 1], ...
   'DefaultValue', 'Rst', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'PrkgClimaActv', ...
   {'Off','PreCdngActv','PostCdngActv','BlwAftRunActv'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

Simulink.defineIntEnumType( 'Qly2', ...
   {'Flt','NoInfo','Vld'}, ...
   [0 1 2], ...
   'DefaultValue', 'Flt', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', true);

