%% 删掉输出端口，并将所有输出信号接地

%% 解析信号
createModSig(gcb, ...
    'autosarMode', 'prefixHalf', ...
    'prefixName', 'CcmIF', ...
    'isEnableIn', false, ...
    'isEnableOut', true, ...
    'resoveValue',true)

createModSig(gcb, ...
    'isEnableIn', true, ...
    'isEnableOut', false,...
    'resoveValue',true)

%% 解析输出信号
[outputFile, sigTable] = createSlddSigGee(bdroot, ...
'autosarMode', 'prefixHalf', ...
'ignoreInput', true,...
'isUseSubModel', true);

%% 导入解析信号
outputFile = "SdbRxSigProc_Element_Management_AddPort.xlsm"
findSlddLoadGee(outputFile, ...
    'StorageClassIn', 'Auto', ...
    'StorageClassOut', 'Global');  % Global,Auto

