
try
    Simulink.defineIntEnumType('CCMLifeCycleModeGroup',...
    {'StartUp','Normal'}, ...
    [1,0], ...
    'DefaultValue','StartUp', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',false);
catch e
end
try
    Simulink.defineIntEnumType('ClimaCfgForCarTyp1',...
    {'CarTyp0','CarTyp1','CarTyp2'}, ...
    [0,1,2], ...
    'DefaultValue','CarTyp0', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('ClimaCfgForHeatrTyp1',...
    {'NoHeatr','FuHeatr','HvHeatr','PrkgHeatrElec','Hv12V'}, ...
    [1,2,3,4,128], ...
    'DefaultValue','NoHeatr', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('MaxGear',...
    {'Max4Gear','Max5Gear','Max6Gear','Max7Gear','Max8Gear','Max9Gear'}, ...
    [0,1,2,3,4,5], ...
    'DefaultValue','Max4Gear', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('ClimaCfgForNrOfFanLvlSetg1',...
    {'NrOfFanLvlSetg1','NrOfFanLvlSetg2','NrOfFanLvlSetg3','NrOfFanLvlSetg4'}, ...
    [0,1,2,3], ...
    'DefaultValue','NrOfFanLvlSetg1', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('ClimaCfgForNrOfTSetg1',...
    {'NrOfTSetg1','NrOfTSetg2','NrOfTSetg3','NrOfTSetg4'}, ...
    [0,1,2,3], ...
    'DefaultValue','NrOfTSetg1', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('ClimaStStrtUp',...
    {'Comfort','Cooldown','Heatup'}, ...
    [0,1,2], ...
    'DefaultValue','Comfort', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('HmiCmptmtAirDistbnFrnt',...
    {'Flr','Vent','Defrst','FlrDefrst','FlrVent','VentDefrst','FlrVentDefrst','Aut'}, ...
    [0,1,2,3,4,5,6,7], ...
    'DefaultValue','Flr', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('PreClngSts',...
    {'Off','UniqueActv','WithPreCdngActv'}, ...
    [0,1,2], ...
    'DefaultValue','Off', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('PrkgClimaActv',...
    {'Off','PreCdngActv','PostCdngActv','BlwAftRunActv'}, ...
    [0,1,2,3], ...
    'DefaultValue','Off', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('ClimaCfgForActrModVrnt1',...
    {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn'}, ...
    [0,1,2,3], ...
    'DefaultValue','FlapInd', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('ClimaCfgForActrModVrnt2',...
    {'FlapInd','VentFlrCmn','FlrVentCmn','FlrVentDefrCmn','VentFlrCmnAdjmt','FlrVentCmnAdjmt','WithoutFlap'}, ...
    [0,1,2,3,4,5,6], ...
    'DefaultValue','FlapInd', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end
try
    Simulink.defineIntEnumType('HvacFanLvlFb',...
    {'Off','Min','Lvl1','Lvl2','Lvl3','Lvl4','Lvl5','Lvl6','Lvl7','Max'}, ...
    [0,1,2,3,4,5,6,7,8,9], ...
    'DefaultValue','Off', ...
    'HeaderFile','Rte_Type.h', ...
    'DataScope','Auto', ...
    'StorageType','uint8', ...
    'AddClassNameToEnumNames',true);
catch e
end