% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Sep-2023 20:02:45
%  MATLAB version: 9.13.0.2193358 (R2022b) Update 5
% -------------------------------------------------------------------
                                                 

AutCtrldFlowReqForRowFirstLeAtFlrForStorg = AUTOSAR4.Signal;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.CoderInfo.StorageClass = ...
  'Custom';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.CoderInfo.Identifier = '';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.CoderInfo.Alignment = -1;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.CoderInfo.CustomAttributes.Owner = '';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.CoderInfo.CustomAttributes.IsReusable = false;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.Description = '-';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.DataType = 'AirFlow30';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.Min = 0;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.Max = 1000;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.DocUnits = 'KgPerHour';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.Dimensions = -1;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.DimensionsMode = 'auto';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.Complexity = 'auto';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.SampleTime = -1;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.InitialValue = '0';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.GenericProperty = [];
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.DoubleProperty = 0;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.Int32Property = int32(0);
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.LogicalProperty = false;
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.StringProperty = '';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.OnOffStringProperty = 'off';
AutCtrldFlowReqForRowFirstLeAtFlrForStorg.ColorStringProperty = 'red';

FlowLimActvManModForStorg0 = AUTOSAR4.Signal;
FlowLimActvManModForStorg0.CoderInfo.StorageClass = 'Custom';
FlowLimActvManModForStorg0.CoderInfo.Identifier = '';
FlowLimActvManModForStorg0.CoderInfo.Alignment = -1;
FlowLimActvManModForStorg0.CoderInfo.CustomStorageClass = 'GlobalDisp';
FlowLimActvManModForStorg0.CoderInfo.CustomAttributes.HeaderFile = '';
FlowLimActvManModForStorg0.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowLimActvManModForStorg0.CoderInfo.CustomAttributes.Owner = '';
FlowLimActvManModForStorg0.CoderInfo.CustomAttributes.IsReusable = false;
FlowLimActvManModForStorg0.Description = '-';
FlowLimActvManModForStorg0.DataType = 'boolean';
FlowLimActvManModForStorg0.Min = 0;
FlowLimActvManModForStorg0.Max = 1;
FlowLimActvManModForStorg0.DocUnits = 'NoUnit';
FlowLimActvManModForStorg0.Dimensions = -1;
FlowLimActvManModForStorg0.DimensionsMode = 'auto';
FlowLimActvManModForStorg0.Complexity = 'auto';
FlowLimActvManModForStorg0.SampleTime = -1;
FlowLimActvManModForStorg0.InitialValue = 'false';
FlowLimActvManModForStorg0.GenericProperty = [];
FlowLimActvManModForStorg0.DoubleProperty = 0;
FlowLimActvManModForStorg0.Int32Property = int32(0);
FlowLimActvManModForStorg0.LogicalProperty = false;
FlowLimActvManModForStorg0.StringProperty = '';
FlowLimActvManModForStorg0.OnOffStringProperty = 'off';
FlowLimActvManModForStorg0.ColorStringProperty = 'red';

FlowLimActvManModForStorg1 = AUTOSAR4.Signal;
FlowLimActvManModForStorg1.CoderInfo.StorageClass = 'Custom';
FlowLimActvManModForStorg1.CoderInfo.Identifier = '';
FlowLimActvManModForStorg1.CoderInfo.Alignment = -1;
FlowLimActvManModForStorg1.CoderInfo.CustomStorageClass = 'GlobalDisp';
FlowLimActvManModForStorg1.CoderInfo.CustomAttributes.HeaderFile = '';
FlowLimActvManModForStorg1.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowLimActvManModForStorg1.CoderInfo.CustomAttributes.Owner = '';
FlowLimActvManModForStorg1.CoderInfo.CustomAttributes.IsReusable = false;
FlowLimActvManModForStorg1.Description = '-';
FlowLimActvManModForStorg1.DataType = 'boolean';
FlowLimActvManModForStorg1.Min = 0;
FlowLimActvManModForStorg1.Max = 1;
FlowLimActvManModForStorg1.DocUnits = 'NoUnit';
FlowLimActvManModForStorg1.Dimensions = -1;
FlowLimActvManModForStorg1.DimensionsMode = 'auto';
FlowLimActvManModForStorg1.Complexity = 'auto';
FlowLimActvManModForStorg1.SampleTime = -1;
FlowLimActvManModForStorg1.InitialValue = 'false';
FlowLimActvManModForStorg1.GenericProperty = [];
FlowLimActvManModForStorg1.DoubleProperty = 0;
FlowLimActvManModForStorg1.Int32Property = int32(0);
FlowLimActvManModForStorg1.LogicalProperty = false;
FlowLimActvManModForStorg1.StringProperty = '';
FlowLimActvManModForStorg1.OnOffStringProperty = 'off';
FlowLimActvManModForStorg1.ColorStringProperty = 'red';

FlowLimActvManModForStorg2 = AUTOSAR4.Signal;
FlowLimActvManModForStorg2.CoderInfo.StorageClass = 'Custom';
FlowLimActvManModForStorg2.CoderInfo.Identifier = '';
FlowLimActvManModForStorg2.CoderInfo.Alignment = -1;
FlowLimActvManModForStorg2.CoderInfo.CustomStorageClass = 'GlobalDisp';
FlowLimActvManModForStorg2.CoderInfo.CustomAttributes.HeaderFile = '';
FlowLimActvManModForStorg2.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowLimActvManModForStorg2.CoderInfo.CustomAttributes.Owner = '';
FlowLimActvManModForStorg2.CoderInfo.CustomAttributes.IsReusable = false;
FlowLimActvManModForStorg2.Description = '-';
FlowLimActvManModForStorg2.DataType = 'boolean';
FlowLimActvManModForStorg2.Min = 0;
FlowLimActvManModForStorg2.Max = 1;
FlowLimActvManModForStorg2.DocUnits = 'NoUnit';
FlowLimActvManModForStorg2.Dimensions = -1;
FlowLimActvManModForStorg2.DimensionsMode = 'auto';
FlowLimActvManModForStorg2.Complexity = 'auto';
FlowLimActvManModForStorg2.SampleTime = -1;
FlowLimActvManModForStorg2.InitialValue = 'false';
FlowLimActvManModForStorg2.GenericProperty = [];
FlowLimActvManModForStorg2.DoubleProperty = 0;
FlowLimActvManModForStorg2.Int32Property = int32(0);
FlowLimActvManModForStorg2.LogicalProperty = false;
FlowLimActvManModForStorg2.StringProperty = '';
FlowLimActvManModForStorg2.OnOffStringProperty = 'off';
FlowLimActvManModForStorg2.ColorStringProperty = 'red';

FlowLimActvManModForStorg3 = AUTOSAR4.Signal;
FlowLimActvManModForStorg3.CoderInfo.StorageClass = 'Custom';
FlowLimActvManModForStorg3.CoderInfo.Identifier = '';
FlowLimActvManModForStorg3.CoderInfo.Alignment = -1;
FlowLimActvManModForStorg3.CoderInfo.CustomStorageClass = 'GlobalDisp';
FlowLimActvManModForStorg3.CoderInfo.CustomAttributes.HeaderFile = '';
FlowLimActvManModForStorg3.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowLimActvManModForStorg3.CoderInfo.CustomAttributes.Owner = '';
FlowLimActvManModForStorg3.CoderInfo.CustomAttributes.IsReusable = false;
FlowLimActvManModForStorg3.Description = '-';
FlowLimActvManModForStorg3.DataType = 'boolean';
FlowLimActvManModForStorg3.Min = 0;
FlowLimActvManModForStorg3.Max = 1;
FlowLimActvManModForStorg3.DocUnits = 'NoUnit';
FlowLimActvManModForStorg3.Dimensions = -1;
FlowLimActvManModForStorg3.DimensionsMode = 'auto';
FlowLimActvManModForStorg3.Complexity = 'auto';
FlowLimActvManModForStorg3.SampleTime = -1;
FlowLimActvManModForStorg3.InitialValue = 'false';
FlowLimActvManModForStorg3.GenericProperty = [];
FlowLimActvManModForStorg3.DoubleProperty = 0;
FlowLimActvManModForStorg3.Int32Property = int32(0);
FlowLimActvManModForStorg3.LogicalProperty = false;
FlowLimActvManModForStorg3.StringProperty = '';
FlowLimActvManModForStorg3.OnOffStringProperty = 'off';
FlowLimActvManModForStorg3.ColorStringProperty = 'red';

FlowLimActvManModForStorg4 = AUTOSAR4.Signal;
FlowLimActvManModForStorg4.CoderInfo.StorageClass = 'Custom';
FlowLimActvManModForStorg4.CoderInfo.Identifier = '';
FlowLimActvManModForStorg4.CoderInfo.Alignment = -1;
FlowLimActvManModForStorg4.CoderInfo.CustomStorageClass = 'GlobalDisp';
FlowLimActvManModForStorg4.CoderInfo.CustomAttributes.HeaderFile = '';
FlowLimActvManModForStorg4.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowLimActvManModForStorg4.CoderInfo.CustomAttributes.Owner = '';
FlowLimActvManModForStorg4.CoderInfo.CustomAttributes.IsReusable = false;
FlowLimActvManModForStorg4.Description = '-';
FlowLimActvManModForStorg4.DataType = 'boolean';
FlowLimActvManModForStorg4.Min = 0;
FlowLimActvManModForStorg4.Max = 1;
FlowLimActvManModForStorg4.DocUnits = 'NoUnit';
FlowLimActvManModForStorg4.Dimensions = -1;
FlowLimActvManModForStorg4.DimensionsMode = 'auto';
FlowLimActvManModForStorg4.Complexity = 'auto';
FlowLimActvManModForStorg4.SampleTime = -1;
FlowLimActvManModForStorg4.InitialValue = 'false';
FlowLimActvManModForStorg4.GenericProperty = [];
FlowLimActvManModForStorg4.DoubleProperty = 0;
FlowLimActvManModForStorg4.Int32Property = int32(0);
FlowLimActvManModForStorg4.LogicalProperty = false;
FlowLimActvManModForStorg4.StringProperty = '';
FlowLimActvManModForStorg4.OnOffStringProperty = 'off';
FlowLimActvManModForStorg4.ColorStringProperty = 'red';

FlowReqForRowFirstAtFlrLeCnvincForStorg = AUTOSAR4.Signal;
FlowReqForRowFirstAtFlrLeCnvincForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqForRowFirstAtFlrLeCnvincForStorg.CoderInfo.Identifier = '';
FlowReqForRowFirstAtFlrLeCnvincForStorg.CoderInfo.Alignment = -1;
FlowReqForRowFirstAtFlrLeCnvincForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqForRowFirstAtFlrLeCnvincForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqForRowFirstAtFlrLeCnvincForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqForRowFirstAtFlrLeCnvincForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqForRowFirstAtFlrLeCnvincForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqForRowFirstAtFlrLeCnvincForStorg.Description = '-';
FlowReqForRowFirstAtFlrLeCnvincForStorg.DataType = 'AirFlow30';
FlowReqForRowFirstAtFlrLeCnvincForStorg.Min = 0;
FlowReqForRowFirstAtFlrLeCnvincForStorg.Max = 1000;
FlowReqForRowFirstAtFlrLeCnvincForStorg.DocUnits = 'KgPerHour';
FlowReqForRowFirstAtFlrLeCnvincForStorg.Dimensions = -1;
FlowReqForRowFirstAtFlrLeCnvincForStorg.DimensionsMode = 'auto';
FlowReqForRowFirstAtFlrLeCnvincForStorg.Complexity = 'auto';
FlowReqForRowFirstAtFlrLeCnvincForStorg.SampleTime = -1;
FlowReqForRowFirstAtFlrLeCnvincForStorg.InitialValue = '0';
FlowReqForRowFirstAtFlrLeCnvincForStorg.GenericProperty = [];
FlowReqForRowFirstAtFlrLeCnvincForStorg.DoubleProperty = 0;
FlowReqForRowFirstAtFlrLeCnvincForStorg.Int32Property = int32(0);
FlowReqForRowFirstAtFlrLeCnvincForStorg.LogicalProperty = false;
FlowReqForRowFirstAtFlrLeCnvincForStorg.StringProperty = '';
FlowReqForRowFirstAtFlrLeCnvincForStorg.OnOffStringProperty = 'off';
FlowReqForRowFirstAtFlrLeCnvincForStorg.ColorStringProperty = 'red';

FlowReqForRowFirstAtFlrLeDurgHiForStorg = AUTOSAR4.Signal;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.CoderInfo.Identifier = '';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.CoderInfo.Alignment = -1;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.Description = '-';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.DataType = 'AirFlow30';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.Min = 0;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.Max = 1000;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.DocUnits = 'KgPerHour';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.Dimensions = -1;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.DimensionsMode = 'auto';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.Complexity = 'auto';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.SampleTime = -1;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.InitialValue = '0';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.GenericProperty = [];
FlowReqForRowFirstAtFlrLeDurgHiForStorg.DoubleProperty = 0;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.Int32Property = int32(0);
FlowReqForRowFirstAtFlrLeDurgHiForStorg.LogicalProperty = false;
FlowReqForRowFirstAtFlrLeDurgHiForStorg.StringProperty = '';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.OnOffStringProperty = 'off';
FlowReqForRowFirstAtFlrLeDurgHiForStorg.ColorStringProperty = 'red';

FlowReqForRowFirstAtFlrLeDurgLoForStorg = AUTOSAR4.Signal;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.CoderInfo.Identifier = '';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.CoderInfo.Alignment = -1;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.Description = '-';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.DataType = 'AirFlow30';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.Min = 0;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.Max = 1000;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.DocUnits = 'KgPerHour';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.Dimensions = -1;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.DimensionsMode = 'auto';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.Complexity = 'auto';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.SampleTime = -1;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.InitialValue = '0';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.GenericProperty = [];
FlowReqForRowFirstAtFlrLeDurgLoForStorg.DoubleProperty = 0;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.Int32Property = int32(0);
FlowReqForRowFirstAtFlrLeDurgLoForStorg.LogicalProperty = false;
FlowReqForRowFirstAtFlrLeDurgLoForStorg.StringProperty = '';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.OnOffStringProperty = 'off';
FlowReqForRowFirstAtFlrLeDurgLoForStorg.ColorStringProperty = 'red';

FlowReqForRowFirstAtFlrLeManFanActvForStorg = AUTOSAR4.Signal;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.CoderInfo.Identifier = '';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.CoderInfo.Alignment = -1;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.Description = '-';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.DataType = 'AirFlow30';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.Min = 0;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.Max = 1000;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.DocUnits = 'KgPerHour';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.Dimensions = -1;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.DimensionsMode = 'auto';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.Complexity = 'auto';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.SampleTime = -1;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.InitialValue = '0';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.GenericProperty = [];
FlowReqForRowFirstAtFlrLeManFanActvForStorg.DoubleProperty = 0;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.Int32Property = int32(0);
FlowReqForRowFirstAtFlrLeManFanActvForStorg.LogicalProperty = false;
FlowReqForRowFirstAtFlrLeManFanActvForStorg.StringProperty = '';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.OnOffStringProperty = 'off';
FlowReqForRowFirstAtFlrLeManFanActvForStorg.ColorStringProperty = 'red';

FlowReqForRowFirstAtFlrLeMaxDefrstForStorg = AUTOSAR4.Signal;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.CoderInfo.Identifier = '';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.CoderInfo.Alignment = -1;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.Description = '-';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.DataType = 'AirFlow30';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.Min = 0;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.Max = 1000;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.DocUnits = 'KgPerHour';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.Dimensions = -1;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.DimensionsMode = 'auto';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.Complexity = 'auto';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.SampleTime = -1;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.InitialValue = '0';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.GenericProperty = [];
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.DoubleProperty = 0;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.Int32Property = int32(0);
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.LogicalProperty = false;
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.StringProperty = '';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.OnOffStringProperty = 'off';
FlowReqForRowFirstAtFlrLeMaxDefrstForStorg.ColorStringProperty = 'red';

FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg = AUTOSAR4.Signal;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.CoderInfo.Identifier = '';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.CoderInfo.Alignment = -1;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.Description = '-';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.DataType = 'AirFlow30';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.Min = 0;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.Max = 1000;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.DocUnits = 'KgPerHour';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.Dimensions = -1;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.DimensionsMode = 'auto';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.Complexity = 'auto';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.SampleTime = -1;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.InitialValue = '0';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.GenericProperty = [];
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.DoubleProperty = 0;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.Int32Property = int32(0);
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.LogicalProperty = false;
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.StringProperty = '';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.OnOffStringProperty = ...
  'off';
FlowReqForRowFirstAtFlrLeMaxDefrstManForStorg.ColorStringProperty = ...
  'red';

FlowReqForRowFirstAtFlrLePreClngForStorg = AUTOSAR4.Signal;
FlowReqForRowFirstAtFlrLePreClngForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqForRowFirstAtFlrLePreClngForStorg.CoderInfo.Identifier = '';
FlowReqForRowFirstAtFlrLePreClngForStorg.CoderInfo.Alignment = -1;
FlowReqForRowFirstAtFlrLePreClngForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqForRowFirstAtFlrLePreClngForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqForRowFirstAtFlrLePreClngForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqForRowFirstAtFlrLePreClngForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqForRowFirstAtFlrLePreClngForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqForRowFirstAtFlrLePreClngForStorg.Description = '-';
FlowReqForRowFirstAtFlrLePreClngForStorg.DataType = 'AirFlow30';
FlowReqForRowFirstAtFlrLePreClngForStorg.Min = 0;
FlowReqForRowFirstAtFlrLePreClngForStorg.Max = 1000;
FlowReqForRowFirstAtFlrLePreClngForStorg.DocUnits = 'KgPerHour';
FlowReqForRowFirstAtFlrLePreClngForStorg.Dimensions = -1;
FlowReqForRowFirstAtFlrLePreClngForStorg.DimensionsMode = 'auto';
FlowReqForRowFirstAtFlrLePreClngForStorg.Complexity = 'auto';
FlowReqForRowFirstAtFlrLePreClngForStorg.SampleTime = -1;
FlowReqForRowFirstAtFlrLePreClngForStorg.InitialValue = '0';
FlowReqForRowFirstAtFlrLePreClngForStorg.GenericProperty = [];
FlowReqForRowFirstAtFlrLePreClngForStorg.DoubleProperty = 0;
FlowReqForRowFirstAtFlrLePreClngForStorg.Int32Property = int32(0);
FlowReqForRowFirstAtFlrLePreClngForStorg.LogicalProperty = false;
FlowReqForRowFirstAtFlrLePreClngForStorg.StringProperty = '';
FlowReqForRowFirstAtFlrLePreClngForStorg.OnOffStringProperty = 'off';
FlowReqForRowFirstAtFlrLePreClngForStorg.ColorStringProperty = 'red';

FlowReqForRowFirstAtFlrPwrAllwdLoForStorg = AUTOSAR4.Signal;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.CoderInfo.Identifier = '';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.CoderInfo.Alignment = -1;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.Description = '-';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.DataType = 'AirFlow30';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.Min = 0;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.Max = 1000;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.DocUnits = 'KgPerHour';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.Dimensions = -1;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.DimensionsMode = 'auto';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.Complexity = 'auto';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.SampleTime = -1;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.InitialValue = '0';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.GenericProperty = [];
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.DoubleProperty = 0;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.Int32Property = int32(0);
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.LogicalProperty = false;
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.StringProperty = '';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.OnOffStringProperty = 'off';
FlowReqForRowFirstAtFlrPwrAllwdLoForStorg.ColorStringProperty = 'red';

FlowReqScaForRowFirstAtFlrLeManDistbnForStorg = AUTOSAR4.Signal;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.CoderInfo.StorageClass = ...
  'Custom';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.CoderInfo.Identifier = '';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.CoderInfo.Alignment = -1;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.CoderInfo.CustomAttributes.Owner = '';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.CoderInfo.CustomAttributes.IsReusable = false;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.Description = '-';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.DataType = 'AirFlow30';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.Min = 0;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.Max = 1000;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.DocUnits = 'KgPerHour';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.Dimensions = -1;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.DimensionsMode = 'auto';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.Complexity = 'auto';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.SampleTime = -1;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.InitialValue = '0';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.GenericProperty = [];
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.DoubleProperty = 0;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.Int32Property = int32(0);
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.LogicalProperty = false;
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.StringProperty = '';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.OnOffStringProperty = ...
  'off';
FlowReqScaForRowFirstAtFlrLeManDistbnForStorg.ColorStringProperty = ...
  'red';

HvacAirMFlowReqMaxAvlManForStorg = AUTOSAR4.Signal;
HvacAirMFlowReqMaxAvlManForStorg.CoderInfo.StorageClass = 'Custom';
HvacAirMFlowReqMaxAvlManForStorg.CoderInfo.Identifier = '';
HvacAirMFlowReqMaxAvlManForStorg.CoderInfo.Alignment = -1;
HvacAirMFlowReqMaxAvlManForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
HvacAirMFlowReqMaxAvlManForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
HvacAirMFlowReqMaxAvlManForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
HvacAirMFlowReqMaxAvlManForStorg.CoderInfo.CustomAttributes.Owner = '';
HvacAirMFlowReqMaxAvlManForStorg.CoderInfo.CustomAttributes.IsReusable = false;
HvacAirMFlowReqMaxAvlManForStorg.Description = '-';
HvacAirMFlowReqMaxAvlManForStorg.DataType = 'AirFlow30';
HvacAirMFlowReqMaxAvlManForStorg.Min = 0;
HvacAirMFlowReqMaxAvlManForStorg.Max = 1000;
HvacAirMFlowReqMaxAvlManForStorg.DocUnits = 'KgPerHour';
HvacAirMFlowReqMaxAvlManForStorg.Dimensions = -1;
HvacAirMFlowReqMaxAvlManForStorg.DimensionsMode = 'auto';
HvacAirMFlowReqMaxAvlManForStorg.Complexity = 'auto';
HvacAirMFlowReqMaxAvlManForStorg.SampleTime = -1;
HvacAirMFlowReqMaxAvlManForStorg.InitialValue = '0';
HvacAirMFlowReqMaxAvlManForStorg.GenericProperty = [];
HvacAirMFlowReqMaxAvlManForStorg.DoubleProperty = 0;
HvacAirMFlowReqMaxAvlManForStorg.Int32Property = int32(0);
HvacAirMFlowReqMaxAvlManForStorg.LogicalProperty = false;
HvacAirMFlowReqMaxAvlManForStorg.StringProperty = '';
HvacAirMFlowReqMaxAvlManForStorg.OnOffStringProperty = 'off';
HvacAirMFlowReqMaxAvlManForStorg.ColorStringProperty = 'red';

ManModHexFlowLimActvForStorg = AUTOSAR4.Signal;
ManModHexFlowLimActvForStorg.CoderInfo.StorageClass = 'Custom';
ManModHexFlowLimActvForStorg.CoderInfo.Identifier = '';
ManModHexFlowLimActvForStorg.CoderInfo.Alignment = -1;
ManModHexFlowLimActvForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
ManModHexFlowLimActvForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
ManModHexFlowLimActvForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
ManModHexFlowLimActvForStorg.CoderInfo.CustomAttributes.Owner = '';
ManModHexFlowLimActvForStorg.CoderInfo.CustomAttributes.IsReusable = false;
ManModHexFlowLimActvForStorg.Description = '';
ManModHexFlowLimActvForStorg.DataType = 'boolean';
ManModHexFlowLimActvForStorg.Min = [];
ManModHexFlowLimActvForStorg.Max = [];
ManModHexFlowLimActvForStorg.DocUnits = '';
ManModHexFlowLimActvForStorg.Dimensions = -1;
ManModHexFlowLimActvForStorg.DimensionsMode = 'auto';
ManModHexFlowLimActvForStorg.Complexity = 'auto';
ManModHexFlowLimActvForStorg.SampleTime = -1;
ManModHexFlowLimActvForStorg.InitialValue = 'false';
ManModHexFlowLimActvForStorg.GenericProperty = [];
ManModHexFlowLimActvForStorg.DoubleProperty = 0;
ManModHexFlowLimActvForStorg.Int32Property = int32(0);
ManModHexFlowLimActvForStorg.LogicalProperty = false;
ManModHexFlowLimActvForStorg.StringProperty = '';
ManModHexFlowLimActvForStorg.OnOffStringProperty = 'off';
ManModHexFlowLimActvForStorg.ColorStringProperty = 'red';

ManModHmiAirDistbnFrntLeForStorg = AUTOSAR4.Signal;
ManModHmiAirDistbnFrntLeForStorg.CoderInfo.StorageClass = 'Custom';
ManModHmiAirDistbnFrntLeForStorg.CoderInfo.Identifier = '';
ManModHmiAirDistbnFrntLeForStorg.CoderInfo.Alignment = -1;
ManModHmiAirDistbnFrntLeForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
ManModHmiAirDistbnFrntLeForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
ManModHmiAirDistbnFrntLeForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
ManModHmiAirDistbnFrntLeForStorg.CoderInfo.CustomAttributes.Owner = '';
ManModHmiAirDistbnFrntLeForStorg.CoderInfo.CustomAttributes.IsReusable = false;
ManModHmiAirDistbnFrntLeForStorg.Description = '';
ManModHmiAirDistbnFrntLeForStorg.DataType = ...
  'Enum:HmiCmptmtAirDistbnFrnt';
ManModHmiAirDistbnFrntLeForStorg.Min = [];
ManModHmiAirDistbnFrntLeForStorg.Max = [];
ManModHmiAirDistbnFrntLeForStorg.DocUnits = '';
ManModHmiAirDistbnFrntLeForStorg.Dimensions = -1;
ManModHmiAirDistbnFrntLeForStorg.DimensionsMode = 'auto';
ManModHmiAirDistbnFrntLeForStorg.Complexity = 'auto';
ManModHmiAirDistbnFrntLeForStorg.SampleTime = -1;
ManModHmiAirDistbnFrntLeForStorg.InitialValue = ...
  'HmiCmptmtAirDistbnFrnt.Flr';
ManModHmiAirDistbnFrntLeForStorg.GenericProperty = [];
ManModHmiAirDistbnFrntLeForStorg.DoubleProperty = 0;
ManModHmiAirDistbnFrntLeForStorg.Int32Property = int32(0);
ManModHmiAirDistbnFrntLeForStorg.LogicalProperty = false;
ManModHmiAirDistbnFrntLeForStorg.StringProperty = '';
ManModHmiAirDistbnFrntLeForStorg.OnOffStringProperty = 'off';
ManModHmiAirDistbnFrntLeForStorg.ColorStringProperty = 'red';

ManModHmiAirDistbnFrntRiForStorg = AUTOSAR4.Signal;
ManModHmiAirDistbnFrntRiForStorg.CoderInfo.StorageClass = 'Custom';
ManModHmiAirDistbnFrntRiForStorg.CoderInfo.Identifier = '';
ManModHmiAirDistbnFrntRiForStorg.CoderInfo.Alignment = -1;
ManModHmiAirDistbnFrntRiForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
ManModHmiAirDistbnFrntRiForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
ManModHmiAirDistbnFrntRiForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
ManModHmiAirDistbnFrntRiForStorg.CoderInfo.CustomAttributes.Owner = '';
ManModHmiAirDistbnFrntRiForStorg.CoderInfo.CustomAttributes.IsReusable = false;
ManModHmiAirDistbnFrntRiForStorg.Description = '';
ManModHmiAirDistbnFrntRiForStorg.DataType = ...
  'Enum:HmiCmptmtAirDistbnFrnt';
ManModHmiAirDistbnFrntRiForStorg.Min = [];
ManModHmiAirDistbnFrntRiForStorg.Max = [];
ManModHmiAirDistbnFrntRiForStorg.DocUnits = '';
ManModHmiAirDistbnFrntRiForStorg.Dimensions = -1;
ManModHmiAirDistbnFrntRiForStorg.DimensionsMode = 'auto';
ManModHmiAirDistbnFrntRiForStorg.Complexity = 'auto';
ManModHmiAirDistbnFrntRiForStorg.SampleTime = -1;
ManModHmiAirDistbnFrntRiForStorg.InitialValue = ...
  'HmiCmptmtAirDistbnFrnt.Flr';
ManModHmiAirDistbnFrntRiForStorg.GenericProperty = [];
ManModHmiAirDistbnFrntRiForStorg.DoubleProperty = 0;
ManModHmiAirDistbnFrntRiForStorg.Int32Property = int32(0);
ManModHmiAirDistbnFrntRiForStorg.LogicalProperty = false;
ManModHmiAirDistbnFrntRiForStorg.StringProperty = '';
ManModHmiAirDistbnFrntRiForStorg.OnOffStringProperty = 'off';
ManModHmiAirDistbnFrntRiForStorg.ColorStringProperty = 'red';

ModeDialDefrstFlrInForHexDefrstForStorg = AUTOSAR4.Signal;
ModeDialDefrstFlrInForHexDefrstForStorg.CoderInfo.StorageClass = ...
  'Custom';
ModeDialDefrstFlrInForHexDefrstForStorg.CoderInfo.Identifier = '';
ModeDialDefrstFlrInForHexDefrstForStorg.CoderInfo.Alignment = -1;
ModeDialDefrstFlrInForHexDefrstForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
ModeDialDefrstFlrInForHexDefrstForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
ModeDialDefrstFlrInForHexDefrstForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
ModeDialDefrstFlrInForHexDefrstForStorg.CoderInfo.CustomAttributes.Owner = '';
ModeDialDefrstFlrInForHexDefrstForStorg.CoderInfo.CustomAttributes.IsReusable = false;
ModeDialDefrstFlrInForHexDefrstForStorg.Description = '-';
ModeDialDefrstFlrInForHexDefrstForStorg.DataType = 'boolean';
ModeDialDefrstFlrInForHexDefrstForStorg.Min = 0;
ModeDialDefrstFlrInForHexDefrstForStorg.Max = 1;
ModeDialDefrstFlrInForHexDefrstForStorg.DocUnits = 'NoUnit';
ModeDialDefrstFlrInForHexDefrstForStorg.Dimensions = -1;
ModeDialDefrstFlrInForHexDefrstForStorg.DimensionsMode = 'auto';
ModeDialDefrstFlrInForHexDefrstForStorg.Complexity = 'auto';
ModeDialDefrstFlrInForHexDefrstForStorg.SampleTime = -1;
ModeDialDefrstFlrInForHexDefrstForStorg.InitialValue = 'false';
ModeDialDefrstFlrInForHexDefrstForStorg.GenericProperty = [];
ModeDialDefrstFlrInForHexDefrstForStorg.DoubleProperty = 0;
ModeDialDefrstFlrInForHexDefrstForStorg.Int32Property = int32(0);
ModeDialDefrstFlrInForHexDefrstForStorg.LogicalProperty = false;
ModeDialDefrstFlrInForHexDefrstForStorg.StringProperty = '';
ModeDialDefrstFlrInForHexDefrstForStorg.OnOffStringProperty = 'off';
ModeDialDefrstFlrInForHexDefrstForStorg.ColorStringProperty = 'red';

ModeDialDefrstFlrInForHexFlrDefrstForStorg = AUTOSAR4.Signal;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.CoderInfo.StorageClass = ...
  'Custom';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.CoderInfo.Identifier = '';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.CoderInfo.Alignment = -1;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.CoderInfo.CustomAttributes.Owner = '';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.CoderInfo.CustomAttributes.IsReusable = false;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.Description = '-';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.DataType = 'boolean';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.Min = 0;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.Max = 1;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.DocUnits = 'NoUnit';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.Dimensions = -1;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.DimensionsMode = 'auto';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.Complexity = 'auto';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.SampleTime = -1;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.InitialValue = 'false';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.GenericProperty = [];
ModeDialDefrstFlrInForHexFlrDefrstForStorg.DoubleProperty = 0;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.Int32Property = int32(0);
ModeDialDefrstFlrInForHexFlrDefrstForStorg.LogicalProperty = false;
ModeDialDefrstFlrInForHexFlrDefrstForStorg.StringProperty = '';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.OnOffStringProperty = 'off';
ModeDialDefrstFlrInForHexFlrDefrstForStorg.ColorStringProperty = 'red';

ModeDialDefrstFlrInForTiDefrstForStorg = AUTOSAR4.Signal;
ModeDialDefrstFlrInForTiDefrstForStorg.CoderInfo.StorageClass = ...
  'Custom';
ModeDialDefrstFlrInForTiDefrstForStorg.CoderInfo.Identifier = '';
ModeDialDefrstFlrInForTiDefrstForStorg.CoderInfo.Alignment = -1;
ModeDialDefrstFlrInForTiDefrstForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
ModeDialDefrstFlrInForTiDefrstForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
ModeDialDefrstFlrInForTiDefrstForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
ModeDialDefrstFlrInForTiDefrstForStorg.CoderInfo.CustomAttributes.Owner = '';
ModeDialDefrstFlrInForTiDefrstForStorg.CoderInfo.CustomAttributes.IsReusable = false;
ModeDialDefrstFlrInForTiDefrstForStorg.Description = '-';
ModeDialDefrstFlrInForTiDefrstForStorg.DataType = 'boolean';
ModeDialDefrstFlrInForTiDefrstForStorg.Min = 0;
ModeDialDefrstFlrInForTiDefrstForStorg.Max = 1;
ModeDialDefrstFlrInForTiDefrstForStorg.DocUnits = 'NoUnit';
ModeDialDefrstFlrInForTiDefrstForStorg.Dimensions = -1;
ModeDialDefrstFlrInForTiDefrstForStorg.DimensionsMode = 'auto';
ModeDialDefrstFlrInForTiDefrstForStorg.Complexity = 'auto';
ModeDialDefrstFlrInForTiDefrstForStorg.SampleTime = -1;
ModeDialDefrstFlrInForTiDefrstForStorg.InitialValue = 'false';
ModeDialDefrstFlrInForTiDefrstForStorg.GenericProperty = [];
ModeDialDefrstFlrInForTiDefrstForStorg.DoubleProperty = 0;
ModeDialDefrstFlrInForTiDefrstForStorg.Int32Property = int32(0);
ModeDialDefrstFlrInForTiDefrstForStorg.LogicalProperty = false;
ModeDialDefrstFlrInForTiDefrstForStorg.StringProperty = '';
ModeDialDefrstFlrInForTiDefrstForStorg.OnOffStringProperty = 'off';
ModeDialDefrstFlrInForTiDefrstForStorg.ColorStringProperty = 'red';

ModeDialDefrstFlrInForTiFlrDefrstForStorg = AUTOSAR4.Signal;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.CoderInfo.StorageClass = ...
  'Custom';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.CoderInfo.Identifier = '';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.CoderInfo.Alignment = -1;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.CoderInfo.CustomAttributes.Owner = '';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.CoderInfo.CustomAttributes.IsReusable = false;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.Description = '-';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.DataType = 'boolean';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.Min = 0;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.Max = 1;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.DocUnits = 'NoUnit';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.Dimensions = -1;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.DimensionsMode = 'auto';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.Complexity = 'auto';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.SampleTime = -1;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.InitialValue = 'false';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.GenericProperty = [];
ModeDialDefrstFlrInForTiFlrDefrstForStorg.DoubleProperty = 0;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.Int32Property = int32(0);
ModeDialDefrstFlrInForTiFlrDefrstForStorg.LogicalProperty = false;
ModeDialDefrstFlrInForTiFlrDefrstForStorg.StringProperty = '';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.OnOffStringProperty = 'off';
ModeDialDefrstFlrInForTiFlrDefrstForStorg.ColorStringProperty = 'red';

ModeDialDefrstFlrOutForStorg = AUTOSAR4.Signal;
ModeDialDefrstFlrOutForStorg.CoderInfo.StorageClass = 'Custom';
ModeDialDefrstFlrOutForStorg.CoderInfo.Identifier = '';
ModeDialDefrstFlrOutForStorg.CoderInfo.Alignment = -1;
ModeDialDefrstFlrOutForStorg.CoderInfo.CustomStorageClass = ...
  'GlobalDisp';
ModeDialDefrstFlrOutForStorg.CoderInfo.CustomAttributes.HeaderFile = '';
ModeDialDefrstFlrOutForStorg.CoderInfo.CustomAttributes.DefinitionFile = '';
ModeDialDefrstFlrOutForStorg.CoderInfo.CustomAttributes.Owner = '';
ModeDialDefrstFlrOutForStorg.CoderInfo.CustomAttributes.IsReusable = false;
ModeDialDefrstFlrOutForStorg.Description = '';
ModeDialDefrstFlrOutForStorg.DataType = 'Enum:HmiCmptmtAirDistbnFrnt';
ModeDialDefrstFlrOutForStorg.Min = [];
ModeDialDefrstFlrOutForStorg.Max = [];
ModeDialDefrstFlrOutForStorg.DocUnits = '';
ModeDialDefrstFlrOutForStorg.Dimensions = -1;
ModeDialDefrstFlrOutForStorg.DimensionsMode = 'auto';
ModeDialDefrstFlrOutForStorg.Complexity = 'auto';
ModeDialDefrstFlrOutForStorg.SampleTime = -1;
ModeDialDefrstFlrOutForStorg.InitialValue = ...
  'HmiCmptmtAirDistbnFrnt.Flr';
ModeDialDefrstFlrOutForStorg.GenericProperty = [];
ModeDialDefrstFlrOutForStorg.DoubleProperty = 0;
ModeDialDefrstFlrOutForStorg.Int32Property = int32(0);
ModeDialDefrstFlrOutForStorg.LogicalProperty = false;
ModeDialDefrstFlrOutForStorg.StringProperty = '';
ModeDialDefrstFlrOutForStorg.OnOffStringProperty = 'off';
ModeDialDefrstFlrOutForStorg.ColorStringProperty = 'red';

