function importScript_compos_mdl
%% Import ARXML Files
arxmlList = {'controller_arch_import_mdl_datatype.arxml', ...
    'controller_arch_import_mdl_interface.arxml', ...
    'Electronic_Throttle_Control_import_mdl_composition.arxml', ...
    'inputScaling_arch_import_mdl_component.arxml', ...
    'inputScaling_arch_import_mdl_implementation.arxml', ...
    'inputScaling_arch_import_mdl_timing.arxml', ...
    'outputScaling_arch_import_mdl_component.arxml', ...
    'outputScaling_arch_import_mdl_implementation.arxml', ...
    'piCtrl_arch_import_mdl_component.arxml', ...
    'piCtrl_arch_import_mdl_implementation.arxml', ...
    'pwmConversion_arch_import_mdl_component.arxml', ...
    'pwmConversion_arch_import_mdl_implementation.arxml' ...
    };
importerObj = arxml.importer(arxmlList) %#ok

%% Create new composition model with interfaces and internal behavior

[~] = rmdir('compos_mdl');
mkdir compos_mdl
d = cd('compos_mdl');

compos_name = importerObj.getComponentNames('Composition');
importerObj.createCompositionAsModel(compos_name{1}, ...
    'ModelPeriodicRunnablesAs','FunctionCallSubsystem', ...
    'DataDictionary','import_mdl_dd.sldd');

cd(d)