%% TmAfCtrl/TmAfCtrl/Subsystem/GrlShttrAngReqCtrl/AngleReq/ShttrOnlyReq/ID26035_ShttrWntrCdnReq
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.1,...
    'mask',false,...
    'usingAllPorts',true,...
    'logValue',true,...
    'lev1',{'HP','NHP'}, ...
    'lev2',{ ...
        {'True','False'},...
        {'True','False'},...
    }, ...
    'inValue',{ ...
        { ...
            {-5,2,false}, ...
            {[0 -19],2,true}, ...
        }, ...
        { ...
            {-5,1,false}, ...
            {[0 -19],1,true}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {24}, ... 
            {0}, ...  
        }, ...
        { ...
            {0}, ... 
            {0}, ...  
        }, ...
    }...
    )

%% TmAfCtrl/TmAfCtrl/Subsystem/AirReqCtrl/AcAirFlowReq/ID26531_ACReqFanMax/FlagDeicingFinished
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',180,...
    'mask',false,...
    'usingAllPorts',true,...
    'logValue',true,...
    'lev1',{'FlagDeicingFinished'}, ...
    'lev2',{ ...
        {'reset','Processing','Finished'},...
    }, ...
    'inValue',{ ...
        { ...
            {false}, ...
            {true}, ...
            {true}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {false}, ...  
            {true}, ... 
        }, ...
    }...
    )

%% TmAfCtrl/TmAfCtrl/Subsystem/FanReqCtrl/AirFlowFltForFan/flagFanQuickDec
% 
% deicing    true
% noDeicing   speed 为0,  风扇小于10     true
% noDeicing   speed >0.1  ， 风扇大于10     false

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',6,...
    'mask',false,...
    'usingAllPorts',true,...
    'logValue',true,...
    'lev1',{'flagFanQuickDec'}, ...
    'lev2',{ ...
        {'deicing','noDeicingZeroSp','noDeicingNormSp'},...
    }, ...
    'inValue',{ ...
        { ...
            {20,20,true}, ...
            {0,0,false}, ...
            {20,20,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {true}, ...  
            {false}, ... 
        }, ...
    }...
    )


%% TmAfCtrl/TmAfCtrl/Subsystem/GrlShttrAngReqCtrl/AngleReq/AirFlowFltForShttr/ShttrDecRate
% 0 0 false  -10000
% 2 2 true  -10000
% 2 2 false -5
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.1,...
    'mask',false,...
    'usingAllPorts',true,...
    'logValue',true,...
    'lev1',{'ShttrDecRate'}, ...
    'lev2',{ ...
        {'quickDec','quickDecDeicing','normDec'},...
    }, ...
    'inValue',{ ...
        { ...
            {0,0,false}, ...
            {2,2,true}, ...
            {2,2,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {-10000}, ... 
            {-10000}, ...  
            {-5}, ... 
        }, ...
    }...
    )