%% TmRefriVlvCtrl/TmRefriVlvCtrl/Init/BexvInit
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'InitState'}, ...
    'lev2',{ ...
        {'Success','Fail'},...
    }, ...
    'inName',{ ...
        { 
            'sTmIn_D_u8BexvCalibSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'rTmRefriVlvCtrl_Z_u8BEXVInitState',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0}, ...
            {2}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {2}, ...  
        }, ...
    }...
    )


% xBexvInit_B_BexvPosnCalibReq
createHarness(gcb, ...
    'lastStep','InitState',...  % Initialize
    'mask',false,...
    'lev1',{'BexvPosnCalibReq'}, ...
    'lev2',{ ...
        {'Off','OnFailedOn1','OnFailedOff1','OnFailedOn2','OnFailedOff2','OnFailedOn3','OnFailedOff3', ...
        'Off2','OnSuccessed','OnSuccessedOff'},...
    }, ...
    'inName',{ ...
        { 
            'yTmIn_B_CPSRFbSt',......
            'sTmIn_D_u8BexvCalibSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'yTmRefriVlvCtrl_B_BexvPosnCalibReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            ...
            {false,0}, ...
            {true,2}, ...
            {true,2}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  % 1s
            {false}, ...  % 12s
            {true}, ...  % 15s后，连续3个脉冲
            {false}, ...  % 连续3个脉冲
            {true}, ...  % 15s后，连续3个脉冲
            {false}, ...  % 连续3个脉冲
            ...
            {false}, ... 
            {true}, ... % 连续1个脉冲
            {false}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/Init/EexvInit
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'InitState'}, ...
    'lev2',{ ...
        {'Success','Fail'},...
    }, ...
    'inName',{ ...
        { 
            'sTmIn_D_u8EexvCalibSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'rTmRefriVlvCtrl_Z_u8EEXVInitState',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0}, ...
            {2}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {2}, ...  
        }, ...
    }...
    )


% yTmRefriVlvCtrl_B_EexvPosnCalibReq
createHarness(gcb, ...
    'lastStep','InitState',...  % Initialize
    'mask',false,...
    'lev1',{'EexvPosnCalibReq'}, ...
    'lev2',{ ...
        {'Off','OnFailedOn1','OnFailedOff1','OnFailedOn2','OnFailedOff2','OnFailedOn3','OnFailedOff3', ...
        'Off2','OnSuccessed','OnSuccessedOff'},...
    }, ...
    'inName',{ ...
        { 
            'yTmIn_B_CPSRFbSt',......
            'sTmIn_D_u8EexvCalibSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'yTmRefriVlvCtrl_B_EexvPosnCalibReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            ...
            {false,0}, ...
            {true,2}, ...
            {true,2}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  % 1s
            {false}, ...  % 12s
            {true}, ...  % 15s后，连续3个脉冲
            {false}, ...  % 连续3个脉冲
            {true}, ...  % 15s后，连续3个脉冲
            {false}, ...  % 连续3个脉冲
            ...
            {false}, ... 
            {true}, ... % 连续1个脉冲
            {false}, ... 
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/Init/CexvInit
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'InitState'}, ...
    'lev2',{ ...
        {'Success','Fail'},...
    }, ...
    'inName',{ ...
        { 
            'sTmIn_D_u8CexvCalibSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'rTmRefriVlvCtrl_Z_u8CEXVInitState',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0}, ...
            {2}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {2}, ...  
        }, ...
    }...
    )


% yTmRefriVlvCtrl_B_CexvPosnCalibReq
createHarness(gcb, ...
    'lastStep','InitState',...  % Initialize
    'mask',false,...
    'lev1',{'CexvPosnCalibReq'}, ...
    'lev2',{ ...
        {'Off','OnFailedOn1','OnFailedOff1','OnFailedOn2','OnFailedOff2','OnFailedOn3','OnFailedOff3', ...
        'Off2','OnSuccessed','OnSuccessedOff'},...
    }, ...
    'inName',{ ...
        { 
            'yTmIn_B_CPSRFbSt',......
            'sTmIn_D_u8CexvCalibSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'yTmRefriVlvCtrl_B_CexvPosnCalibReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            {true,0}, ...
            ...
            {false,0}, ...
            {true,2}, ...
            {true,2}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  % 1s
            {false}, ...  % 12s
            {true}, ...  % 15s后，连续3个脉冲
            {false}, ...  % 连续3个脉冲
            {true}, ...  % 15s后，连续3个脉冲
            {false}, ...  % 连续3个脉冲
            ...
            {false}, ... 
            {true}, ... % 连续1个脉冲
            {false}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/MovEnable_Cexv
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'MovEnable'}, ...
    'lev2',{ ...
        {'HP','NHP'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8HeatPump',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'B_MovEnable',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {2}, ...
            {1}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {false}, ...  
        }, ...
    }...
    )
% CexvPosnCalibReq
createHarness(gcb, ...
    'lastStep','MovEnable',...  % Initialize
    'mask',false,...
    'lev1',{'CexvPosnCalibReq'}, ...
    'lev2',{ ...
        {'HP','NHP'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8FltSt',......
            'B_CexvPosnCalibReqIn',
        }, ...
    },...
    'rstName',{ ...
        { 
            'yTmRefriVlvCtrl_B_CexvPosnCalibReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0,false}, ...
            {3,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/MovEnable_Eexv
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'MovEnable'}, ...
    'lev2',{ ...
        {'HP','NHP'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8HeatPump',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'B_MovEnable',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {2}, ...
            {1}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {false}, ...  
        }, ...
    }...
    )
% EexvPosnCalibReq
createHarness(gcb, ...
    'lastStep','MovEnable',...  % Initialize
    'mask',false,...
    'lev1',{'EexvPosnCalibReq'}, ...
    'lev2',{ ...
        {'HP','NHP'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8FltSt',......
            'B_EexvPosnCalibReqIn',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'yTmRefriVlvCtrl_B_EexvPosnCalibReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0,false}, ...
            {3,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/MovEnable_Cexv
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'MovEnable'}, ...
    'lev2',{ ...
        {'HP','NHP'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8HeatPump',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'B_MovEnable',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {2}, ...
            {1}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {false}, ...  
        }, ...
    }...
    )
% BexvPosnCalibReq
createHarness(gcb, ...
    'lastStep','MovEnable',...  % Initialize
    'mask',false,...
    'lev1',{'BexvPosnCalibReq'}, ...
    'lev2',{ ...
        {'HP','NHP'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8FltSt',......
            'B_BexvPosnCalibReqIn',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'yTmRefriVlvCtrl_B_BexvPosnCalibReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0,false}, ...
            {3,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/ID26206_MaxAcCalc
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'MaxAcCalc'}, ...
    'lev2',{ ...
        {'lev1','lev2','lev3','lev4'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8LargerCoolingFlag',......
            'Te_s32TAmb',......
            'sTmSigProces_Pw_i16ReqPwrForCool',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'D_u8CoolingLoadLevel',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0,[0 3],700}, ...
            {0,[5 3 10 12],700}, ...
            {0,[15 12],700}, ...
            {1,15,700}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {2}, ...  
            {3}, ... 
            {4}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPICalc_SM1/BexvPIPara_SM1/ID26200_BexvErrorCalcSM1
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvErrorCalcSM1'}, ...
    'lev2',{ ...
        {'pos','neg'},...
    }, ...
    'inName',{ ...
        { 
            'SetPoint',......
            'Acture',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'Dvt',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {7,10}, ...
            {7,4}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {3}, ... 
            {-3}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/ID26202_BexvFFSM1
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvFFSM1'}, ...
    'lev2',{ ...
        {'NoDeiciNormCharg','NoDeiciquickCharg','NoDeiciSuperCharg','InterChillDeicing'},...
    }, ...
    'inName',{ ...
        { 
            'yTmRefriModeMgr_B_InterChillDeicing',......
            'sTmSigProces_D_u8CarChrgMode',......
            'sTmSigProces_Te_s32TAmb',......
            'sTmIn_Te_s32HvBattCooltTReq',......
            'sTmSigProces_Te_s32HvBattCooltTOutFilter',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'sfBExvFwCtrl',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,1,25,25,20}, ...
            {false,2,25,25,20}, ...
            {false,3,25,25,20}, ...
            {true,4,25,25,20}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {20}, ... 
            {30}, ...  
            {40}, ...  
            {50}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPICalc_SM1/BexvPIPara_SM1/ID26196_BexvKpSM1
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvKpSM1'}, ...
    'lev2',{ ...
        {'NormCharg','QuickCharg','SuperCharg'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8CarChrgMode',......
            'X_s32BexvPosSts',......
            'ErrorBexv',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'X_u16BexvKp',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {1,20,1}, ...
            {2,20,1}, ...
            {3,20,1}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5}, ... 
            {5}, ...  
            {5}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPICalc_SM1/BexvPIPara_SM1/ID26196_BexvKiSM1
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvKiSM1'}, ...
    'lev2',{ ...
        {'NormCharg','QuickCharg','SuperCharg'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8CarChrgMode',......
            'D_u8HvBattCoolgReq',......
            'ErrorBexv',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'X_u16BexvKi',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {1,1,1}, ...
            {2,1,1}, ...
            {3,1,1}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {1}, ...  
            {1}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPICalc_SM1/ID26198_SM1BexvPIResetValCalc
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SM1BexvPIResetValCalc'}, ...
    'lev2',{ ...
        {'Init','EnterMax','QuiqMax'},...
    }, ...
    'inName',{ ...
        { 
            'B_MAXPos',......
            'X_s32BEXVPosReqOld',......
            'BexvKp',......
            'ErrorBexv',......
            'BexvKi',......
            'sfBExvFwCtrl',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'ResetVal',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,100,10,5,10,20}, ...
            {true,100,10,5,10,20}, ...
            {false,100,10,5,10,20}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0}, ... 
            {0}, ...  
            {70}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPICalc_SM1/ID26196_BexvPISM1
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvPISM1'}, ...
    'lev2',{ ...
        {'PIMax','PIMin','OutMax','OutMin','Reset'},...
    }, ...
    'inName',{ ...
        { 
            'Err',......
            'Reset',......
            'PGain',......
            'IGain',......
            'PMax',......
            'PMin',......
            'IMax',......
            'IMin',......
            'TsPeriod',......
            'KIErrInit',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'Ctrl',...
            'KpSum',...
            'KiSum',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {50,false,100,100,30,-30,30,-30,0.05,0}, ...
            {-50,false,100,100,30,-30,30,-30,0.05,0}, ...
            {200,false,100,100,60,-60,60,-60,0.05,0}, ...
            {-200,false,100,100,60,-60,60,-60,0.05,0}, ...
            {10,true,100,100,60,-60,60,-60,0.05,0}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {60,30,30}, ... 
            {0,-30,-30}, ...  
            {100,60,60}, ...  
            {0,-60,-60}, ... 
            {10.5,10,0.5}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPICalc_SM1/ID26196_BexvPosLimit
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvPosLimit'}, ...
    'lev2',{ ...
        {'UpPos','UpNeg','LowPos','LowNeg','Norm'},...
    }, ...
    'inName',{ ...
        { 
            'X_s32BEXVPosReqOld',......
            'Err',......
            'BexvMin',......
            'BexvMax',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'BexvPosLimit_Flag',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {100,1,0,100}, ...
            {100,-1,0,100}, ...
            {0,1,0,100}, ...
            {0,-1,0,100}, ...
            {50,[-1 1],0,100}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  
            {true}, ...  
            {false}, ... 
            {true}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPIFwFlag_SM1/ID26198ID31512_ProtectFlag

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SHProtect','DischargeProtect'}, ...
    'lev2',{ ...
        {'Off','Low','Mid','High'},...
        {'Off','Low','Mid','High'},...
    }, ...
    'inName',{ ...
        { 
            'SHProtect_ON',......
            'Te_s32HeatSH',......
        }, ...
        { 
            'sTmSigProces_Te_s32CompDischarge',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'B_HeatSH_High',...
            'B_HeatSH_Mid',...
        }, ...
        { 
            'B_CompDischargeT_High',...
            'B_CompDischargeT_Mid',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,5}, ...
            {true,5}, ...
            {true,15}, ...
            {true,25}, ...
        }, ...
        { ...
            {105}, ...
            {105}, ...
            {115}, ...
            {125}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false,false}, ... 
            {false,false}, ...  
            {false,true}, ...  
            {true,false}, ... 
        }, ...
        { ...
            {false,false}, ... 
            {false,false}, ...  
            {false,true}, ...  
            {true,false}, ... 
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPIFwFlag_SM1/ID26196_PICtrlParam

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'LimitFlag','bBExvPIFwOn','bBExvPIFwReset'}, ...
    'lev2',{ ...
        {'None','SH','Discharge'},...
        {'None','MaxPos','ErrNeg'},...
        {'None','MaxPos','MaxPosChg1','NewMode','B_CompOnReq','B_CompOnReqChg1','B_CompOnReqChg2'},...
    }, ...
    'inName',{ ...
        { 
            'B_HeatSH_High',......
            'B_CompDischargeT_High',......
            'B_CompDischargeT_Mid',......
            'B_HeatSH_Mid',......
        }, ...
        { 
            'B_HeatSH_High',......
            'B_CompDischargeT_High',......
            'B_CompDischargeT_Mid',......
            'B_HeatSH_Mid',......
            'Err',......
        }, ...
        { 
            'B_HeatSH_High',......
            'B_CompDischargeT_High',......
            'B_CompDischargeT_Mid',......
            'B_HeatSH_Mid',......
            'NewMode',......
            'B_CompOnReq',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'B_MAXPos',...
            'B_Keep',...
        }, ...
        { 
            'bBExvPIFwOn',...
        }, ...
        { 
            'bBExvPIFwReset',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,false,false,false}, ...
            {true,false,true,false}, ...
            {false,true,false,true}, ...
        }, ...
        { ...
            {false,false,false,false,1}, ...
            {true,false,false,false,1}, ...
            {false,false,true,false,-1}, ...
        }, ...
        { ...
            {false,false,false,false,false,false}, ...
            {true,false,false,false,false,false}, ...
            {false,false,false,false,false,false}, ...
            {false,false,false,false,true,false}, ...
            {false,false,false,false,false,false}, ...
            {false,false,false,false,false,true}, ...
            {false,false,false,false,false,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false,false}, ... 
            {true,false}, ... 
            {false,true}, ...  
        }, ...
        { ...
            {true}, ... 
            {false}, ...  
            {false}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ...  
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BEXVPosCalc

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'bBExvPIFwOn','bBExvPIFwOff'}, ...
    'lev2',{ ...
        {'bBExvPIFwOn'},...
        {'B_MAXPosOn','MAXPosOffHeatSHMidOn','MAXPosOffHeatSHMidOn1','MAXPosOffHeatSHMidOff'},...
    }, ...
    'inName',{ ...
        { 
            'bBExvPIFwOn',......
            'sfBExvFbCtrl',......
            'sfBExvFwCtrl',......
        }, ...
        { 
            'bBExvPIFwOn',......
            'B_MAXPos',......
            'B_Keep',......
            'X_s32BEXVPosReqOld',......
            'sfBExvFbCtrl',......
            'sfBExvFwCtrl',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'BEXVPosCalc',...
        }, ...
        { 
            'BEXVPosCalc',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true,25,25}, ...
        }, ...
        { ...
            {false,true,false,60,25,25}, ...
            {false,false,true,60,25,25}, ...
            {false,false,true,40,25,25}, ...
            {false,false,false,60,25,25}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {50}, ... 
        }, ...
        { ...
            {100}, ... 
            {60}, ...  
            {50}, ...  
            {0}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BEXVRampLimit

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'Up','Down'}, ...
    'lev2',{ ...
        {'SHProtect','DisChargProt','Others'},...
        {'SHProtect','DisChargProt','Others'},...
    }, ...
    'inName',{ ...
        { 
            'X_s32BEXVPosReq',......
            'X_s32BEXVPosReqOld',......
            'B_HeatSH_High',......
            'B_CompDischargeT_High',......
        }, ...
        { 
            'X_s32BEXVPosReq',......
            'X_s32BEXVPosReqOld',......
            'B_HeatSH_High',......
            'B_CompDischargeT_High',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'X_s32BEXVPosReqRamp',...
        }, ...
        { 
            'X_s32BEXVPosReqRamp',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {50,25,true,false}, ... % 1 3
            {50,25,false,true}, ...  % 1 3
            {50,25,false,false}, ...  % 4 1
        }, ...
        { ...
            {25,50,true,false}, ... % 2 3
            {25,50,false,true}, ... % 2 3
            {25,50,false,false}, ... % 2 1
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {26}, ... 
            {26}, ... 
            {29}, ... 
        }, ...
        { ...
            {48}, ... 
            {48}, ... 
            {48}, ... 
        }, ...
    }...
    )
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/ID26191_BEXVMaxMinLimit
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'PosLimit'}, ...
    'lev2',{ ...
        {'Min','Norm','Max'},...
    }, ...
    'inName',{ ...
        { 
            'X_s32BEXVPosReq',......
            'BexvMin',......
            'BexvMax',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'sTmRefriVlvCtrl_X_s32BEXVPosReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0,25,75}, ... 
            {50,25,75}, ... 
            {100,25,75}, ... 
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {25}, ... 
            {50}, ... 
            {75}, ... 
        }, ...
    }...
    )

%% ------------------------------------------------------------------
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM2_Cool/SM2_Cool_Sub/ID26189_bBExvPIFwOffBEXVPos
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SM2BexvPos'}, ...
    'lev2',{ ...
        {'OCR','NoOCRCycle','NoOCRNoCycle'},...
    }, ...
    'inName',{ ...
        { 
            'B_CoolOCRMode',......
            'Cycle',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'X_s32BEXVPosReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true,false}, ... 
            {false,true}, ... 
            {false,false}, ... 
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {50}, ... 
            {0}, ... 
            {0}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM2_Cool/SM2_Cool_Sub/EexvLimit_SM2/SM2EexvProtectFlag

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SHProtect','DischargeProtect','LowPress'}, ...
    'lev2',{ ...
        {'Disable','Off','Mid','High'},...
        {'Off','Mid','High'},...
        {'Disable','Off','Mid','High'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8CoolingLoadLevel',......
            'Te_s32CoolSH',......
            'SHProtect_ON',......
        }, ...
        { 
            'sTmSigProces_Te_s32CompDischarge',......
        }, ...
        { 
            'D_u8CoolingLoadLevel',......
            'p_u16PLowSide',......
            'LPProtect_ON',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'CoolSH_Lim',...
            'CoolSH_Mid',...
        }, ...
        { 
            'B_CompDischargeT_High',...
            'B_CompDischargeT_Mid',...
        }, ...
        { 
            'PLowSide_Lim',...
            'PLowSide_Mid',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {4,10,false}, ...  % 15 20
            {4,10,true}, ...  % 15 20
            {4,18,true}, ...  % 15 20
            {4,25,true}, ...  % 15 20
        }, ...
        { ...
            {105}, ...
            {115}, ...
            {125}, ...
        }, ...
        { ...
            {3,290,true}, ... % 270 285
            {4,290,true}, ... % 270 285
            {4,280,true}, ...
            {4,265,true}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false,false}, ...  
            {false,false}, ... 
            {false,true}, ...  
            {true,false}, ... 
        }, ...
        { ...
            {false,false}, ...  
            {false,true}, ...  
            {true,false}, ... 
        }, ...
        { ...
            {false,false}, ...  
            {false,false}, ...  
            {false,true}, ...  
            {true,false}, ... 
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM2_Cool/SM2_Cool_Sub/EexvLimit_SM2/SM2EexvPICtrlParam

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'LimitFlag','bBExvPIFwOn','bBExvPIFwReset'}, ...
    'lev2',{ ...
        {'None','SH','Discharge','PLowSide'},...
        {'None','MaxPos','ErrNeg'},...
        {'None','MaxPos','MaxPosChg1','NewMode','B_CompOnReq','B_CompOnReqChg1','B_CompOnReqChg2'},...
    }, ...
    'inName',{ ...
        { 
            'B_CompDischargeT_High',......
            'CoolSH_Lim',......
            'PLowSide_Lim',......
            'B_CompDischargeT_Mid',......
            'PLowSide_Mid',......
            'CoolSH_Mid',......
        }, ...
        { 
            'B_CompDischargeT_High',......
            'CoolSH_Lim',......
            'PLowSide_Lim',......
            'B_CompDischargeT_Mid',......
            'PLowSide_Mid',......
            'CoolSH_Mid',......
            'Err',......
        }, ...
        { 
            'B_CompDischargeT_High',......
            'CoolSH_Lim',......
            'PLowSide_Lim',......
            'B_CompDischargeT_Mid',......
            'PLowSide_Mid',......
            'CoolSH_Mid',......
            'NewMode',......
            'B_CompOnReq',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'B_MAXPos',...
            'B_Keep',...
        }, ...
        { 
            'bBExvPIFwOn',...
        }, ...
        { 
            'bBExvPIFwReset',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,false,false,false,false,false}, ...
            {true,false,false,true,false,false}, ...
            {false,true,false,false,true,false}, ...
            {false,false,true,false,false,true}, ...
        }, ...
        { ...
            {false,false,false,false,false,false,1}, ...
            {true,false,false,false,false,false,1}, ...
            {false,false,false,true,false,false,-1}, ...
        }, ...
        { ...
            {false,false,false,false,false,false,false,false}, ...
            {true,false,false,false,false,false,false,false}, ...
            {false,false,false,false,false,false,false,false}, ...
            {false,false,false,false,false,false,true,false}, ...
            {false,false,false,false,false,false,false,false}, ...
            {false,false,false,false,false,false,false,true}, ...
            {false,false,false,false,false,false,false,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false,false}, ... 
            {true,true}, ... 
            {true,true}, ...  
            {true,true}, ...  
        }, ...
        { ...
            {true}, ... 
            {false}, ...  
            {false}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM2_Cool/SM2_Cool_Sub/EexvPICalc_SM2/ID26205_EexvPIParaCalcSM2

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'Params'}, ...
    'lev2',{ ...
        {'Pos','Neg'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8CoolingLoadLevel',......
            'Te_s32CurSCCalValue',......
            'sTmIn_X_s32EexvPosSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'Te_s32ReqSC',...
            'ErrorEexv',...
            'u16EexvKp',...
            'u16EexvKi',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {1,8,9}, ...
            {1,0,9}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {4,4,1,0}, ... 
            {4,-4,1,0}, ... 
        }, ...
    }...
    )
%% ------------------------------------------------------------------------
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM3_ChillCool/BexvPICalc_SM3/ID26183_BexvPIParaSM3
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'Params'}, ...
    'lev2',{ ...
        {'Pos','Neg'},...
    }, ...
    'inName',{ ...
        { 
            'Te_s32HvBattCooltTReq',......
            'Te_s32HvBattCooltTFilter',......
            'D_u8HvBattCoolgReq',......
            'sTmIn_X_s32BexvPosSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'ErrorBexv',...
            'u16BexvKp',...
            'u16BexvKi',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {25,30,1,9}, ...
            {25,20,1,9}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5,1,1}, ... 
            {-5,1,1}, ... 
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM3_ChillCool/BexvPIFw_Flag/ID30316ID30317_EvapFanTBexvLim
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BattHvMaxHi','BattHvMaxLow'}, ...
    'lev2',{ ...
        {'BattHvMaxHi'},...
        {'Lev0','Lev1','Lev2'},...
    }, ...
    'inName',{ ...
        { 
            'Te_s32BattHvMaxFilter',......
        }, ...
        { 
            'Te_s32BattHvMaxFilter',......
            'sTmSigProces_Te_s32EvapFanFilter',......
            'sTmSigProces_Te_s32EvapFanReqRamp',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'yTmRefriVlvCtrl_B_EvapBattTLimBexvEna',...
            'TevapTbatBexvLmtSts',...
        }, ...
        { 
            'yTmRefriVlvCtrl_B_EvapBattTLimBexvEna',...
            'TevapTbatBexvLmtSts',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {[44  43.5] }, ...
        }, ...
        { ...
            {43, [12 13],8}, ...
            {43, [15 13],8}, ...
            {43.5, [18 17],8}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0,0}, ... 
        }, ...
        { ...
            {1,0}, ... 
            {1,1}, ... 
            {1,2}, ... 
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM3_ChillCool/BexvPIFw_Flag/ID30317_EvapLimit
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'Keep','Reduce'}, ...
    'lev2',{ ...
        {'true','false'},...
        {'trueLev','trueEvap','false'},...
    }, ...
    'inName',{ ...
        {'TevapTbatBexvLmtSts'},...
        { 
            'TevapTbatBexvLmtSts',...
            'n_u16CompRpmReq',...
            'n_u16CompMaxRpm',...
            'sTmSigProces_Te_s32EvapFanFilter',...
            'B_EvapBattTLimBexvEna',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'TevapTbatBexvPosKeep',...
        }, ...
        { 
            'TevapTbatBexvPosDec',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {[1 2]}...
            {0}...
        },...
        { ...
            {2,5000,5000,12 false}, ...
            {0,5000,5000,[15 14] true }, ...
            ...
            {0,5000,6000,[12 14] false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {false}, ... 
        }, ...
        { ...
            {true}, ... 
            {true}, ... 
            {false}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM3_ChillCool/ID26180_BexvMaxCalc
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvMaxCalc'}, ...
    'lev2',{ ...
        {'HvBattCoolFlowHi', 'HvBattCoolFlowLNoChrgSpLow', 'HvBattCoolFlowLNoChrgSpMid', 'HvBattCoolFlowLNoChrgSpHi', 'HvBattCoolFlowLChrg'},...
    }, ...
    'inName',{ ...
        { 
            'sTmIn_L_s32HvBattCoolFlow1',...
            'D_u8CarChrgMode',...
            'Te_s32BattHvMaxFilter',...
            'sTmSigProces_Te_s32TAmb',...
            'sTmIn_v_s32VehSpdLgt',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'BexvMax',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {50,0,40 25 0}, ...
            {30,0,40 25 0}, ...
            {30,0,40 25 120}, ...
            {30,0,40 25 140}, ...
            {30,1,40 25 0}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {60}, ... 
            {40}, ... 
            {40}, ... 
            {50}, ... 
            {40}, ... 
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM3_ChillCool/BexvPIFw_Flag/ID30318_BattLowProtInSuperChrg
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BattLowProtInSuperChrg'}, ...
    'lev2',{ ...
        {'ProtectBattMax', 'ProtectBattCooltT',  'NoProtectChrgMode', 'NoProtectBatt'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8CarChrgMode',...
            'Te_s32HvBattCooltTReq',...
            'Te_s32BattHvMaxFilter',...
            'Te_s32HvBattCooltTFilter',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'bBexvCtlFlg',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {3,25,[25 26] 30 }, ...
            {3,25,30 [22 25]}, ...
            {1,25,30 25 }, ...
            {3,25,[27 26] [28 25] }, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {true}, ... 
            {false}, ... 
            {false}, ... 
        }, ...
    }...
    )
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM3_ChillCool/EexvPICalc_SM3/ID26162_EexvPIParaCalcSM3
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'EexvPIParaCalcSM3'}, ...
    'lev2',{ ...
        {'Pos','Neg'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8CoolingLoadLevel',......
            'Acture',......
            'sTmIn_X_s32EexvPosSts',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'Te_s32ReqSC',...
            'ErrorEexv',...
            'u16EexvKp',...
            'u16EexvKi',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {1,9,9}, ...
            {1,-1,9}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {4,5,1,0}, ... 
            {4,-5,1,0}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM3_ChillCool/EexvLimit_SM3/SM3EexvProtectFlag

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SHProtect','DischargeProtect','LowPress'}, ...
    'lev2',{ ...
        {'Disable','Off','Mid','High'},...
        {'Off','Mid','High'},...
        {'Disable','Off','Mid','High'},...
    }, ...
    'inName',{ ...
        { 
            'D_u8CoolingLoadLevel',......
            'Te_s32HeatSH',......
            'SHProtect_ON',......
        }, ...
        { 
            'sTmSigProces_Te_s32CompDischarge',......
        }, ...
        { 
            'D_u8CoolingLoadLevel',......
            'p_u16PLowSide',......
            'LPProtect_ON',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'B_HeatSH_High',...
            'B_HeatSH_Mid',...
        }, ...
        { 
            'B_CompDischargeT_High',...
            'B_CompDischargeT_Mid',...
        }, ...
        { 
            'PLowSide_Lim',...
            'PLowSide_Mid',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {4,10,false}, ...  % 15 20
            {4,10,true}, ...  % 15 20
            {4,18,true}, ...  % 15 20
            {4,25,true}, ...  % 15 20
        }, ...
        { ...
            {105}, ...
            {115}, ...
            {125}, ...
        }, ...
        { ...
            {3,290,true}, ... % 270 285
            {4,290,true}, ... % 270 285
            {4,280,true}, ...
            {4,265,true}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false,false}, ...  
            {false,false}, ... 
            {false,true}, ...  
            {true,false}, ... 
        }, ...
        { ...
            {false,false}, ...  
            {false,true}, ...  
            {true,false}, ... 
        }, ...
        { ...
            {false,false}, ...  
            {false,false}, ...  
            {false,true}, ...  
            {true,false}, ... 
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM3_ChillCool/EexvLimit_SM3/SM3EexvPICtrlParam

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'LimitFlag','bBExvPIFwOn','bBExvPIFwReset'}, ...
    'lev2',{ ...
        {'None','SH','Discharge','PLowSide'},...
        {'None','MaxPos','ErrNeg'},...
        {'None','MaxPos','MaxPosChg1','NewMode','B_CompOnReq','B_CompOnReqChg1','B_CompOnReqChg2'},...
    }, ...
    'inName',{ ...
        { 
            'B_CompDischargeT_High',......
            'B_HeatSH_High',......
            'PLowSide_Lim',......
            'B_CompDischargeT_Mid',......
            'PLowSide_Mid',......
            'B_HeatSH_Mid',......
        }, ...
        { 
            'B_CompDischargeT_High',......
            'B_HeatSH_High',......
            'PLowSide_Lim',......
            'B_CompDischargeT_Mid',......
            'PLowSide_Mid',......
            'B_HeatSH_Mid',......
            'Err',......
        }, ...
        { 
            'B_CompDischargeT_High',......
            'B_HeatSH_High',......
            'PLowSide_Lim',......
            'B_CompDischargeT_Mid',......
            'PLowSide_Mid',......
            'B_HeatSH_Mid',......
            'NewMode',......
            'B_CompOnReq',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'MAXPos_En',...
            'B_Keep',...
        }, ...
        { 
            'bEExvPIFwOn',...
        }, ...
        { 
            'bEExvPIFwReset',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,false,false,false,false,true}, ...  % et<0.10000||et>0.10000, 时间需要从0.05改为0.1.,确保信号没有突变
            {true,false,false,true,false,false}, ...
            {false,true,false,false,true,false}, ...
            {false,false,true,false,false,true}, ...
        }, ...
        { ...
            {false,false,false,false,false,false,1}, ...
            {true,false,false,false,false,false,1}, ...
            {false,false,false,true,false,false,-1}, ...
        }, ...
        { ...
            {false,false,false,false,false,false,false,false}, ...
            {true,false,false,false,false,false,false,false}, ...
            {false,false,false,false,false,false,false,false}, ...
            {false,false,false,false,false,false,true,false}, ...
            {false,false,false,false,false,false,false,false}, ...
            {false,false,false,false,false,false,false,true}, ...
            {false,false,false,false,false,false,false,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false,false}, ... 
            {true,true}, ... 
            {true,true}, ...  
            {true,true}, ...  
        }, ...
        { ...
            {true}, ... 
            {false}, ...  
            {false}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ...  
        }, ...
    }...
    )
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM4_Heat/Subsystem/ID26199_CexvFF
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'CexvFF'}, ...
    'lev2',{ ...
        {'PtcEnad','PtcNotEnad'},...
    }, ...
    'inName',{ ...
        { 
            'sTmComprCtrl_D_u8HvacFlowLevel',...
            'sTmSigProces_Te_s32TAmb',...
            'yTmHvchCtrl_B_HpcPtcEnad',...
            'sTmSigProces_Te_s32HeatrAirTReqRamp',...
            'sTmSigProces_Te_s32EvapFanFilter',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'sfCExvFwCtrl',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {10,25,true,40,30}, ...
            {10,25,false,40,30}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {20}, ... 
            {20}, ... 
        }, ...
    }...
    )
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM4_Heat/Subsystem/CexvPI/ID26197_SM4Kp
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SM4Kp'}, ...
    'lev2',{ ...
        {'SM4Kp'},...
    }, ...
    'inName',{ ...
        { 
            'sTmComprCtrl_D_u8HvacFlowLevel',...
            'sTmSigProces_Te_s32TAmb',...
            'ErrorCexv',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'X_u16CexvKp',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {10,0,4}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM4_Heat/Subsystem/CexvPI/ID26197_SM4Ki
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SM4Ki'}, ...
    'lev2',{ ...
        {'SM4Ki'},...
    }, ...
    'inName',{ ...
        { 
            'sTmComprCtrl_D_u8HvacFlowLevel',...
            'Te_s32TAmb',...
            'ErrorCexv',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'X_u16CexvKi',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {10,0,4}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM4_Heat/Subsystem/CexvLimit_SM4/SM4EexvProtectFlag

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SHProtect'}, ...
    'lev2',{ ...
        {'Disable','Off','Mid','High'},...
    }, ...
    'inName',{ ...
        { 
            'Te_s32HeatSH',......
            'SHProtect_ON',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'HeatSH_High',...
            'HeatSH_Mid',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {5,false}, ...  % 10 15
            {5,true}, ...  % 
            {15,true}, ...  % 
            {18,true}, ...  % 
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false,false}, ...  
            {false,false}, ... 
            {false,true}, ...  
            {true,false}, ... 
        }, ...
    }...
    )
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM4_Heat/Subsystem/CexvLimit_SM4/SM4EexvPICtrlParam

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'bBExvPIFwOn','bBExvPIFwReset'}, ...
    'lev2',{ ...
        {'None','HSHigh','ErrNeg'},...
        {'None','HSHigh','HSHighChg1','NewMode','B_CompOnReq','B_CompOnReqChg1','B_CompOnReqChg2'},...
    }, ...
    'inName',{ ...
        { 
            'B_HeatSH_High',......
            'B_HeatSH_Mid',......
            'Err',......
        }, ...
        { 
            'B_HeatSH_High',......
            'B_HeatSH_Mid',......
            'NewMode',......
            'B_CompOnReq',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'bCExvPIFwOn',...
        }, ...
        { 
            'bCExvPIFwReset',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,false,1}, ...
            {true,false,1}, ...
            {false,true,-1}, ...
        }, ...
        { ...
            {false,false,false,true}, ...
            {true,false,false,false}, ...
            {false,false,false,false}, ...
            {false,false,true,false}, ...
            {false,false,false,false}, ...
            {false,false,false,true}, ...
            {false,false,false,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {false}, ...  
            {false}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ...  
        }, ...
    }...
    )
%% ---------------------------------------------------------------------
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM5_HeatRecycle/Subsystem/Subsystem3/ID26212_BexvPIParaSM5
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvPIParaSM5'}, ...
    'lev2',{ ...
        {'pos','neg'},...
    }, ...
    'inName',{ ...
        { 
            'Te_s32CurSCCalValue',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'rTmRefriVlvCtrl_Te_s32ReqSC',...
            'ErrorBexv',...
            'u16BexvKp',...
            'u16BexvKi',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {9}, ...
            {5}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {7,2,3,0}, ... 
            {7,-2,3,0}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM5_HeatRecycle/Subsystem/ID26211_BexvFFSM5
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BexvFFSM5'}, ...
    'lev2',{ ...
        {'FlowLev10','FlowLev20','FlowLev30','FlowLev40','FlowLev50','Disable'},...
    }, ...
    'inName',{ ...
        { 
            'Enable',...
            'Te_s32EvapFanFilter',...
            'Te_s32HeatrAirTReqRamp',...
            'sTmComprCtrl_D_u8HvacFlowLevel',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'sfBExvFwCtrl',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true,0,40,10}, ...
            {true,0,40,20}, ...
            {true,0,40,30}, ...
            {true,0,40,40}, ...
            {true,0,40,50}, ...
            {false,0,40,10}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {20}, ... 
            {20}, ... 
            {20}, ... 
            {20}, ... 
            {20}, ... 
            {20}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM5_HeatRecycle/Subsystem/Subsystem4/SM5BexvProtectFlag

createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'SHProtect'}, ...
    'lev2',{ ...
        {'Disable','Off','Mid','High'},...
    }, ...
    'inName',{ ...
        { 
            'Te_s32HeatSH',......
            'SHProtect_ON',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'HeatSH_High',...
            'HeatSH_Mid',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {5,false}, ...  % 25 30
            {5,true}, ...  % 
            {25,true}, ...  % 
            {35,true}, ...  % 
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false,false}, ...  
            {false,false}, ... 
            {false,true}, ...  
            {true,false}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM5_HeatRecycle/Subsystem/Subsystem4/SM5BexvPICtrlParam
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'bBExvPIFwOn','bBExvPIFwReset'}, ...
    'lev2',{ ...
        {'None','HSHigh','ErrNeg'},...
        {'None','HSHigh','HSHighChg1','NewMode','B_CompOnReq','B_CompOnReqChg1','B_CompOnReqChg2'},...
    }, ...
    'inName',{ ...
        { 
            'B_HeatSH_High',......
            'B_HeatSH_Mid',......
            'Err',......
        }, ...
        { 
            'B_HeatSH_High',......
            'B_HeatSH_Mid',......
            'NewMode',......
            'B_CompOnReq',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'bBExvPIFwOn',...
        }, ...
        { 
            'bBExvPIFwReset',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,false,1}, ...
            {true,false,1}, ...
            {false,true,-1}, ...
        }, ...
        { ...
            {false,false,false,true}, ...
            {true,false,false,false}, ...
            {false,false,false,false}, ...
            {false,false,true,false}, ...
            {false,false,false,false}, ...
            {false,false,false,true}, ...
            {false,false,false,false}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {false}, ...  
            {false}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ... 
            {true}, ...  
            {true}, ...  
            {true}, ...  
        }, ...
    }...
    )


%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM5_HeatRecycle/Subsystem/ID26188_CEXVHold/isNeedHold
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'isNeedHold'}, ...
    'lev2',{ ...
        {'Off','CompOnReq','NewMode','HeatSHDuring','HeatSHAfter1800'},...
    }, ...
    'inName',{ ...
        { 
            'yTmComprCtrl_B_CompOnReq',......
            'NewMode',......
            'sTmSigProces_Te_s32HeatSH',......
            'X_s32CEXVPosReqSM5',......
            'SHProtect_ON',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'isNeedHold',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,false,0,0,false}, ...
            {true,false,0,0,true}, ...
            {true,true,0,0,true}, ...
            {false,false,10,0,true}, ...
            {false,false,10,0,true}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  
            {true}, ...  
            {false}, ...  
            {true}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM5_HeatRecycle/Subsystem/ID26188_CEXVHold
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'X_s32CEXVPosReqSM5'}, ...
    'lev2',{ ...
        {'Off','CompOnReq','NewMode','HeatSHDuring','HeatSHAfter60','HeatSHAfter1800'},...
    }, ...
    'inName',{ ...
        { 
            'yTmComprCtrl_B_CompOnReq',......
            'NewMode',......
            'sTmSigProces_Te_s32HeatSH',......
            'SHProtect_ON',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'X_s32CEXVPosReqSM5',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false,false,0,false}, ...
            {true,false,0,true}, ...
            {true,true,0,true}, ...
            {true,false,10,true}, ...
            {true,false,10,true}, ...
            {true,false,10,true}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0}, ... 
            {20}, ...  
            {20}, ...  
            {20}, ...  
            {0}, ...  
            {20}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM6_ParaDehumid/Subsystem7/EexvPICalc_SM6/ID26176_EexvPIParaCalcSM6
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'EexvPIParaCalcSM6'}, ...
    'lev2',{ ...
        {'Pos','Neg'},...
    }, ...
    'inName',{ ...
        { 
            'Te_s32EvapFanReqRamp',......
            'Te_s32EvapFanFilter',......
            'md_u16BlwCool',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'ErrorEexv',...
            'u16EexvKp',...
            'u16EexvKi',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {5,10,250}, ...
            {5,0,250}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5,1,1}, ... 
            {-5,1,1}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM6_ParaDehumid/Subsystem7/ID26174_EexvFF
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'EexvFF'}, ...
    'lev2',{ ...
        {'EexvFF'},...
    }, ...
    'inName',{ ...
        { 
            'sTmSigProces_md_u16BlwCool',......
            'sTmSigProces_Te_s32InletCal',......
            'sTmSigProces_Te_s32EvapFanReqRamp',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'sfEExvFwCtrl',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {250,13,3}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {20}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM6_ParaDehumid/Subsystem7/ID26171_EexvLimitSM6/ID26171_EvapProtect
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'EvapProtect'}, ...
    'lev2',{ ...
        {'Protect','NoProtect'},...
    }, ...
    'inName',{ ...
        { 
            'Te_s32EvapFanFilter',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'B_s32EEXVEvapProtect',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {[1.5 2]}, ...
            {[3 2]}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {0}, ... 
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM2_Cool/SM2_Cool_Sub/ID26164_EEXVMaxMinLimit
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'EEXVMaxMinLimit'}, ...
    'lev2',{ ...
        {'Uplim','Norm','Lowlim'},...
    }, ...
    'inName',{ ...
        { 
            'X_s32EEXVPosReq',......
            'EexvMax',...
            'EexvMin',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'sTmRefriVlvCtrl_X_s32EEXVPosReq',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {90,80 20}, ...
            {50,80 20}, ...
            {0,80 20}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {80}, ... 
            {50}, ... 
            {20}, ... 
        }, ...
    }...
    )
%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/ModeSwitch/SwitchSts
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SwitchSts'}, ...
    'lev2',{ ...
        {'Init','NoSwitchKeep','EnterSwitch','SwitchKeep','QuitSwitch'},...
    }, ...
    'inName',{ ...
        { 
            'sTmRefriModeMgr_D_u8HpModeMainState ',......
        }, ...
    },...
    'rstName',{ ...
        { 
            'SwitchSts',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0}, ...
            {0}, ...
            {127}, ...
            {127}, ...
            {1}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0}, ... 
            {0}, ... 
            {1}, ... 
            {2}, ...  
            {3}, ...  
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/ModeSwitch/Init
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'Init'}, ...
    'lev2',{ ...
        {'Init','EnterSwitch'},...
    }, ...
    'inName',{ ...
        { 
            'SwitchSts ',...
            'D_u8EexvRefriSwitchSt_In ',...
            'D_u8CexvRefriSwitchSt_In ',...
            'D_u8BexvRefriSwitchSt_In ',...
            'D_u8EexvMoveEnd_In ',...
            'D_u8CexvMoveEnd_In ',...
            'D_u8BexvMoveEnd_In ',...
            'D_u8ModeSwitchType ',...
        }, ...
    },...
    'rstName',{ ...
        { 
            'D_u8EexvRefriSwitchStOld',...
            'D_u8CexvRefriSwitchStOld',...
            'D_u8BexvRefriSwitchStOld',...
            'D_u8EexvMoveEndOld',...
            'D_u8CexvMoveEndOld',...
            'D_u8BexvMoveEndOld',...
            'D_u8ModeSwitchTypeLoc',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0 1 1 1 2 2 2 6}, ...
            {1 1 1 1 2 2 2 6}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1 1 1 2 2 2 0}, ...
            {0 0 0 0 0 0 6}, ...
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/ModeSwitch/Switch_ING/Switch0_Sub/Switch0_Chart
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'Switch0'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {0 0 1 1 1 2 2 2 50 50 50}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {1 1 1 2 2 2}, ...
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/ModeSwitch/Switch_ING/Switch1_Sub
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'Init','CompRdy','CEBERdy','AllRdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {1 0 0 0 0 1 1 1 50 50 50}, ...
            {1 1 0 0 0 1 1 1 50 50 50}, ...
            {1 1 0 0 0 1 1 1 50 80 100}, ...
            {1 1 0 1 1 1 1 1 0 80 100}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 1 1 1}, ...
            {0 0 0 1 80 100}, ...
            {0 1 1 0 80 100}, ...
            {1 1 1 0 80 100}, ...
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/ModeSwitch/Switch_ING/Switch1_Sub
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'BE2LookUp'}, ...
    'lev2',{ ...
        {'NoChillChrg1','NoChillChrg2','NoChillChrg3','ChillChrg'},...
    }, ...
    'inName',{ ...
        { ...
            'sTmRefriModeMgr_D_u8ModeSwitchType',...
            'sTmComprCtrl_D_u8CmprRefriSwitchSt',...
            'D_u8EexvRefriSwitchStOld' ,...         
            'D_u8CexvRefriSwitchStOld'  ,...        
            'D_u8BexvRefriSwitchStOld' ,...         
            'X_s32EEXVPosReqOld'  ,...              
            'X_s32CEXVPosReqOld' ,...               
            'X_s32BEXVPosReqOld'  ,...              
            'sTmIn_X_s32EexvPosSts'   ,...          
            'sTmIn_X_s32CexvPosSts',...             
            'sTmIn_X_s32BexvPosSts' ,...            
            'B_InterChillDeicing',...              
            'Te_s32HvBattCooltTOutFilter' ,...      
            'Te_s32TAmb'  ,...                      
            'D_u8CarChrgMode' ,...                  
            'D_u8HvBattCoolgReq' ,...               
            'Te_s32HvBattCooltTReq'  ,...           
        }
    },...
    'rstName',{ ...
        { ...
            'sTmRefriVlvCtrl_D_u8EexvRefriSwitchSt',...
            'sTmRefriVlvCtrl_D_u8CexvRefriSwitchSt',...
            'sTmRefriVlvCtrl_D_u8BexvRefriSwitchSt' ,...         
            'sTmRefriVlvCtrl_X_s32EEXVPosReq'  ,...        
            'sTmRefriVlvCtrl_X_s32CEXVPosReq' ,...         
            'sTmRefriVlvCtrl_X_s32BEXVPosReq'  ,...                   
        }
    },...
    'inValue',{ ...
        { ...
            {2 2 0 0 0 5 5 5 5 5 5 0 25 25 1 1 30 }, ...
            {2 2 0 0 0 5 5 5 5 5 5 0 25 25 2 1 30 }, ...
            {2 2 0 0 0 5 5 5 5 5 5 0 25 25 3 1 30 }, ...
            {2 2 0 0 0 5 5 5 5 5 5 1 25 25 1 1 30 }, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {2 2 2 0 0 20}, ...
            {2 2 2 0 0 20}, ...
            {2 2 2 0 0 20}, ...
            {2 2 2 0 0 20}, ...
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM1_Chill/Subsystem/BexvPICalc_SM1/ID26200_BexvPIParaSM1/ID26200_SM1Err
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',false,...
    'lev1',{'ID26200_SM1Err'}, ...
    'lev2',{ ...
        {'pos','neg'},...
    }, ...
    'inName',{ ...
        { ...
            'Acture',...
            'sTmSigProces_Te_s32BattHvMaxFilter',...
            'sTmSigProces_Te_s32TAmb' ,...                 
        }
    },...
    'rstName',{ ...
        { ...
            'Te_u16SM1TargetSC',...
            'Dvt',...           
        }
    },...
    'inValue',{ ...
        { ...
            {15 30 30}, ...  % 10
            {5 30 30}, ...  % 10
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {10 5}, ...
            {10 -5}, ...
        }, ...
    }...
    )

%% Switch11  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'NotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {11 11 0 0 0 2 2 2 0 0 100}, ...
            {11 11 0 0 0 0 0 100 0 0 100}, ...
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 0 0 100}, ...
            {11 11 11 0 0 100}, ...
        }, ...
    }...
    )

%% Switch18 先后逻辑
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'init','compRdy','BC_Rdy','E_Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {18 0 0 0 0 5 5 5 6 6 6 }, ...
            {18 18 0 0 0 5 5 5 6 6 6 }, ...
            {18 18 0 0 0 5 5 5 6 80 100 }, ...
            {18 18 0 0 0 5 5 5 0 80 100 }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 5 5 5}, ...
            {0 0 0 5 80 100}, ...
            {0 18 18 0 80 100}, ...
            {18 18 18 0 80 100}, ...
        }, ...
    }...
    )

%% Switch17  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {17 17 0 0 0 5 5 5 6 0 0 25}, ...  % E C B
            {17 17 0 0 0 5 5 5 10 6 0 25}, ...  % E C B
            {17 17 0 0 0 5 5 5 10 0 6 25}, ...  % E C B
            {17 17 0 0 0 5 5 5 10 0 0 25}, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 10 0 0}, ...
            {0 0 0 10 0 0}, ...
            {0 0 0 10 0 0}, ...
            {17 17 17 10 0 0}, ...
        }, ...
    }...
    )

%% Switch13  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {17 17 0 0 0 5 5 5 6 0 75}, ...  % E C B
            {17 17 0 0 0 5 5 5 50 6 75}, ...  % E C B
            {17 17 0 0 0 5 5 5 50 0 6}, ...  % E C B
            {17 17 0 0 0 5 5 5 50 0 75}, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 50 0 75}, ...
            {0 0 0 50 0 75}, ...
            {0 0 0 50 0 75}, ...
            {17 17 17 50 0 75}, ...
        }, ...
    }...
    )


%% Switch4  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 3;
E = 18;
B = 0;
C = 30;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 B C 25 25 3 9 30}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 C 25 25 3 9 30}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E B 6 25 25 3 9 30}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E B C 25 25 3 9 30}, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E B C}, ...
            {0 0 0 E B C}, ...
            {0 0 0 E B C}, ...
            {swType swType swType E B C}, ...
        }, ...
    }...
    )

%% Switch12  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 12;
E = 100;
C = 0;
B = 0;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 B C}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 C}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E B 6}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E B C}, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E B C}, ...
            {0 0 0 E B C}, ...
            {0 0 0 E B C}, ...
            {swType swType swType E B C}, ...
        }, ...
    }...
    )

%% Switch3  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 3;
E = 18;
C = 0;
B = 5;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C B 25 25 3 9}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C 6 25 25 3 9}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 B 25 25 3 9}, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C B 25 25 3 9}, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {swType swType swType E C B }, ...
        }, ...
    }...
    )

%% Switch14  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 3;
E = 0;
C = 100;
B = 0;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C 6 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C B }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {swType swType swType E C B }, ...
        }, ...
    }...
    )

%% Switch8  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 3;
E = 100;
C = 100;
B = 0;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C 6 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C B }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {swType swType swType E C B }, ...
        }, ...
    }...
    )


%% Switch5  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 3;
E = 0;
C = 75;
B = 0;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C 6 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C B }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {swType swType swType E C B }, ...
        }, ...
    }...
    )

%% Switch15  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 15;
E = 0;
C = 100;
B = 100;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C 6 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C B }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {swType swType swType E C B }, ...
        }, ...
    }...
    )

%% Switch9  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 9;
E = 100;
C = 100;
B = 0;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C 6 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C B }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {swType swType swType E C B }, ...
        }, ...
    }...
    )

%% Switch7  直通
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 7;
E = 5;
C = 8;
B = 0;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{ModelName}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C 6 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C B }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {swType swType swType E C B }, ...
        }, ...
    }...
    )

%% Switch19  延时
[ModelName,PortsIn,PortsOut] = findModPorts(gcb, 'getType', 'Name')
swType = 19;
E = 20;
C = 100;
B = 100;

E2 = 100;
C2 = 0;
B2 = 0;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'BeforeDelay','AfterDelay'}, ...
    'lev2',{ ...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
        {'ENotRdy','CNotRdy','BNotRdy','Rdy'},...
    }, ...
    'inName',{ ...
        PortsIn,...
        PortsIn
    },...
    'rstName',{ ...
        PortsOut,...
        PortsOut
    },...
    'inValue',{ ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C 6 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E 6 B }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E C B }, ...  % E C B
        }, ...
        { ...
            {swType swType 0 0 0 5 5 5 6 C2 B2 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E2 C2 6 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E2 6 B2 }, ...  % E C B
            {swType swType 0 0 0 5 5 5 E2 C2 B2 }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {0 0 0 E C B}, ...
            {swType swType swType E C B }, ...
        }, ...
        { ...
            {0 0 0 E2 C2 B2 }, ...
            {0 0 0 E2 C2 B2 }, ...
            {0 0 0 E2 C2 B2 }, ...
            {swType swType swType E2 C2 B2 }, ...
        }, ...
    }...
    )


%% ModeEnd  
sw = 8;
E = 8;
C = 18;
B = 8;
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW8'}, ...
    'lev2',{ ...
        {'Init','SwtRdy','SovRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
            'D_u8SOV2RefriSwitchSt',...
            ...
            's32TAmb', ...
            's32HeatrAirTReqRamp', ...
            's32EvapFanFilter', ...
            's32HvacHexAirTFilter', ...
            'bHpcPtcEnad', ...
            'u8HvacFlowLevel', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   E C B   0 0 0      sw 0  127       0 25 40 10 35 true 9 }, ...  % E C B
            {0 0 0   5 5 5   E C B   sw sw sw   sw sw sw        0 25 40 10 35 true 9 }, ...  % E C B
            {0 0 0   5 5 5   E C B   sw sw sw   sw sw sw        sw 25 40 10 35 true 9 }, ...  % E C B
            {0 0 0   5 C 5   E C B   sw sw sw   sw sw sw        sw 25 40 10 35 true 9 }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {5 5 5 0 0 0 }, ...
            {5 C 5 1 0 1 }, ...
            {5 C 5 1 1 1 }, ...
        }, ...
    }...
    )

%% sw9

sw = 9;
E = 8;
C = 20;
B = 18;
createHarness(gcb, ...
    'lastStep','SW8',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW9'}, ...
    'lev2',{ ...
        {'Init','SwtRdy','SovRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
            'D_u8SOV2RefriSwitchSt',...
            's32EvapFanFilter', ...
            's32HeatrAirTReqRamp', ...
            'u8HvacFlowLevel', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127       0 10 35 9 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw        0 10 35 9 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw        sw 10 35 9 }, ...  % E C B
            {0 0 0   5 5 5   6 C B   sw sw sw   sw sw sw        sw 10 35 9 }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {5 5 5 0 0 0 }, ...
            {5 C B 1 0 0 }, ...
            {5 C B 1 1 1 }, ...
        }, ...
    }...
    )

%% sw10

sw = 10;
E = 20;
C = 20;
B = 18;
createHarness(gcb, ...
    'lastStep','SW9',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW10'}, ...
    'lev2',{ ...
        {'Init','SwtRdy','SovRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
            'D_u8SOV2RefriSwitchSt',...
            ...
            's32InletCal',...
            's32EvapFanReqRamp',...
            'u16BlwCool',...
            ...
            's32TAmb', ...
            's32HeatrAirTReqRamp', ...
            's32EvapFanFilter', ...
            's32HvacHexAirTFilter', ...
            'bHpcPtcEnad', ...
            'u8HvacFlowLevel', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127 0       25 3 400     25 40 10 35 true 9 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw 0        25 3 400     25 40 10 35 true 9 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw sw       25 3 400     25 40 10 35 true 9 }, ...  % E C B
            {0 0 0   5 5 5   E C 6   sw sw sw   sw sw sw sw       25 3 400     25 40 10 35 true 9 }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {5 5 5 0 0 0 }, ...
            {E C 5 0 0 1 }, ...
            {E C 5 1 1 1 }, ...
        }, ...
    }...
    )
%% sw1
sw = 1;
E = 20;
C = 20;
B = 18;
createHarness(gcb, ...
    'lastStep','SW10',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW1'}, ...
    'lev2',{ ...
        {'Init','MainStRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
%             ...
%             's32InletCal',...
%             's32EvapFanReqRamp',...
%             'u16BlwCool',...
%             ...
%             's32TAmb', ...
%             's32HeatrAirTReqRamp', ...
%             's32EvapFanFilter', ...
%             's32HvacHexAirTFilter', ...
%             'bHpcPtcEnad', ...
%             'u8HvacFlowLevel', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127      }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw        }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw       }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {5 5 5 0 0 0 }, ...
            {5 5 5 1 1 1 }, ...
        }, ...
    }...
    )

%% sw11
sw = 11;
E = 20;
C = 20;
B = 20;
createHarness(gcb, ...
    'lastStep','SW1',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW11'}, ...
    'lev2',{ ...
        {'Init','MainStRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
%             ...
%             's32InletCal',...
%             's32EvapFanReqRamp',...
%             'u16BlwCool',...
%             ...
%             's32TAmb', ...
%             's32HeatrAirTReqRamp', ...
%             's32EvapFanFilter', ...
%             's32HvacHexAirTFilter', ...
%             'bHpcPtcEnad', ...
%             'u8HvacFlowLevel', ...
%             ...
%             'bInterChillDeicing', ...
%             's32HvBattCooltTOutFilter', ...
%             's32TAmb', ...
%             'u8CarChrgMode', ...
%             'u8HvBattCoolgReq', ...
%             's32HvBattCooltTReq', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw  }, ...  % E C B
            {0 0 0   5 5 B   6 6 B   sw sw sw   sw sw sw  }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {5 5 B 1 1 0 }, ...
            {5 5 B 1 1 1 }, ...
        }, ...
    }...
    )

%             {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127      true 30 25 0 3 30}, ...  % E C B
%             {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw       true 30 25 0 3 30}, ...  % E C B
%             {0 0 0   5 5 5   6 6 B   sw sw sw   sw sw sw       true 30 25 0 3 30}, ...  % E C B

%% sw12
sw = 12;
E = 20;
C = 20;
B = 20;
createHarness(gcb, ...
    'lastStep','SW11',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW12'}, ...
    'lev2',{ ...
        {'Init','MainStRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
%             ...
%             's32InletCal',...
%             's32EvapFanReqRamp',...
%             'u16BlwCool',...
%             ...
%             's32TAmb', ...
%             's32HeatrAirTReqRamp', ...
%             's32EvapFanFilter', ...
%             's32HvacHexAirTFilter', ...
%             'bHpcPtcEnad', ...
%             'u8HvacFlowLevel', ...
%             ...
%             'bInterChillDeicing', ...
%             's32HvBattCooltTOutFilter', ...
%             's32TAmb', ...
%             'u8CarChrgMode', ...
%             'u8HvBattCoolgReq', ...
%             's32HvBattCooltTReq', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      [12 19] 0  127 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   [12 19] sw sw  }, ...  % E C B
            {0 0 0   E 5 5   E 6 6   sw sw sw   [12 19] sw sw  }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {E 5 5 0 1 1 }, ...
            {E 5 5 1 1 1 }, ...
        }, ...
    }...
    )

%% sw13
sw = 13;
E = 18;
C = 20;
B = 15;
createHarness(gcb, ...
    'lastStep','SW12',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW13'}, ...
    'lev2',{ ...
        {'Init','MainStRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw  }, ...  % E C B
            {0 0 0   E 5 B   E 6 B   sw sw sw   sw sw sw  }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {E 5 B 0 1 0 }, ...
            {E 5 B 1 1 1 }, ...
        }, ...
    }...
    )

%% sw14
sw = 14;
E = 18;
C = 20;
B = 15;
createHarness(gcb, ...
    'lastStep','SW13',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW14'}, ...
    'lev2',{ ...
        {'Init','MainStRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw  }, ...  % E C B
            {0 0 0   5 C 5   6 C 6   sw sw sw   sw sw sw  }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {5 C 5 1 0 1 }, ...
            {5 C 5 1 1 1 }, ...
        }, ...
    }...
    )

%% sw15
sw = 15;
E = 18;
C = 30;
B = 15;
createHarness(gcb, ...
    'lastStep','SW14',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW15'}, ...
    'lev2',{ ...
        {'Init','MainStRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw  }, ...  % E C B
            {0 0 0   5 C B   6 C B   sw sw sw   sw sw sw  }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {5 C B 1 0 0 }, ...
            {5 C B 1 1 1 }, ...
        }, ...
    }...
    )

%% sw17
sw = 17;
E = 80;
C = 30;
B = 15;
createHarness(gcb, ...
    'lastStep','SW15',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW17'}, ...
    'lev2',{ ...
        {'Init','MainStRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw  }, ...  % E C B
            {0 0 0   E 5 5   E 6 6   sw sw sw   sw sw sw  }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {E 5 5 0 1 1 }, ...
            {E 5 5 1 1 1 }, ...
        }, ...
    }...
    )

%% sw3
sw = 3;
E = 18;
C = 0;
B = 0;
createHarness(gcb, ...
    'lastStep','SW17',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'SW3'}, ...
    'lev2',{ ...
        {'Init','MainStRdy','Finish'},...
    }, ...
    'inName',{ ...
        { ...
            'D_u8EexvMoveEndOld', ...
            'D_u8CexvMoveEndOld', ...
            'D_u8BexvMoveEndOld', ...
            'X_s32EEXVPosReqOld', ...
            'X_s32CEXVPosReqOld', ...
            'X_s32BEXVPosReqOld', ...
            'X_s32EexvPosSts',...
            'X_s32CexvPosSts',...
            'X_s32BexvPosSts',...
            'D_u8EexvRefriSwitchSt',...
            'D_u8CexvRefriSwitchSt',...
            'D_u8BexvRefriSwitchSt',...
            ...
            'D_u8ModeSwitchType', ...
            'D_u8ModeSwitchTypeLoc', ...
            'D_u8HpModeMainState', ...
        },
    },...
    'rstName',{ ...
        { ...
            'X_s32EEXVPosReq',...
            'X_s32CEXVPosReq',...
            'X_s32BEXVPosReq',...
            'D_u8EexvMoveEnd',...
            'D_u8CexvMoveEnd',...
            'D_u8BexvMoveEnd',...
        },
    },...
    'inValue',{ ...
        { ...
            {0 0 0   5 5 5   6 6 6   0 0 0      sw 0  127 }, ...  % E C B
            {0 0 0   5 5 5   6 6 6   sw sw sw   sw sw sw  }, ...  % E C B
            {0 0 0   5 5 B   6 6 B   sw sw sw   sw sw sw  }, ...  % E C B
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {5 5 5 0 0 0 }, ...
            {5 5 B 1 1 0 }, ...
            {5 5 B 1 1 1 }, ...
        }, ...
    }...
    )

%% TmRefriVlvCtrl/TmRefriVlvCtrl/EXVPosCal/SM6_ParaDehumid/ID26172_EEXVMaxMinLimit
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'waitTime',0.05,...
    'mask',false,...
    'lev1',{'EEXVMaxMinLimit'}, ...
    'lev2',{ ...
        {'MinLim','Norm','MaxLim'},...
    }, ...
    'inName',{ ...
        { ...
            'X_s32EEXVPosReq', ...
            'sTmComprCtrl_D_u8HvacFlowLevel', ...
            'sTmSigProces_Te_s32TAmb', ...
        },
    },...
    'rstName',{ ...
        { ...
            'sTmRefriVlvCtrl_X_s32EEXVPosReq',...
        },
    },...
    'inValue',{ ...
        { ...
            {-10 10 0}, ...  % 20
            {10 10 0}, ...  % 20
            {30 10 0}, ...  % 20
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {0}, ...
            {10}, ...
            {20}, ...
        }, ...
    }...
    )