%% TmSovCtrl/TmSovCtrl/SpecialProces/SOV4
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',0,...
    'lev1',{'NoProtect'}, ...
    'lev2',{ ...
        {'Sov4OnBasedCompClose','Sov4RawIsOn', 'Sov4RawIsOff',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov4ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmPumpCtrl_L_s32BpumpFlwEstmd ',...
            'sTmIn_D_u8DCChrgSt ',...
            'sTmSigProces_D_u8BattThermReq',...
            ...,
            'sTmIn_Te_s32HvBattCooltTReq ',...
            'sTmIn_Te_s32HvBattCooltT ',...
            'sTmSigProces_Te_s32BattHvMaxFilter ',...
            'sTmSigProces_Te_s32HvBattCooltTFilter',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV4_B_HpmSov4ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false false 20 10 10 1 25 30 30 30}, ... 
            {true true 20 10 10 1 25 30 30 30}, ... 
            {false true 20 10 10 1 25 30 30 30}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {1}, ...  
            {0}, ... 
        }, ...
    }...
    )
% HighPressProtect
createHarness(gcb, ...
    'lastStep','NoProtect',...  % Initialize
    'mask',0,...
    'lev1',{'HighSidePProtect'}, ...
    'lev2',{ ...
        {'HighPWithBattThermReq','HighPWithoutBattThermReq',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov4ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmPumpCtrl_L_s32BpumpFlwEstmd ',...
            'sTmIn_D_u8DCChrgSt ',...
            'sTmSigProces_D_u8BattThermReq',...
            ...,
            'sTmIn_Te_s32HvBattCooltTReq ',...
            'sTmIn_Te_s32HvBattCooltT ',...
            'sTmSigProces_Te_s32BattHvMaxFilter ',...
            'sTmSigProces_Te_s32HvBattCooltTFilter',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV4_B_HpmSov4ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true true 25 10 10 1 25 30 30 30}, ... 
            {true true 25 10 10 0 25 30 30 30}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {1}, ...  
            {0}, ... 
        }, ...
    }...
    )
% PumpFlwProtect
createHarness(gcb, ...
    'lastStep','HighSidePProtect',...  % Initialize
    'mask',0,...
    'lev1',{'PumpFlwProtect'}, ...
    'lev2',{ ...
        {'HighPWithBattThermReq','HighPWithoutBattThermReq',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov4ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmPumpCtrl_L_s32BpumpFlwEstmd ',...
            'sTmIn_D_u8DCChrgSt ',...
            'sTmSigProces_D_u8BattThermReq',...
            ...,
            'sTmIn_Te_s32HvBattCooltTReq ',...
            'sTmIn_Te_s32HvBattCooltT ',...
            'sTmSigProces_Te_s32BattHvMaxFilter ',...
            'sTmSigProces_Te_s32HvBattCooltTFilter',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV4_B_HpmSov4ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true true 20 10 10 1 25 30 30 30}, ... 
            {true true 20 0 10 1 25 30 30 30}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {1}, ...  
            {0}, ... 
        }, ...
    }...
    )

% BattCoolTProtect
createHarness(gcb, ...
    'lastStep','PumpFlwProtect',...  % Initialize
    'nextStep','BattCooltErrProt',...
    'mask',0,...
    'lev1',{'BattCoolTProtect'}, ...
    'lev2',{ ...
        {'DCChrgSt12Prot','DCChrgSt12NoProt',...  % yTmComprCtrl_B_CompOnReq is On
        'DCChrgSt2Prot','DCChrgSt2NoProt',...
        'DCChrgStNormProt','DCChrgStNormNoProt',
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov4ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmPumpCtrl_L_s32BpumpFlwEstmd ',...
            'sTmIn_D_u8DCChrgSt ',...
            'sTmSigProces_D_u8BattThermReq',...
            ...,
            'sTmIn_Te_s32HvBattCooltTReq ',...
            'sTmIn_Te_s32HvBattCooltT ',...
            'sTmSigProces_Te_s32BattHvMaxFilter ',...
            'sTmSigProces_Te_s32HvBattCooltTFilter',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV4_B_HpmSov4ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true true 20 10 12 1 25 [18 20] 30 30}, ... 
            {true true 20 10 12 1 25 [23 20] 30 30}, ... 
            {true true 20 10 2 1 25 [19 20] 30 30}, ... 
            {true true 20 10 2 1 25 [24 20] 30 30}, ... 
            {true true 20 10 0 1 25 [15 16] 30 30}, ... 
            {true true 20 10 0 1 25 [20 16] 30 30}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {0}, ...  
            {1}, ... 
            {0}, ...  
            {1}, ... 
            {0}, ...  
            {1}, ... 
        }, ...
    }...
    )

% BattCooltErrProt
createHarness(gcb, ...
    'lastStep','BattCoolTProtect',...  % Initialize
    'mask',0,...
    'lev1',{'BattCooltErrProt'}, ...
    'lev2',{ ...
        {'SupChargProt','SupChargNoProt','NormChargProt','NormChargNoProt',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov4ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmPumpCtrl_L_s32BpumpFlwEstmd ',...
            'sTmIn_D_u8DCChrgSt ',...
            'sTmSigProces_D_u8BattThermReq',...
            'sTmIn_Te_s32HvBattCooltT ',...
            ...,
            'sTmSigProces_Te_s32HvBattCooltTFilter',...
            'sTmIn_Te_s32HvBattCooltTReq ',...
            'sTmSigProces_Te_s32BattHvMaxFilter ',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV4_B_HpmSov4ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true true 20 10 12 1 30   [28.5 30] 30 40}, ... 
            {true true 20 10 12 1 30   [32 30] 30 40}, ... 
            {true true 20 10 0  1 30   [26 28] 30 40}, ... 
            {true true 20 10 0  1 30   [29 28] 30 40 }, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {0}, ...  
            {1}, ... 
            {0}, ...  
            {1}, ... 
        }, ...
    }...
    )

% BattMaxErrProt
createHarness(gcb, ...
    'lastStep','BattCooltErrProt',...  % Initialize
    'mask',0,...
    'lev1',{'BattMaxErrProt'}, ...
    'lev2',{ ...
        {'SupChargProt','SupChargNoProt','NormChargNoProt',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov4ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmPumpCtrl_L_s32BpumpFlwEstmd ',...
            'sTmIn_D_u8DCChrgSt ',...
            'sTmSigProces_D_u8BattThermReq',...
            'sTmIn_Te_s32HvBattCooltT ',...
            ...,
            'sTmSigProces_Te_s32HvBattCooltTFilter',...
            'sTmIn_Te_s32HvBattCooltTReq ',...
            'sTmSigProces_Te_s32BattHvMaxFilter ',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV4_B_HpmSov4ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true true 20 10 12 1 30   40 30 [32 32.5]}, ... 
            {true true 20 10 12 1 30   40 30 [33 32.5]}, ... 
            {true true 20 10 0  1 30   40 30 40}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {0}, ...  
            {1}, ... 
            {1}, ... 
        }, ...
    }...
    )

%% TmSovCtrl/TmSovCtrl/SpecialProces/SOV5
createHarness(gcb, ...
    'lastStep','Initialize',...  % Initialize
    'mask',0,...
    'lev1',{'NoProtect'}, ...
    'lev2',{ ...
        {'Sov5OnBasedCompClose','Sov5RawIsOn', 'Sov5RawIsOff',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov5ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'yTmIn_B_AirCondEnbl ',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmSigProces_md_u16BlwCool',...
            'sTmSigProces_Te_s32EvapFanFilter',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV5_B_HpmSov5ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true false true 20 40 3}, ... 
            {true true true 20 40 3}, ... 
            {false true true 20 40 3}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {1}, ...  
            {0}, ... 
        }, ...
    }...
    )
% HighPressProtect
createHarness(gcb, ...
    'lastStep','NoProtect',...  % Initialize
    'mask',0,...
    'lev1',{'HighPressProtect'}, ...
    'lev2',{ ...
        {'HighPressWithCondEn','HighPressWithoutCondEn',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov5ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'yTmIn_B_AirCondEnbl ',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmSigProces_md_u16BlwCool',...
            'sTmSigProces_Te_s32EvapFanFilter',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV5_B_HpmSov5ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true true true 25 40 3}, ... 
            {true true false 25 40 3}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {0}, ...  
        }, ...
    }...
    )

% BlwCoolProtect
createHarness(gcb, ...
    'lastStep','HighPressProtect',...  % Initialize
    'mask',0,...
    'lev1',{'BlwCoolProtect'}, ...
    'lev2',{ ...
        {'BlwCoolHigh','BlwCoolLow',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov5ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'yTmIn_B_AirCondEnbl ',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmSigProces_md_u16BlwCool',...
            'sTmSigProces_Te_s32EvapFanFilter',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV5_B_HpmSov5ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true true true 20 40 3}, ... 
            {true true true 20 30 3}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {0}, ...  
        }, ...
    }...
    )

% EvapProtect
createHarness(gcb, ...
    'lastStep','BlwCoolProtect',...  % Initialize
    'mask',0,...
    'lev1',{'EvapProtect'}, ...
    'lev2',{ ...
        {'EvapHigh','EvapLow',...  % yTmComprCtrl_B_CompOnReq is On
        },...
    }, ...
    'inName',{ ...
        { 
            'xTmSovCtrl_B_Sov5ReqRaw',...
            'yTmComprCtrl_B_CompOnReq',...
            'yTmIn_B_AirCondEnbl ',...
            'rGlAcVlvCtrl_p_AirCondHiSideBar',...
            'sTmSigProces_md_u16BlwCool',...
            'sTmSigProces_Te_s32EvapFanFilter',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'ySOV5_B_HpmSov5ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true true true 20 40 [3 2]}, ... 
            {true true true 20 30 [1 2]}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {1}, ... 
            {0}, ...  
        }, ...
    }...
    )

%% TmSovCtrl/TmSovCtrl/StaticMode
createHarness(gcb, ...
    'Initialize',...  % Initialize
    'mask',0,...
    'lev1',{'StaticMode'}, ...
    'lev2',{ ...
        {'SM0','SM1237','SM456','SM20','SM21','SM22','SM23'
        },...
    }, ...
    'inName',{ ...
        { 
            'sTmRefriModeMgr_D_u8HpModeMainState',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'APP_u8SOV1ReqState',...
            'APP_u8SOV2ReqState',...
            'APP_u8SOV3ReqState',...
            'APP_u8SOV4ReqState',...
            'APP_u8SOV5ReqState',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {0}, ... 
            {[1 2 3 7]}, ... 
            {[4 5 6]}, ... 
            {20}, ... 
            {21}, ... 
            {22}, ... 
            {23}, ... 
            {127}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {1 0 1 1 1}, ... 
            {0 0 1 1 1}, ...  
            {1 1 0 1 1}, ...  
            {1 0 1 1 1}, ... 
            {1 0 1 1 0}, ... 
            {1 0 1 0 1}, ... 
            {1 0 1 1 1}, ... 
            {1 0 1 1 1}, ... 
        }, ...
    }...
    )

%% TmSovCtrl/TmSovCtrl/Sov45BothOffProtect
createHarness(gcb, ...
    'Initialize',...  % Initialize
    'mask',0,...
    'lev1',{'Sov45BothOffProtect'}, ...
    'lev2',{ ...
        {'SOV00','SOV01','SOV10','SOV11'
        },...
    }, ...
    'inName',{ ...
        { 
            'yTmSovCtrl_B_HpmSov4ActvCmd',...
            'yTmSovCtrl_B_HpmSov5ActvCmd',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'yTmSovCtrl_B_HpmSov5ActvCmdBothOffProtect',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {false false}, ... 
            {false true}, ... 
            {true false}, ... 
            {true true}, ... 
        }, ...
      
    },...
    'rstValue',{ ...
        { ...
            {true}, ... 
            {true}, ...  
            {false}, ...  
            {true}, ... 
        }, ...
    }...
    )

%% TmSovCtrl/TmSovCtrl/Diag2F
createHarness(gcb, ...
    'Initialize',...  % Initialize
    'mask',0,...
    'lev1',{'Sov1','Sov2','Sov3','Sov4','Sov5'}, ...
    'lev2',{ ...
        {'Norm','Diag2F',...
        },...
        {'Norm','Diag2F',...
        },...
        {'Norm','Diag2F',...
        },...
        {'Norm','Diag2F',...
        },...
        {'Norm','Diag2F',...
        },...
    }, ...
    'inName',{ ...
        { 
            'yTmDiag_B_HpmSov1ActvCmd2F',...
            'sTmDiag_D_u8HpmSov1Actv2FEnState',...
            'yTmSovCtrl_B_HpmSov1ActvCmd',...
            ...,
        }, ...
        { 
            'yTmDiag_B_HpmSov2ActvCmd2F',...
            'sTmDiag_D_u8HpmSov2Actv2FEnState',...
            'yTmSovCtrl_B_HpmSov2ActvCmd',...
            ...,
        }, ...
        { 
            'yTmDiag_B_HpmSov3ActvCmd2F',...
            'sTmDiag_D_u8HpmSov3Actv2FEnState',...
            'yTmSovCtrl_B_HpmSov3ActvCmd',...
            ...,
        }, ...
        { 
            'yTmDiag_B_ChillerValveReq2F',...
            'sTmDiag_D_u8ChillerValve2FEnState',...
            'yTmSovCtrl_B_HpmSov4ActvCmd',...
            ...,
        }, ...
        { 
            'yTmDiag_B_EvaprVlvReqFrnt2F',...
            'sTmDiag_D_u8EvaprVlvFrnt2FEnState',...
            'yTmSovCtrl_B_HpmSov5ActvCmd',...
            ...,
        }, ...
    },...
    'rstName',{ ...
        { 
            'y2F_B_HpmSov1ActvCmd',...
        }, ...
        { 
            'y2F_B_HpmSov2ActvCmd',...
        }, ...
        { 
            'y2F_B_HpmSov3ActvCmd',...
        }, ...
        { 
            'y2F_B_HpmSov4ActvCmd',...
        }, ...
        { 
            'y2F_B_HpmSov5ActvCmd',...
        }, ...
    },...
    'inValue',{ ...
        { ...
            {true 0 false}, ... 
            {true 2 false}, ... 
        }, ...
        { ...
            {true 0 false}, ... 
            {true 2 false}, ... 
        }, ...
        { ...
            {true 0 false}, ... 
            {true 2 false}, ... 
        }, ...
        { ...
            {true 0 false}, ... 
            {true 2 false}, ... 
        }, ...
        { ...
            {true 0 false}, ... 
            {true 2 false}, ... 
        }, ...
    },...
    'rstValue',{ ...
        { ...
            {false}, ... 
            {true}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
        }, ...
        { ...
            {false}, ... 
            {true}, ...  
        }, ...
    }...
    )